duckduckgo/zeroclickinfo-spice

share/spice/timer/timer.js
See #1389 for background.
I tried using the jquery `on('load', ...)` approach to detect the injection of the `link` element, but it wasn't working, thus why I used the `setInterval` approach instead.
=> Fix for issue #1389

share/spice/code_search/code_search.js
I added the `sourceIconUrl` as recommended in #1388. Also changed the `sourceUrl` to use https and the same URL.
=> Add favicon to codesearch. Fixes #1388.

share/spice/flights/route/flights_route.js
Currently, the flights by route IA displays a month and day in the arrival time for overnight flights. However, the display uses a numerical representation for months, which can be hard to interpret given the adjacent location to the arrival time. This PR explicitly spells out each month.
=> Explicitly spell out months for overnight flights

share/spice/dns/dns.js
+ Fixing #1395 - Changing `name` value to "Answer"
+ Adding additional error checking of api_result. - `if (!api_result)`
=> DNS: Change name value to "Answer". Add error checking of api_result.

share/spice/people_in_space/people_in_space.js
@jagtalon The people in space api changed and the url link is broken.  This fixes that.
=> people in space: fix url link

share/spice/stocks/stocks.css
Prepended relevant styles with `.zci--stocks` to namespace the CSS.
Fixes #1284
=> Namespaced Stocks ZCI CSS

share/spice/packagist/packagist.js
Changing normalization of download # from regex to DDG.commifyNumber()
=> Packagist.js - Normalizing downloads with DDG function.

LICENSE
Copied the license from http://www.apache.org/licenses/LICENSE-2.0.txt -- not sure why the brackets are different there, but its the most official source, so I'm going with it.
=> Update LICENSE, restore boilerplate text

share/spice/xkcd/display/xkcd_display.css
Fixes #1384.
Not completely sure whether I should update the IA attribution for a quick CSS fix or not.
=> Xkcd: fixed floating of prev/next buttons for IE8

lib/DDG/Spice/Nutrition.pm, t/Nutrition.t
Hope you don't mind me doing this one.
The IA now supports queries like "tofu calories" and "tofu how many calories". Tests updated, too.
=> Nutrition: added trigger support for different word order, fixes #1425

template/share/spice/example/example.js
@moollaza I see this come up a lot in PR requests, `api_result` not being checked. Might as well add it to the template.
=> Template: Add error checking of api_result

share/spice/airlines/airlines.js, share/spice/airlines/content.handlebars
Addresses #1436 
Currently, the airlines IA (which searches by airline code and flight numbers) and the flights_route IA (which searches by airline and source/destination cities) do not share any code. This PR unifies the appearance of the two IAs. Eventually, we should try to unify the two IAs to avoid having to maintain two different sets of code. (This is on my list of weekend projects to attempt :)
=> Update airlines IA display to mirror flights_route

share/spice/movie/movie.js
Fixes #1339
Ping pong @jagtalon 
**Example:**
__________________________________________
~~Note: There may be a relevancy issue, example search for "Babe 2006" https://duckduckgo.com/?q=Babe+2006+rotten+tomatoes~~ Fixed
=> Movie: Check movie year against searched year

.travis.yml
Since .travis.yml is autogenerated by https://github.com/SineSwiper/Dist-Zilla-TravisCI, we can't just modify that file ourselves. We'd have to wait for https://github.com/SineSwiper/Dist-Zilla-TravisCI/issues/25 to get fixed first.
@moollaza
=> .travis.yml: Remove sudo: false

share/spice/go_watch_it/go_watch_it.css, share/spice/go_watch_it/go_watch_it.js
This is a dirty fix, but the UI breaks when we display images that's not from us:
Easiest fix is to remove them for now until we either have:
- Better images
- Resize their image so that it doesn't break the UI (this is also easy but requires extensive testing. Also GoWatchIt's images don't work well on retina screens)
=> GoWatchIt: Don't display if we don't have any images for them

lib/DDG/Spice/Timer.pm
It makes sense for a search like `time 3 minutes` to bring up the countdown timer.
=> Timer: add new trigger (time)

share/spice/bible/bible.js, share/spice/bitcoin_balance/bitcoin_balance.js, share/spice/book/book.js, share/spice/fedora_project_package_db/fedora_project_package_db.js, share/spice/in_every_lang/in_every_lang.js, share/spice/leak_db/leak_db.js, share/spice/maven/maven.js, share/spice/npm/npm.js, share/spice/packagist/packagist.js, share/spice/population/population.js, share/spice/rainfall/rainfall.js, share/spice/tvmaze/nextepisode/tvmaze_nextepisode.js, share/spice/tvmaze/previousepisode/tvmaze_previousepisode.js, share/spice/tvmaze/show/tvmaze_show.js
Possible improvement to `sourceName`. I've left timeanddate.com and xe.com as these are brand names including the extention.
https://github.com/duckduckgo/zeroclickinfo-spice/pull/1474#issuecomment-72935193
CC// @jagtalon
=> Update sourceName removing FQDN extention

share/spice/sales_tax/sales_tax.js
Fixing #1496 | [View online](http://duckpan.mrchris.me/?q=sales+tax+pa&ia=answer)
Currently displaying **0%** for no tax states.
_______________________
=> SalesTax: Update title, add subtitle. Standardize design

share/spice/betterific/betterific.js, share/spice/betterific/content.handlebars, share/spice/detect_lang/content.handlebars, share/spice/detect_lang/detect_lang.js, share/spice/go_watch_it/content.handlebars, share/spice/go_watch_it/go_watch_it.js, share/spice/movie/movie.js, share/spice/movie/subtitle_content.handlebars, share/spice/open_snp/open_snp.handlebars, share/spice/open_snp/open_snp.js, share/spice/translate/detect/translate_detect.js, share/spice/translate/from_to/translate_from_to.js, share/spice/translate/translate_from_to.handlebars
=> Standardise Handlebars helpers

lib/DDG/Spice/InEveryLang.pm
Solves the gzip issue on my API - now the DDG api responses come pre-wrapped with the JSONP callback. It's a bit brittle and coupled, so things will blow up if the callback naming format ever changes, but we can cross that bridge when we get there.
=> use new ddg-wrapped jsonp api endpoints

share/spice/amazon/amazon.js
The `loadedRatingsData` var isn't used anymore, and the `items` local var isn't necessary since it's only referenced in one place now.
@moollaza @jagtalon
=> Remove unused local vars in amazon spice js

share/spice/movie/movie.js
We're moving to `DDG.is3x` and `DDG.is2x` now.
=> movie.js: remove the use of is_retina because it's being deprecated.

lib/DDG/Spice/RandPOS.pm, share/spice/rand_pos/content.handlebars, share/spice/rand_pos/rand_pos.js, t/RandPOS.t
This is my first attempt at a Spice so excuse any daft mistakes.. :wink: It uses Wordnik to return random words in particular parts of speech (noun, verb, adjective, pronoun, adverb, preposition and conjunction). If the query includes the part of speech in plural it returns five words, otherwise is returns one.
It gives people examples of words in a part of speech, which can be helpful when learning grammar. Rather than seeing a description of a grammatical idea, seeing examples is often the easiest way to understand what e.g. a noun, verb or whatever is.
Wordnik …
=> New spice to return words in specified part of speech

lib/DDG/Spice/Coursebuffet.pm, share/spice/coursebuffet/coursebuffet.js
HTTP endpoint not working anymore. HTTPS is working so we're moving there.
I had to change the image endpoint as well so that it wouldn't break:
=> HOTFIX: CourseBuffet: API endpoint is down because it's using HTTPS

lib/DDG/Spice/RandWord.pm
The canonical naming convention is to reference the provider name, not the Spice name. We're using this APIKEY in other Instant Answers so it makes sense to reference the Provider and not the IA name.
Note: There is a corresponding change to the close-source code
/cc @jagtalon
=> Use provider name for Env APIKEY variable

share/spice/bbc/bbc.js
This was an already-declared variable set to either 'TV' or 'Radio'
depending on which type of station the user asked for.
=> BBC: Use header_service_type for name field

share/spice/currency/currency.css
=> currency.css: Hovering / clicking on mobile has ugly underline.

lib/DDG/Spice/BBC.pm, share/spice/bbc/bbc.js
At the moment with the BBC results, the "More at" link goes to the BBC homepage.  This PR makes that link go to the relevant schedule page.
=> BBC: link to schedule

lib/DDG/Spice/Rainfall.pm
Recently Travis started to fail Rainfall tests.
Those two commits make them pass again.
The first commit is just whitespace fixup.
The second commit has the acutal fix.
The issue is that some variants of the country data report Bolivia as
```
Bolivia, Plurinational State of
```
(comma after 'Bolivia') while others use
```
Bolivia (Plurinational State of)
```
(space and opening paren after 'Bolivia').
This difference [recently made made travis tests fail](https://travis-ci.org/duckduckgo/zeroclickinfo-spice/jobs/52748092#L1663). We now split
country names at both comma and ' (' to identify the main country name
for both variants. Thereby, tests pass again in travis.
=> Fix Rainfall tests for travis

lib/DDG/Spice/IsItUp.pm, lib/DDG/Spice/Namecheap.pm, lib/DDG/Util/SpiceConstants.pm, share/spice/namecheap/namecheap.css, share/spice/namecheap/namecheap.handlebars, share/spice/namecheap/namecheap.js, t/Namecheap.t
When a user's query begins with "namecheap", we do a domain lookup to the NC API. If the domain is available, a purchase link to Namecheap is provided. If not, a link to make an offer to the owner is provided via DomainAgents.
The instant answer provides a simple way of purchasing domains straight from a user's DDG query.
[NameCheap API](https://www.namecheap.com/support/api/intro.aspx)
It provides responses for TLDs that relate to NameCheap. Modular + expandable :+1: 
Many alternative …
=> Namecheap Instant Answer

lib/DDG/Spice/Keybase.pm, share/spice/keybase/keybase.js
The Keybase IA attempts to check if an object (`api_result.them`) returned by the keybase API is an array however if this doesn't exist it throws an exception as we're checking an undefined object.
This is currently in production: https://duckduckgo.com/?q=keybase+moollaza
I've also updated the example_queries as discussed in #1581
=> Keybase Hotfix: Check returned status

share/spice/amazon/amazon.js
The regex for Amazon reviews needs to include '.jp' to match results from amazon.jp
=> Update regex for amazon.jp review urls

share/spice/transit/njt/train_item.handlebars, share/spice/transit/njt/transit_njt.css, share/spice/transit/path/train_item.handlebars, share/spice/transit/path/transit_path.css, share/spice/transit/septa/train_item.handlebars, share/spice/transit/septa/transit_septa.css
=> Replaced hard-coded colours with site-wide class names (fixes #1600)

lib/DDG/Spice/Forecast.pm, t/Forecast.t
The weather IA is overtriggering and producing some odd results when we pass Forecast an extracted location that it does not fail on. To try to address this, I would like to limit the keyword triggering for this IA to only "weather," and then handle all other potential weather/forecast-related queries with an internal trigger that looks at search results to infer the user's intent.
=> Remove all trigger words except for "weather"

lib/DDG/Spice/Nutrition.pm, t/Nutrition.t
Removed some of the ambiguous trigger words so things like `carbon fiber wrap` don't trigger.
Internal pr will take care of the rest of the relevancy. 
fixes #1616
=> nutrition relevancy

share/spice/quandl/fundamentals/content.handlebars, share/spice/quandl/home_values/content.handlebars
Added in our DDG text classes. Darkens header and subheader colours slightly:
- https://ddh7.duckduckgo.com/?q=aapl+revenue&ia=fundamentals
- https://ddh7.duckduckgo.com/?q=19087+3+bedroom+home&ia=homevalues
//cc @brianrisk @abeyang
=> Add zci__header, zci__subheader and text-primary classes for better colours

lib/DDG/Spice/ProductHunt.pm
Wasn't sure where this API came from or if the keys needed to be hidden.
PH explains that others are free to use this endpoint and should use their given API key.
/cc @jagtalon @zekiel
=> ProductHunt: Comment to explain the ProductHunt API we're using

share/spice/brainy_quote/content.handlebars
fixes #805 
Cutting off at 200, was breaking the design, so i set this at 150 chars.
=> BrainyQuote: Cut at 150 chars (fixes #805)

share/spice/quandl/fundamentals/fundamentals_triggers.yml, share/spice/quandl/fundamentals/tickers.txt
@moollaza After seeing which API requests were called over the past few days, I have noticed that certain ticker symbols and certain trigger phrases were being called in combinations that implied the users did not truly desire fundamentals data with those queries.
A removed trigger is "price".  While "AAPL price" strongly implies a fundamentals response, "FORD price" does not.  In the end, I decided that "price" as an indicator would produce more inappropriate queries than not.
I also removed many ticker symbols that had common meanings when paired with indicators.  For example those submitting "HOME income" and "HOME revenue" queries are most likely interested in making money at home.
Note that many tickers are English words, and I did not remove those that, when paired with indicator …
=> Removed ambiguous tickers and triggers

lib/DDG/Spice/RxInfo.pm, share/spice/rx_info/rx_info.js, share/spice/rx_info/triggerWords.txt, t/RxInfo.t
Fixing #1542 
Currently the RxInfo Spice triggers on small English two letter/three letter words: `aa ad ae am an as at be by do go ha he hi id if in is it me no of ok on or pi so to up us we`. 
Examples:
https://duckduckgo.com/?q=tablet+of+blue+color
https://duckduckgo.com/?q=tablet+is
https://duckduckgo.com/?q=capsule+age
Use DDG.isRelevant and call Spice.failed if no relevant results are found
=> RxInfo: Update to use isRelevant to avoid returning invaild results

.travis.yml, lib/DDG/Spice/Hearthstone.pm, share/spice/hearthstone/hearthstone.css, share/spice/hearthstone/hearthstone.handlebars, share/spice/hearthstone/hearthstone.js, t/Hearthstone.t
It shows infos about any Hearthstone card with a thumbnail.
It allows to get instantly main informations like what a card does, without searching in a database or a wiki.
Gamepedia Hearthstone Wiki
http://hearthstone.gamepedia.com/
It seems to be the most accurate, and has image for every card.
Not better alternatives:
http://hearthstonejson.com/
http://hearthstoneapi.herokuapp.com/
hearthstone leeroy
hearthstone …
=> Hearthstone Spice debut

lib/DDG/Spice/Forecast.pm, t/Forecast.t
Hello DDH community,
I would like to limit the weather trigger further until we are able to filter queries through the upcoming places detection logic, because we can generate some silly results (see http://www.reddit.com/r/techsnap/comments/2w0c27/odd_duckduckgo_weather_bug/). In combination with the internal trigger, we should still return Forecast results for most relevant queries. Once places detection goes live, we can remove this change and implement all of the relevancy and triggering features here again.
I modified the tests but left most of the code inside the Spice block in anticipation of using it again (would be happy to remove it if it's cleaner).
=> Weather triggering

lib/DDG/Spice/Time.pm, share/spice/time/time.js, t/Time.t
Fixes #1657 
This limits the time IA to only return if it finds a known capitol from the capitols.yml file.  There is also an internal pr to go with its one. 
Bolth PRs are installed on ddh4 for testing. https://ddh4.duckduckgo.com/?q=seattle+time&ia=time
@moollaza @russellholt
=> limit time to capitals

lib/DDG/Spice/Images.pm, lib/DDG/Spice/Quixey.pm
Switched ```String::Trim``` to ```Text::Trim``` as agreed in #1638.
```
$ ack -l Text::Trim
lib/DDG/Spice/Coursebuffet.pm
lib/DDG/Spice/Currency.pm
lib/DDG/Spice/Forecast.pm
lib/DDG/Spice/GithubStatus.pm
lib/DDG/Spice/GoWatchIt.pm
lib/DDG/Spice/Images.pm
lib/DDG/Spice/Parking.pm
lib/DDG/Spice/Quandl/Fundamentals.pm
lib/DDG/Spice/Quandl/HomeValues.pm
lib/DDG/Spice/Quixey.pm
lib/DDG/Spice/RandPOS.pm
lib/DDG/Spice/Recipes.pm
lib/DDG/Spice/SeatGeek/EventsByArtist.pm
lib/DDG/Spice/TravisStatus.pm
lib/DDG/Spice/Whois.pm
```
=> Switch String::Trim to Text::Trim (#1638)

lib/DDG/Spice/Timer.pm, t/Timer.t
Fixes #1607. Queries like `timer for 15 mins` will show timer.
=> spice/timer - added new trigger 'timer for'

share/spice/newint/newint.js
We were running the whole thing through `strip_html` anyway.
=> spice/newint - removed unnecessary HTML formatting

lib/DDG/Spice/Airlines.pm
Check for a space in between the flight and flight number.  Otherwise queries like "sha512" will trigger airlines.
@moollaza @russellholt
=> require a space between flight and  flight number

share/spice/similar_sites/similar_sites.css, share/spice/similar_sites/similar_sites.js
It should look consistent with the Wikipedia buttons:
Screencast:
https://gfycat.com/AlienatedShamefulButterfly
=> SimilarSites: + and - buttons are now consistent

lib/DDG/Spice/Github.pm, share/spice/github/footer.handlebars, share/spice/github/github.js, share/spice/github/triggers.txt, t/Github.t
This does the following:
- Updates the Github Spice to use the current version of the Github API
- Adds language detection to the query parser, adds detected languages as the language parameter passed to Github
- Does remove the bare github search test, my testing shows it was working correctly showing Github status.
This is in lieu of the previous GithubLanguages Spice I was working on.
=> Updating Github Spice

lib/DDG/Spice/Pokemon/Data.pm, share/spice/pokemon/data/pokemon_data.js, t/Pokemon.t
Original IA PR: #1536 
* The IA is now triggered only by a one-word remainders, such as "pokemon pikachu". If the user searches for "how to train my pokemon", the IA is not triggered
* The IA provides a link to the next evolution of the pokemon, but it wasn't specifically redirecting to the IA tab
=> [Pokedex IA] Amended the IA trigger and the link to next evolution

lib/DDG/Spice/DebVersion.pm, share/spice/deb_version/deb_version.css, share/spice/deb_version/deb_version.js, t/DebVersion.t
Reviving old stale branch `ideas/deb`. Added on top of master, as mentioned in #1667. Should close that other PR.
=> spice/deb_version - added the spice on top of master

share/spice/forecast/forecast.css, share/spice/forecast/forecast.js
Removing the blank square of doom for Windows users finally... :smile: 
cc @jagtalon @chrismorast @bsstoner
=> (Forecast) Alert Styling Update

share/spice/similar_sites/similar_sites.css
Removing the container `div` in #1716 made the CSS selectors too broad which added margins everywhere.
Now:
Before:
Notice the increased space at the bottom.
=> similar_sites.css: Add additional qualifier to avoid extra spacing.

dist.ini
Being overly strict with trailing whitespaces was confusing for devs
according to
https://github.com/duckduckgo/zeroclickinfo-spice/commit/5980b02618d1f96e0d9e43af1b4ad788d392447e#commitcomment-10675310
. Hence, reverting.
This reverts commit 5980b02618d1f96e0d9e43af1b4ad788d392447e.
=> Revert "Guard against trailing whitespaces in Perl files when building"

share/spice/reddit_sub_search/reddit_sub_search.handlebars, share/spice/reddit_sub_search/reddit_sub_search.js
This PR removes the use of `{{rt}}` and `{{rd}}` template helpers and makes use of the record template instead. CC @moollaza @abeyang @bsstoner 
Old:
New:
=> RedditSubSearch: Move to record template.

lib/DDG/Spice/Geometry.pm, share/spice/geometry/content.handlebars, share/spice/geometry/geometry.css, share/spice/geometry/geometry.js, t/Geometry.t
This is a converted Goodie, the old PR was duckduckgo/zeroclickinfo-goodies#464
**What does your instant answer do?**
This spice shows geometric formulas (e.g. circle area) with a mockup or calculates them if sizes are specified.
**What are some example queries that trigger this instant answer?**
- formula circle perimeter
- calc circle area with radius = 3
- geometry cube volume length 50.6
- calc equilateral triangle perimeter
- formula ball volume
- geometry rectangle area a = 5,2, b = 10
- geometry cuboid volume a: 5; b: 3; c: 4
**Is this instant answer connected to a DuckDuckHack [instant answer idea](https://duck.co/ideas)?**
Yes, https://duck.co/ideas/idea/1053/geometry-calculator.
**Which existing instant answers will this one supercede/overlap with?**
Not known yet
**Are you …
=> New geometry formula shower / calculator Spice

dist.ini
Required update, you can no longer specify `index`
/cc @zachthompson
=> Update PromptIfStale to use index_base_url

lib/DDG/Spice/Quandl/Fundamentals.pm, lib/DDG/Spice/Quandl/HomeValues.pm, lib/DDG/Spice/Quandl/WorldBank.pm
Hi @moollaza, Quandl has deprecated the http access for API calls and will be shutting it down completely on May 15.  I've made the necessary changes to the code here (which amounted to adding an 's' to three files.)
=> Quandl: http to https

share/spice/dogo_books/dogo_books.js, share/spice/dogo_movies/dogo_movies.js, share/spice/dogo_news/dogo_news.js
Need to switch these over to the new 'movies' template group, now that it's released.
Also removed `ref=` param from `sourceUrl` links -- that's not allowed ;)
/cc @jagtalon
=> Dogo: Switch Movies & Books to movies template group

lib/DDG/Spice/IndeedJobs.pm, share/spice/indeed_jobs/indeed_jobs.js, t/IndeedJobs.t
We're switching to deep triggers because it's difficult to extract the location from a query. We can understand location for some queries such as "javascript jobs in philadelphia" because of the "in" preposition, but we can do nothing for queries such as "javascript nyc jobs" because we don't have the functionality to get the location part of the query. For the mean time, we switch to a Deep trigger so that we can pass the right location to the Indeed API endpoint.
**What is a Deep trigger?**
A Deep trigger is triggering based on the SERP results instead of on the query. This means we can look in the search results, see indeed.com domains (such as indeed.com/q-Javascript-l-San-Francisco,-CA-jobs.html), extract the things that we want using regexp (in this case, "Javascript" and "San …
=> IndeedJobs.pm: Switch to deep trigger.

share/spice/amazon/amazon.js, share/spice/astrobin/subject/astrobin_subject.js, share/spice/envato/envato.js, share/spice/gifs/gifs.js, share/spice/images/images.js, share/spice/isbn/isbn.js, share/spice/sound_cloud/sound_cloud.js, share/spice/videos/videos.js
I'd like to move towards deprecating the need to specify a `model` from Spice.add(). This removes it for Audio/Product/Image and replaces it with `relevancy.dup` attribute, which is essentially the only thing those models are actually doing right now anyway.
The only models remaining are Places and Videos. I'd like to replace them with some kind of shared normalize() function or something since that's essentially all those models are doing. They take in data and transform it into standard objects for the templates. I think this logic needs to be open source so developers understand what's happening to the data between when it's passed into Spice.add() and when it shows up in the templates.
This PR also specifies the templates for Images/Videos spices instead of us magically adding them …
=> Start to deprecate models in Spice.add()

share/spice/quixey/quixey.js
Fixing #1793 - Remove Google TV editions of Android apps based on regexp for ` /Google\s?TV/i` on `package_name` or `name`
=> Quixey: Additional Relevancy Checking - #1793

share/spice/currency/currency.js
`conversions` is an object not an array. 
Don't worry about < IE 9 support, duckduckgo has a polyfill for the `Object.keys` method :smile:  
// @jagtalon
=> Currency: Fix #1844 - Check api_result.conversion as object

lib/DDG/Spice/MovieImage.pm, share/spice/in_theaters/in_theaters.js, share/spice/movie/movie.js
Currently using TMDb just to get the images working in the mean time. It makes a call to the MovieImage.pm endpoint for every item in the list. Fixes #1647.
=> Movies + InTheaters: Use an alternate image source.

share/spice/time/time.js
While debugging issues with queries such as "time london" and "time in mauritania", I noticed that we don't always call Spice.failed() after making an API call and failing relevancy. I don't think that this is what is causing the problem with those queries, but just wanted to fix it for good measure...
=> Call Spice.failed if response fails relevancy

share/spice/twitch/featured/twitch_featured.js, share/spice/twitch/streams/twitch_streams.js
Changing group template to use videos for Twitch Spice IA as per @moollaza's request in #1871.
=> Adding group: videos as per request

share/spice/stocks/content.handlebars, share/spice/stocks/stocks.js
Check if markets are closed, if so, add notice to display. Fixes #1854
New design: 
After 4PM
Following morning, before next opening:
/cc @abeyang @jagtalon
=> Add check for closed market, add to frontend

share/spice/wikinews/wikinews.js
Updated text size to 17em, changed title length to 4 lines, and updated the source name to "Wikinews"
/cc @iambibhas @abeyang
=> Set title to 4line, change fontsize to 17px

share/spice/editor/editor.js
Wrap everything in a closure (as we do for all Spice IA's) and ensure we call `Spice.failed()` for mobile devices because it shouldn't show.
/cc @nilnilnil @jagtalon
=> Update to newest Spice API, ensure Spice.failed() call

share/spice/bbc/bbc.js
Saw this IA could use some moment.js love, so using that. Sadly can't remove the `duration()` function as moment.js' `humanize()` function doesn't return accurate duration.
=> bbc - using moment.js, removed unnecessary helpers

share/spice/time/time.css
Mobile view (for viewports smaller than 406px):
Anything larger than an iPhone 6 (portrait) will revert to the original / side-by-side view:
=> Time - Fix mobile layout (Fixes #1853)

share/spice/playing_cards/playing_cards.css, share/spice/playing_cards/playing_cards.js
- Switched to Movie template (automates hiding the tile body)
- Set width on tile (prevents calculating tile width at 0px when image hasn't loaded)
/cc @kbhat95
=> simplify CSS, set tile-width to prevent 0 width tile display

share/spice/forecast/forecast.js
I've been trying to namespace all the item-specific meta options with `items` at the beginning. This depends on an internal change.
@sdougbrown
=> Update Forecast variableTileWidth => itemsWidthVaries

share/spice/airlines/airlines.js
Fixes the missing result on "[SY 394](https://duckduckgo.com/?q=SY+394)". Also for "[Sun Country Flight 394](https://duckduckgo.com/?q=Sun+country+flight+394)"
- https://moollaza.duckduckgo.com/?q=SY+394&ia=airlines
- https://moollaza.duckduckgo.com/?q=Sun+country+flight+394&ia=airlines
/cc @tommytommytommy
=> ensure codeshares property exists before iterating

share/spice/time/content.handlebars, share/spice/time/time.css, share/spice/time/time.js
In response to a tweet, we realized the floated text was causing problems.
This simplifies and cleans up the CSS. Opting for `inline-block` elements over floats.
/cc @chrismorast
=> Remove horizontal separator b/w time and date

share/spice/go_watch_it/go_watch_it.js
The Fandango description line was being replaced by a cut-off one
this should fix #1544
=> Fix Fandango description line in GoWatchIt IA

share/spice/sports/mlb/games/sports_mlb_games.js
- Updating 'SportsData' to 'Sportsradar'
- Dynamic `moreAt` depending on the query.
Requires an internal PR to actually have the new moreAt url field, but safe to merge otherwise as there's a fallback. :smile: 
cc @b1ake @bsstoner @nilnilnil
=> MLB Scores Attribution Adjustments

lib/DDG/Spice/SeatGeek/EventsByArtist.pm, t/SeatGeek.t
As reported in #1585, "tickets" was not a trigger for concerts
=> use "tickets" as trigger for EventsByArtist IA

lib/DDG/Spice/SeatGeek/EventsByArtist.pm
@moollaza seems like #1975 was merged, but was missing a comma
=> add missing comma

lib/DDG/Spice/Quandl/Fundamentals.pm, lib/DDG/Spice/Quandl/HomeValues.pm, lib/DDG/Spice/Quandl/WorldBank.pm
Nginx can't handle redirects, so we modify the Spice endpoint.
=> Quandl: quandl.com redirects to www.quandl.com

lib/DDG/Spice/Snow.pm, share/spice/similar_sites/similar_sites.css, share/spice/snow/snow.css, share/spice/snow/snow.js
This is how it looks like now, 
This should fix #1562
=> Improves snowflake effect

share/spice/sports/mlb/games/mlb_score.handlebars
Some whitespace crept into the compiled template, which makes the end result look a little skewed. :smile: 
to @bsstoner 
cc @thm
=> MLB Boxscore - Whitespace Fix

share/spice/recipes/recipes_item_detail.handlebars, share/spice/rx_info/rx_info.handlebars, share/spice/rx_info/rx_info.js, share/spice/rx_info/rx_info_description.handlebars
Item detail templates are now going to require an extra wrapping div.  This makes handling the templates internally a lot easier.  This shouldn't be a problem going forward since it's generally easier to use the `base_item_detail` template rather than crafting a custom one. :smile: 
to @bsstoner
=> Custom Item Detail Wrappers

share/spice/transit/njt/transit_njt.js, share/spice/transit/path/transit_path.js, share/spice/transit/septa/transit_septa.js, share/spice/transit/switzerland/transit_switzerland.js
Removed some old meta text attributes from Transit. Fixes #1794
=> Removed old meta text attribute

share/spice/people_in_space/people_in_space.css
Adjust img and container sizing CSS for IE8 Support.
Images need a background color otherwise they look a little odd because we don't have border-radius available to use:
Merging as a hotfix because right now its completely broken in IE8.
Result: https://www.browserstack.com/screenshots/6e3cb4c05b6462a582a395819cc4590c8b6c5ca1
/cc @abeyang @MrChrisW
=> People in Space: Update for IE8

share/spice/people_in_space/people_in_space.css
We've decided that it's best to just hide the flag in IE8. 
This accomplishes that with some CSS:
/cc @abeyang @MrChrisW
=> Hide flag icon in IE8

share/spice/go_watch_it/go_watch_it.js
Refactored relevancy checking approach to be more lenient.
- First looks for a "strict" relevant result and uses that if present.
- If not, looks to a fallback list of non-strict, relevant results
- If none, bails out
Fixes many queries that currently do not trigger:
- https://duckduckgo.com/?q=stream+vacation
- https://duckduckgo.com/?q=stream+return+of+the+jedi
- https://duckduckgo.com/?q=watch+blade+runner (no result, not available for streaming)
- https://duckduckgo.com/?q=watch+the+walking+dead
- https://duckduckgo.com/?q=stream+saturday+night+live
- https://duckduckgo.com/?q=watch+the+office
to @jdorweiler 
/cc @jagtalon
=> GoWatchIt: Refactor relevancy handling, cleanup code

template/lib/DDG/Spice/Example.pm
I noticed that the url to the spice docs was out of date. It should reflect the current page anchor now.
=> Commented url in 'example.pm'  referencing spice caching documentation updated.

share/spice/seat_geek/events_by_artist/seat_geek_events_by_artist.css
Resolves #1848.  
Not perfect alignment but it works for now.  I suppose the css for `dateBadge` needs to be fixed internally?  It doesn't align to the bottom of the tile footer.
=> Seat Geek: Resolve price align bug on mobile

share/spice/rhymes/rhymes.js
API was down this morning and was causing console errors as `api_result.lenth` can't be called when `api_result` doesn't exist
/cc @jagtalon  @bsstoner
=> Rhymes: verify api_result exists before checking length

share/spice/congress/congress.css, share/spice/congress/congress.js
This currently looks like this, What do you think we should do about the names?
This will fix #836
=> Changed congress template to media

lib/DDG/Spice/BrainyQuote.pm, t/BrainyQuote.t
Seems rather inelegant, but it fixes #1952. Is there a better way to do this?
Also, I saw that this Spice was missing a tests file, so I added that in as well.
=> BrainyQuote: Prevent triggering on 'stock quote'

lib/DDG/Spice/SublimePackages.pm, t/SublimePackages.t
Fixing  #1944
Currently only removing the word `for` 
Filtering by Operating System (windows, mac os x, linux)
Filtering by Sublime version 2/3
//cc @moollaza
=> SublimePackages: Remove common words, add filtering options

share/spice/stocks/content.handlebars, share/spice/stocks/stocks.js
Fixing: #1946 
@moollaza Can you clarify if the moreText hyperlink key is `url` or `href` ? also this doesn't seem to work yet. 
Currently the spices uses `Data by Xignite`, are we able to add "Data by" or is it not needed?
````perl
meta: {
sourceName: 'NASDAQ',
sourceUrl: url,
options: {
moreText: {
href: 'https://xignite.com',
text: 'Xignite'
}
}
}
```
=> Stocks: Use template.options.moreText property for attribution 

lib/DDG/Spice/Npm.pm, share/spice/npm/npm.js
Fixes #1881.
- Checking if there is any dependency before showing it in infobox.
- I sometimes end up searching for `npm install foo`, thought it might be helpful to support it as trigger.
- Added project homepage and repo url as `url` in infobox
=> npm - checking dependency length before showing, added trigger "npm install"

lib/DDG/Spice/Airlines.pm, share/spice/airlines/airlines.js, share/spice/flights/route/flights_route.js
Re: #2000
Stop-gap fix to address the missing flights by making an additional request for either the prior day or the next day depending on the UTC time. I also added some heuristic changes to suppress flights that arrived more than three hours in the past, as well as flights that have scheduled departures more than 24 hours into the future. I would like to merge a fix for this issue first, and then do a second round where we clean up flights by route.
=> Widen flights window

share/spice/currency/currency.css, share/spice/people_in_space/people_in_space.css
@moollaza @jagtalon 
Is causing issues with attribution and doesn't seem necessary:
cc @sdougbrown @malbin
=> Remove z-indexes from currency + people in space

share/spice/twitch/featured/twitch_featured.js, share/spice/twitch/streams/twitch_streams.js
There doesn't seem to be any reason to show 3 items in a grid so it's probably best to remove this. Removing this will use the default instead which is 12 items.
=> Twitch: Remove minItemsForModeSwitch

.travis.yml
Supresses the output also means that failed tests don't show the reason for failure in Travis making it impossible to figure out the cause of the problem when looking at the failed Travis tests.
We've already done this to Goodies.
to @zachthompson
=> Write to STDOUT

share/spice/lastfm/artist/lastfm_artist.js
Guard against empty/bad api responses from last.fm
@moollaza @russellholt
=> Add guard for empty lastfm response

share/spice/parking/parking.js
@AlexCutlipParkingPanda We're noticing that the page is taking too long to load on mobile so I'm fixing like this for now.
As a better solution, can your API return fewer results initially? OR can it take a request parameter that specifies the number of results? Right now it's sending ~140 which is too many. 
/cc @bsstoner @andrey-p 
Live here: https://moollaza.duckduckgo.com/?q=parking+manhattan&ia=parking
=> Parking: Reduce results array to 30 elements to increase page load speed

share/spice/quandl/home_values/metro.yml, share/spice/quandl/home_values/states.yml, t/Quandl.t
The problem was that the abbreviation for "Indiana" is "IN", so "home values in California" was triggering on the "in".
=> quandl home values: fixed indiana bug

share/spice/aqi/aqi.js
When testing I noticed that we cause an error when the array is empty (no result). This tests for that and properly calls `Spice.failed`
https://duck.co/ia/view/aqi
=> AQI: properly fail on an empty array

share/spice/dictionary/definition/dictionary_definition.css, share/spice/dictionary/definition/dictionary_definition.js
**Hotfix**
- Update broken css
- Correct another reference to `id`
- update `Spice.failed()` to use proper `id`
Tested locally:
/cc @jdorweiler @bsstoner
=> Dictionary: fix ID bugs

share/spice/sports/mlb/games/head_in_progress.handlebars, share/spice/sports/mlb/games/sports_mlb_games.js, share/spice/sports/sports.js
This corrects a mistaken assumption that I made when I tried to adjust how `fillBoxScore` gets the 'current' scoring sequence.
to @bsstoner
=> (Sports) Fix 'Current' Assignment for MLB

share/spice/airlines/content.handlebars, share/spice/flights/route/content.handlebars
The flights and routes instant answers do not correctly show the status for delayed flights. After a little investigation, this appears to be related to the handlebars template, which is not passing in the needed scheduled arrival or scheduled departure information. This pull request includes updates to both files to pass the appropriate variables.
I was able to test this for the routes IA only (I think the airline one may only have deep triggers), but it appears to produce the desired effect:
I only tested in one browser, because this did not change the HTML output or the JavaScript. Let me know if there are further tests or prep work I should complete.
Thanks!
=> Fix flight status

share/spice/bbc/buy.handlebars, share/spice/bbc/subtitle_content.handlebars, share/spice/canistreamit/canistreamit.handlebars, share/spice/dogo_books/dogo_books.css, share/spice/dogo_movies/dogo_movies.css, share/spice/dogo_movies/subtitle_content.handlebars, share/spice/in_theaters/in_theaters.css, share/spice/in_theaters/subtitle_content.handlebars, share/spice/lastfm/artist/item.handlebars, share/spice/lastfm/artist/lastfm_artist.js, share/spice/movie/movie.css, share/spice/movie/subtitle_content.handlebars, share/spice/parking/item_back.handlebars, share/spice/quixey/buy.handlebars, share/spice/recipes/recipes_item_detail.handlebars, share/spice/rx_info/rx_info.css, share/spice/rx_info/rx_info.handlebars, share/spice/rx_info/rx_info_description.handlebars, share/spice/stocks/content.handlebars, share/spice/stocks/stocks.css
We're going to be refactoring how detail panes work, in order to make it easier for open-source developers to create and modify these areas.  The first step is to break up the detail 'wrapping' elements from the 'content' elements.  This just tags a bunch of those content elements with the `.c-` prefix, wherever they appear in the Spice repo.
to @bsstoner
=> Detail ClassName Updates

share/spice/news/news.js
The correct condition for calling Spice.fail() for news should be if we have less than 3 good stories. The condition was correct in https://github.com/duckduckgo/zeroclickinfo-spice/blob/d010d02cf7dbd095561ee5d36f1505d3cc10f1c4/share/spice/news/news.js#L80, and then the inequality was flipped in https://github.com/duckduckgo/zeroclickinfo-spice/blob/0cfee129b2e052c264d234b57f183524f6b4acb5/share/spice/news/news.js#L80.
This PR flips the inequality condition and only allows us to call either Spice.failed() or Spice.add(), but not both. (I think that the current code always calls Spice.add() even if we call Spice.fail()?)
=> Fix number of stories condition for adding news

share/spice/geometry/geometry.js
@moollaza I was doing some cleaning up of the DDG utils and noticed one of them exposed `DDG.isNumber` in the global scope. I'll be removing `isNumber` from the global scope to keep things tidy.
The geometry spice is the only place where the global `isNumber` is used instead of `DDG.isNumber`.
=> removed use of global isNumber helper

lib/DDG/Spice/BikeSharing/CitiBikeNYC.pm, share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.css, share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.js, share/spice/bike_sharing/citi_bike_nyc/content.handlebars, t/BikeSharingCitiBikeNYC.t
Show stations of the Citi Bike Bike Sharing Program (in NY), along with information about bike and docks availability.
This is a way to bring into DDG the functionality of the [official map](https://member.citibikenyc.com/map/), and it's useful for both tourists (to discover stations) and NYC citizens (to know current status)
**Data Source**
The data source is the [official Citi Bike API](https://www.citibikenyc.com/stations/json), and its policy can be found [here](http://www.citibikenyc.com/data-sharing-policy)
```
citibike ny
citi bike nyc
citi bike ny stations
bike sharing brooklyn
```
**What does the Instant Answer look like?**
```
[X] Added metadata and attribution information …
```
=> First implementation of Citi Bike NYC Bike Sharing IA

share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.css, share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.js, share/spice/bike_sharing/citi_bike_nyc/content.handlebars, share/spice/gifs/gifs.js
Final CSS and `name` adjustments.
Live here: https://beta.duckduckgo.com/?q=bike+sharing+nyc&ia=bikesharing
/cc @abeyang @marianosimone @xuv
-----
IA Page: https://duck.co/ia/view/citi_bike_nyc
=> Minor CSS adjustments, change tab name to 'Bike Sharing'

share/spice/yoga_asanas/yoga_asanas.css
I added 
```css
-webkit-transform: translate(-50%, 0);
-ms-transform: translate(-50%, 0);
```
So that this IA will work on IE 9 and Safari
=> Add vendor prefixes to the transform CSS property

share/spice/timer/timer.css, share/spice/timer/timer_wrapper.handlebars
Small adjustment to timer_wrapper markup and CSS so that the "add timer" button works correctly in the dark theme.
**Current:**
**Result:**
/cc @abeyang @andrey-p
=> Fix timer CSS/Handlebars for dark theme

share/spice/amazon/amazon.js
Showing the 'Prime' badge on appropriate items.  Requires an internal PR.
=> Amazon Prime Badge - Spice Update

share/spice/twitter/twitter.js
The title link now points to the result's Twitter page, as described in the issue.
=> Twitter: Fixes #2158

lib/DDG/Spice/Lastfm/Artist.pm, share/spice/lastfm/artist/lastfm_artist.js, t/LastfmArtist.t
Fixes #2050.
- Added relevancy block to ensure that artist description is available
- Added stop words `/watch bands?/`
- Added tests, there were none.
**Bug Found:** While the spice has code for showing similar artists, it doesn't implement the method to show them. `ddg_spice_lastfm_artist_similar` callback method is called for any `similar artist` queries, but it's not implemented. Hence the query fails with a JS error. 
Uncaught ReferenceError: ddg_spice_lastfm_artist_similar is not defined
/cc @jagtalon: Am I missing something?
=> Lastfm - added relevancy block, stop words and tests

lib/DDG/Spice/Coderwall.pm, share/spice/coderwall/coderwall.js, t/Coderwall.t
Adds an IA that displays coderwall user profiles
See #1360
------
Display information about a coderwall.com user
It helps to ensure a specific user is found (by displaying location) and provides a direct link to the user's profile
[Coderwall API](https://coderwall.com/api)
It is the only one that i know of.
No
`coderwall jagtalon`, `motersen coderwall`
**Which communities will this Instant Answer be especially useful …
=> Add new Instant Answer: Coderwall

share/spice/cryptocurrency/cryptocurrency.js
I can't reproduce this anymore, but a few weeks ago we were seeing cases that this error was being thrown:
```
TypeError: rows[0] is undefined
```
I'm assuming it was a case where `rows` was just an empty array. But in these cases where it threw the error it was not calling Spice.failed(), which would cause a bad fallback to images. I don't think there's any harm in adding these additional checks, but please let me know if you think we can't do this.
=> Cryptocurrency error handling

share/spice/bike_sharing/indego_phl/bike_sharing_indego_phl.css, share/spice/bike_sharing/indego_phl/bike_sharing_indego_phl.js, share/spice/bike_sharing/indego_phl/footer.handlebars
- Move to built-in `text` template
- Shrink tile sizeto 11.5 x 11.5em (144x144px)
to @abeyang 
/cc @AcriCAA @marianosimone @jagtalon 
@marianosimone can you please make the same changes to the BayAreaBikeSharing PR -- seeing as it also doesn't have the need for extra footer space as it doesn't have update times
-----
Result:
=> IndegoPHL: Move to text template + footer, shrink tile size

lib/DDG/Spice/BikeSharing/CitiBikeNYC.pm, t/BikeSharing/CitiBikeNYC.t
Thanks to @AcriCAA's suggestion, 'bikeshare' (and not only 'bike share') now trigger the CitiBike NYC IA
=> make bikeshare trigger CitiBike NYC IA

share/spice/coderwall/coderwall.js
@abeyang I removed the image, but the icon template is obviously meant to use an icon so there was padding on the title/subtitles.
I assume we should be using the text template instead? Here's the result:
Here's the icon template, without the image: 
**Update**: Just realized the `text_detail` template doesn't support an `altSubtitle` I guess we'll have to use the `Icon` template and some CSS. Alternatively, we could add an altSubtitle to the text template?
=> Coderwall: remove image and switch to text template

share/spice/quixey/quixey.js
This fixes the current problem we're experiencing with broken Android icon links from the Quixey API.
This is the simplest and easiest solution to this problem. Quixey is having difficulty resolving it on their end so this essentially ignores the problem. We already use this solution for Apple icons so this is a pretty straightforward solution. 
Merging as hotfix. Tested and working fine. Live here: https://moollaza.duckduckgo.com/?q=flight+tracking+apps&ia=apps&iai=FlightAware+Flight+Tracker
/cc @jagtalon @bsstoner
=> Hardcode Android icon to use DDG Favicon, like we do for Apple

lib/DDG/Spice/Aur.pm
Fixes #2241.
Added `spice wrap_jsonp_callback => 1;`, while removing the callback parameter in the API endpoint.
=> Aur: Remove callback parameter

lib/DDG/Spice/Drinks.pm, share/spice/drinks/drinks.js, share/spice/drinks/drinks.txt, t/Drinks.t
Shows cocktail recipes.
Makes easier to access cocktail recipes
[TheCocktailDB](http://www.thecocktaildb.com)
It was mentioned in the issue #2184, thus stable enough.
Nope, as far as I know
how to make a white russian drink, mojito, ingredients of margarita, red eye cocktail
People who love to drink
**Is this Instant …
=> Reborn IA: Drinks

lib/DDG/Spice/Currency.pm, t/Currency.t
Fixes issue #2235.
Change trigger to handle space between leading/trailing currency symbol and number.
=> Fixes issue #2235

share/spice/news/news.js
Waiting for new translation tokens to be released before releasing this change. There's also a corresponding internal change.
=> Change "News Articles" to "Recent News"

share/spice/github/github.js, t/Github.t
=> GitHub - Escape query parameter

lib/DDG/Spice/Expatistan.pm
Fixes #2250 
HTTP API now redirects to HTTPS, which is breaking the IA in production. This fixes that.
Working here: https://moollaza.duckduckgo.com/?q=cost+of+living+in+philadelphia&ia=answer
=> Expatisan: Switch to HTTPS, because HTTP redirects

lib/DDG/Spice/Pwned.pm, share/spice/pwned/footer.handlebars, share/spice/pwned/pwned.js
Continuing #2267...
Made some adjustments to this IA. The result looks like this:
I tried using the Clearbit [company logo API](http://blog.clearbit.com/logo) to produce icons for each company and it works pretty well, but in the cases where they have no logo, we end up show ugly `alt` text:
---
I think we need some padding between the footer and snippet, but that should be handled at the template level, because it will affect all IAs -- /cc @abeyang 
/cc @b2ddg
=> Pwned Spice: Update design with larger snippet, footer and subtitle

.travis.yml
Travis breaks when trying to connect to HTTPS links on S3.  This disables the host verification checks for tests.
=> Skip host veriication with LWP SSL

share/spice/quixey/quixey.js
- Quixey API is serving us icons that consistently cause a 502 error. I resolved this by displaying on our own favicons
- Our favicon urls have changed, so this updates Apple and Android accordingly. I've also added support for Microsoft icons because those were producing 502 errors as well.
Result:
//cc @jagtalon
=> Quixey: update apple and android icons. Add hardcoded windows icon also

lib/DDG/Spice/Lastfm/Artist.pm, t/LastfmArtist.t
Fix issue #2099 -  Last.fm Artist: reign in triggering
As suggested by @moollaza I dropped the word artist ...
Maybe Another way could be to filter the more frequent queries with word artist.
example code :
```
handle query_lc => sub {
my $synonyms = "bands?|musicians?|players?|artists?|performers?|singers?|rappers?|djs?|vocalists?|songsters?";
...
#Ignore Queries like "(music or street) artist"
if(m{(music|street)\ artists?}) {
return;
}
```
=> Issue #2099 - Last.fm Artist: reign in triggering

share/spice/cryptocurrency/cryptocurrency.css, share/spice/cryptocurrency/item.handlebars
I just got the latest duckduckhack newsletter and decided to fix one of the low-hanging fruits. :smile: 
The cryptocurrency symbols are now using the `disc` class when searching for "[50 LTC][0]" for example. I was triggering a conversion by searching for "[50 LTC in EUR][1]" first, but that's not using any of the CSS classes I was looking at. But I hope I got all the right places.
[0]: https://duckduckgo.com/?q=10+ltc&ia=cryptocurrency
[1]: https://duckduckgo.com/?q=50+ltc+in+eur&ia=cryptocurrency
-----
IA Page: https://duck.co/ia/view/cryptocurrency
=> Fix #2205 - apply 'disc' class to cryptocurrency IA

share/spice/news/news.js
This PR makes news work more like images and other services by accepting a hash (instead of just an array of stories). Requires simultaneous release with an internal PR.
=> Modify news callback to accept a hash

lib/DDG/Spice/Anime.pm
To avoid triggering this IA when searching for `currently airing anime`.
=> spice_anime - ignoring "currently airing"

share/spice/sound_cloud/sound_cloud.js
They must have changed their API recently and deprecated one of my favorite field names of all time, `favoritings_count`
@moollaza @jagtalon @chrismorast
=> Update field to use for hearts for sound_cloud

share/spice/github/github.js
Fixing #2318 
@moollaza I'm attempting to use a relevancy block to match any number that is not 0 for the [size](https://gist.github.com/MrChrisW/23dabf7d791d98cd2d61#file-gistfile1-txt-L98) value returned from the API, this should fix #2318. 
However this doesn't seem to work as expected and I'm receiving a console error `TypeError: h.match is not a function` referring to the function used to check relevancy. 
I can just check the size in the `normalize` block and return nothing if 0, however I felt this was the more "correct" way to do it. Let me know if I'm missing something... :frowning:
=> Github: Check repository size in relevancy block

share/spice/riffsy/riffsy.css
A keyframe with the same name has conflicted with Riffsy's keyframe. A better solution for this is to have gif detection integrated into the global image template (thinking of working on this soon!), but for now, we don't want it broken so here's a patch that renames the keyframe so that it doesn't conflict.
https://v.usetapes.com/g3M3Cu1VWN
-----
IA Page: https://duck.co/ia/view/riffsy
=> Fix #2316: Problem with loading animation

share/spice/go_watch_it/go_watch_it.js
GoWatchIt's code has gotten a bit unwieldy and is due for another look, but the following fix works. So we have some code that strips some text from the `buy_line` or the `rent_line` without even checking if it should be stripped or not. This patch makes sure that such a thing doesn't happen again.
Screenshots:
---
https://duck.co/ia/view/go_watch_it
=> Fix #2323: Problems with Fandango

share/spice/people_in_space/people_in_space.js
Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2345
The API incorrectly returns "England" as the country for Tim Peak ( :gb: ! ), whereas it should be United Kingdom or UK; therefore no flag was rendered. 
I've added England as an alias for the UK flag to work around this issue.
-----
IA Page: https://duck.co/ia/view/people_in_space
=> PeopleInSpace: Fixing #2345

lib/DDG/Spice/Time.pm, share/spice/time/time.js, t/Time.t
@MrChrisW @moollaza @bsstoner 
@bsstoner I could probably use some JS cleanup :)
-----
IA Page: https://duck.co/ia/view/time
=> Time: Improve Generic Time handling

share/spice/envato/envato.js, share/spice/forecast/forecast.js, share/spice/sound_cloud/sound_cloud.js
There's no need for `item_custom` anymore, they're treated the same as regular `item` template overrides.
@andrey-p 
cc @moollaza
=> Deprecate item_custom

share/spice/google_plus/google_plus.css
This is a fix for issue #2344 
Changed the CSS for the Google+ results to fix issues where the spice tiles would vary in height depending on length of text.
I don't have a full development setup yet, so I couldn't test it on all browsers, but I did run this through duckpan and took some screenshots in Firefox. It looks the same in Chrome also (but chrome has text ellipsis which is better).
***Old Images (before update)***
[Desktop Preview in Firefox](https://cloud.githubusercontent.com/assets/14809478/12006591/8781d138-abaa-11e5-9016-79111668af7d.png)
[Mobile (small window) Preview in Firefox](https://cloud.githubusercontent.com/assets/14809478/12006593/878410ba-abaa-11e5-8c89-124c0d14ac8e.png)
***Updated Images***
[Desktop Preview in …
=> Google+ Style Updates - Fix for #2344

share/spice/coupons/coupons.css, share/spice/coupons/coupons.js
- Minor changes to CSS
- Use `em` for padding, reduce padding below brand image
- set image height to prevent tile content from shifting
- use bolder font for tile title
- strip brand name from coupon description via regex (@ingowachsmuth-sparheld -- would this be possible on your end?)
/cc @ingowachsmuth-sparheld @abeyang 
Result:
-----
IA Page: https://duck.co/ia/view/coupons
=> Final Adjustments for Coupon Spice

lib/DDG/Spice/Timer.pm, t/Timer.t
Hello,
This update fixes some triggering issues with the Timer. This includes fixing triggering such as "five-timer", along with removing the "time" trigger.
This update also adds a few extra triggers. Before the "online" and "for" keyword was only applied to the "timer" trigger, now it's applied to all the `startend` triggers. This allows for queries such as "online alarm" and "countdown for 10 minutes".
I can rollback the triggering even more if you want.
Fixes issue #1937 
Instant Answer: https://duck.co/ia/view/timer
=> Timer - Updated Triggering and Parsing - Fixes #1937

lib/DDG/Spice/Zanran.pm
Quick fix for #102 - remove the `"` quote char from the search query allowing queries like `arabia "oil production"` to work this avoids any internal changes.
See [comment](https://github.com/duckduckgo/zeroclickinfo-spice/issues/102#issue-7845400) for more detail.
=> Zanran: Remove quotes from search query

share/spice/flash_version/flash_version.js
Partially fixing #99
>DDG can tell you your flash version but it doesn't give you the last 3 numbers:  by @zekiel 
Unable to implement this functionality. 
+ Unable to show the last three numbers without using [SWFObject](https://code.google.com/p/swfobject/) to embed a swf file - which is not recommended.
+ All js implementation of flash detection including Adobe official kit only display 3 version numbers. See http://isflashinstalled.com/
**This PR relates to [comments made](https://github.com/duckduckgo/zeroclickinfo-spice/issues/99#issuecomment-49634404) by @bsstoner regarding the removal of FlashDetect from core.**
We should include [flash_detect_min.js](http://www.featureblend.com/flash_detect_1-0-4/flash_detect_min.js) and call it using `DDG.require` the same way we do `moment.js` …
=> FlashVersion: Use DDG.require for 'flash_detect.js' file

share/spice/timer/timer.js
Good evening.
This branch fixes issue #2380 
We check to see if the variable `startingTime` is a value larger than 0. When no time is provided in the query, the `startingTime` variable is 0. This can also happen if someone submits "timer 0 minutes". In this case, I still think it's a good idea to have the timer not start but instead show a create timer box.
Due to my editor, some extra white space was also removed with this commit.
---
https://duck.co/ia/view/timer
=> Timer - Fixes issue #2380

share/spice/cryptocurrency/cryptocurrency.js, share/spice/cryptocurrency/cryptocurrencylist.txt
Hi,
The flag for ShadowCash is already present in the files on DuckDuckGo
https://duckduckgo.com/share/spice/cryptocurrency/1178/assets/svg/SDC.svg
But not enabled in the cryptocurrency.js file.
I've set it to "true" and added it to the list of cryptocurrencies.
https://duck.co/ia/view/cryptocurrency
=> Enable image/flag of ShadowCash [cryptocurrency]

share/spice/indeed_jobs/indeed_jobs.js
Fixes issue #2393 
I also updated the design slightly to (what I believe) displays the information better. Before some job titles only occupied one line and caused additional white-space between the job description and the job title. 
Switched the tile width to be wide, and set the tileTitle to be 1 line.
---
IA Page: http://duck.co/ia/view/indeed_jobs
=> IndeedJobs Design Updates - Fixes #2393

lib/DDG/Spice/Currency.pm, t/Currency.t
Fixes #2398 
Adds support for queries like GBP/ZAR - See [test file](https://github.com/MrChrisW/zeroclickinfo-spice/blob/7d3276f20941145523b0b2b47f156419d854d564/t/Currency.t) for other examples
CC// @Ntrails
------
IA Page:  http://duck.co/ia/view/currency
=> Currency: Add support for / slash format in triggers

share/spice/octopart/octopart.js
Fixes #2207
This allows queries like the following by checking the query against the item title
+ [atmega datasheet](https://beta.duckduckgo.com/?q=atmega+datasheet&ia=parts)
+ [ne555 specs](https://beta.duckduckgo.com/?q=ne555+specs&ia=parts)
Queries - will not trigger
+ people round specs 
+ apple watch specs
-----
IA Page: https://duck.co/ia/view/octopart
=> Octopart: Include relevancy checking against item title

lib/DDG/Spice/InTheaters.pm, t/InTheaters.t
Fixes #2321 
Support for "cinemas" trigger word -  [see test file](https://github.com/duckduckgo/zeroclickinfo-spice/blob/fb14a961c3830fd4143a5fa3c4fcd5569deed7d2/t/InTheaters.t#L51-L64)
"theatres" triggers already exist.
=> InTheaters: Support for cinemas trigger word

share/spice/time/time.js
Fixes #2404
Display raw offset, don't use replace to remove `0`
https://duck.co/ia/view/time
=> Time: Remove .replace for time offset, display raw offset

lib/DDG/Spice/Aqi.pm, t/Aqi.t
Hello,
In this update to Aqi (Air Quality Index), I added a new option to provide the word "local" instead of a zip code. This could be very useful if you are traveling to a different city and don't know the local zip code.
**A few questions...**
I'm not sure if I validate the location property correctly (I'm not a Perl developer). Is it sufficient enough to check if the `$loc` and `$loc->{postal_code}` return `true`, and to assume a valid postal code is present? Is there a more preferred way?
In the test file, I'm not sure if the `DDG::Request->new` method can be used along side the method of testing strings by themselves. In all the test files I've seen, they either use one or the other.
I was considering having this Instant Answer trigger without any additional content for the more …
=> Aqi - Added term 'local' instead of having to use zip codes

share/spice/missing_kids/missing_kids.js
This ensures that when the query is "missing kids" if the IA triggers and shows, it's tab will open.
-----
IA Page: https://duck.co/ia/view/missing_kids
=> MissingKids: Set signal high

share/spice/recipes/recipes.css
This style seems unnecessary and is breaking the mobile detail pane in dark theme:
@moollaza
=> Remove background color override for recipes mobile detail panes

share/spice/statista/footer.handlebars, share/spice/statista/statista.css, share/spice/statista/statista.js
The IA no longer displays premium content, so the "Free" and "Premium" badges are no longer needed.
I've also fixed the indentation.
You can see the changes without whitespace here: https://github.com/duckduckgo/zeroclickinfo-spice/pull/2449/files?w=1
=> Remove premium/free badge, move date to left side

share/spice/expand_url/expand_url.js
* added exclamation mark, which ensures that
if there's not a long-url key, it will fail
Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>
@bsstoner probably removed that exclamation mark here -> https://github.com/duckduckgo/zeroclickinfo-spice/commit/c790c2392994136f0891c842bc1d4a810f8edf0a
=> expand_url: fixed spice failing on every query

lib/DDG/Spice/SeatGeek/EventsByArtist.pm, lib/DDG/Spice/SeatGeek/EventsByCity.pm, lib/DDG/Spice/SeatGeek/EventsByVenue.pm, lib/DDG/Spice/SeatGeek/EventsNearMe.pm, lib/DDG/Spice/SeatGeek/Sports.pm
As pointed out by @moollaza in #1554, the SeatGeek API has changed to always redirect to HTTPS. As a result all current IAs that use it are broken. This PR fixes them.
---
https://duck.co/ia/view/seat_geek
https://duck.co/ia/view/seat_geek_sports
https://duck.co/ia/view/seat_geek_events_near_me
https://duck.co/ia/view/seat_geek_events_by_venue
https://duck.co/ia/view/seat_geek_events_by_city
https://duck.co/ia/view/seat_geek_events_by_artist
=> SeatGeek: Change IA's that use the SeatGeek API to use HTTPS

dist.ini
Use our new dzil plugin to update tag message on git.
=> Use Git::Tag::IAChangelog in dist.ini

share/spice/in_theaters/in_theaters.css
Fixes #2469
A larger image is being served to retina displays, but the CSS needed to have a maximum width property for it to show at the correct size. I've set it to the same size as that of the images served to non-retina displays.
---
IA Page: https://duck.co/ia/view/in_theaters
=> InTheaters: fixed tomato icon size in retina displays

lib/DDG/Spice/SunRiseSet.pm, t/SunRiseSet.t
Fixes #2426
* `$loc` is no longer used when a location is not specified
* Removed location aware tests
---
IA Page: https://duck.co/ia/view/sun_rise_set
=> Location Sunrise/Sunset: Only trigger when a location is specified

share/spice/seat_geek/events_by_city/seat_geek_events_by_city.js
SeatGeek Events (City): Use moment.js
Re: #1554
* `getDate()`
* `getMonth()`
* `getDay()`
* `months[]`
* `days[]`
**Note:** The majority of changes in the diff are a result of adding the `require()` block which pushed everything down one line and indented it. The core changes occur at lines 110-128.
---
IA Page: https://duck.co/ia/view/seat_geek_events_by_city
=> SeatGeek Events (City): Use moment.js

share/spice/seat_geek/events_by_venue/seat_geek_events_by_venue.js
SeatGeek Events (Venue): Use moment.js
Re: #1554
* `getDate()`
* `getMonth()`
* `getDay()`
* `months[]`
* `days[]`
**Note:** The majority of changes in the diff are a result of adding the `require()` block which pushed everything down one line and indented it. The core changes occur at lines 110-128.
---
IA Page: https://duck.co/ia/view/seat_geek_events_by_venue
=> SeatGeek Events (Venue): Use moment.js

share/spice/seat_geek/events_near_me/seat_geek_events_near_me.js
SeatGeek Nearby Concerts: Use moment.js
Re: #1554
* `getDate()`
* `getMonth()`
* `getDay()`
* `months[]`
* `days[]`
**Note:** The majority of changes in the diff are a result of adding the `require()` block which pushed everything down one line and indented it. The core changes occur at lines 107-125.
---
IA Page: https://duck.co/ia/view/seat_geek_events_near_me
=> SeatGeek Nearby Concerts: Use moment.js

share/spice/seat_geek/sports/seat_geek_sports.js
SeatGeek Sports Tickets: Use moment.js
Re: #1554
* `getDate()`
* `getYear()`
* `getMonth()`
* `getDay()`
* `months[]`
* Letters of the month are now uppercase to be consistent with the other SeatGeek IAs
**Note:** The majority of changes in the diff are a result of adding the `require()` block which pushed everything down one line and indented it. The core changes occur at lines 73-89.
---
IA Page: https://duck.co/ia/view/seat_geek_sports
=> SeatGeek Sports Tickets: Use moment.js

share/spice/couprex/couprex.css
Result:
-----
IA Page: https://duck.co/ia/view/couprex_coupons
=> Couprex: reduce height to 19.5em, remove top-padding from body

share/spice/pwned/pwned.js
I noticed today that the content in the snippet was overflowing and being hidden. This reduces the length of the snippet so you see the ellipses at the end, indicating it's been truncated.
---
IA Page: https://duck.co/ia/view/pwned
=> Pwned: reduce snippet size to 140 chars, currently overflowing tile

lib/DDG/Spice/Cryptocurrency.pm
For issue #2453 . Query now matches on the word 'price'.
The following queries will now trigger:
`'20 ltc price'`
`'dogecoin price'`
=> Cryptocurrency conversion: Fixes #2453

share/spice/forecast/forecast.js
With the addition of moment.js in https://github.com/duckduckgo/zeroclickinfo-spice/pull/2432, the event handler for switching between C and F isn't being attached to the DOM element, because that element won't exist until moment.js is loaded.
=> Hotfix: Forecast: Event handlers aren't attached

lib/DDG/Spice/Nutrition.pm, share/spice/nutrition/nutrition.js
Fixes #2419
The score for results mentioned in #2419 are below 1 - see https://duckduckgo.com/js/spice/nutrition/count
~~Using the `min_score=1` param we can limit results to only return above 1. - documentation https://developer.nutritionix.com/docs/v1_1~~
~~Needs to be deployed to beta for testing as unable to test locally without obtaining new API key.~~
_________
https://duck.co/ia/view/nutrition
=> Nutrition: Add min_score param

lib/DDG/Spice/Grunt.pm, share/spice/grunt/footer.handlebars, share/spice/grunt/grunt.js, t/Grunt.t
This plugin gets its data from http://gruntjs.com/plugin-list.json which I admit is a bit big at around 200kb. I think this is ok though since the triggering is limited to "grunt plugins" and "gruntjs plugins". I think anyone searching with those kind of queries have a high signal that they are actually looking for grunt plugins so I think it's worth loading those 200kb (some IAs even load more data--look at recipes. It makes the page 2MB big with the query "cake")
Hope this is ok!
It's modeled after the rubygems spice:
---
https://duck.co/ia/view/grunt
=> New Grunt Spice

share/spice/couprex/couprex.js
Several Clearbit Logo API calls were failing. It turns out I wasn't properly stripping the url to just the domain + TLD. This fixes it an now we should have several more correct logos in the results.
/cc @AdamSC1-ddg 
IA: https://duck.co/ia/view/couprex_coupons
=> strip content after TLD in company url, fixes logo images

share/spice/dogo_news/dogo_news.js
"**Fixes #2528.** This commit reduces the number of character in author's name to 10 so that it doesn't look broken on smaller screens."
IA Page: https://duck.co/ia/view/dogo_news
=> DogoNews: Stops footer from breaking on smaller screens

lib/DDG/Spice/Couprex.pm, t/Couprex.t
Added some stopwords for Amazon, Ebay and Retailmenot -- we shouldn't trigger when those words are in the query.
/cc @AdamSC1-ddg 
---
IA Page: https://duck.co/ia/view/couprex_coupons
=> Add stopwords to Couprex

share/spice/dogo_news/dogo_news.js
Fixes #2547 . This commit increase the snippet text length to 150 chars.
IA Page: https://duck.co/ia/view/dogo_news
=> Increases snippet length to 150 chars - #2547

lib/DDG/Spice/PublicHolidays.pm, share/spice/public_holidays/countries.txt, share/spice/public_holidays/public_holidays.js, share/spice/public_holidays/record.handlebars, t/PublicHolidays.t
_(Work in progress - see limitations)_
This is a new IA that provides the list of public holidays in a calendar year for a country.
For now I'm using the `List` template but I'd welcome input from the design team.
The following words are triggers for this IA:
- `public holidays`
- `national holidays`
- `bank holidays`
- `federal holidays`
The trigger words can appear anywhere in the query but are carefully inspected to ensure they are matched in the right context before triggering the IA. Queries are inspected for the following components:
Component| Description| Required | Default | Optional Prefix
--------------|----------------|-------------|----------|---------------------
`trigger`    | one of the keywords listed above | Yes |  - | -
`country`   |  the country for which holidays to …
=> New Public Holidays Spice

lib/DDG/Spice/Currency.pm, t/Currency.t
Fixes #2533 
//CC @moollaza 
------
IA Page:  http://duck.co/ia/view/currency
=> Currency: Require space after unit abbreviation

share/spice/public_holidays/public_holidays.js
As per https://github.com/duckduckgo/zeroclickinfo-spice/pull/2536#discussion_r55580445 I've added the `signal` property to this IA
---
https://duck.co/ia/view/public_holidays
=> Public Holidays: Add signal property to IA

lib/DDG/Spice/Equaldex.pm
API currently redirects causing the IA to break in production. This fixes the issue.
Live on Moollaza: https://moollaza.duckduckgo.com/?q=lgbt+rights+in+china&ia=equaldex
IA Page: https://duck.co/ia/view/equaldex
/cc @MrChrisW
=> Fix Equaldex API call to address redirect

share/spice/bitcoin/bitcoin.js
#This IA was incorrectly using 3 different Tab names and IDs.
Seeing as these all live in Bitcoin.pm and Bitcoin.js the ID should be `bitcoin` whenever this IA triggers and the canonical "Answer" tab name works best here -- The metadata and the JS need to match so we can't have more than one tab name.
Fixes #2584 
---
IA Page: https://duck.co/ia/view/bitcoin
=> Bitcoin: Unify ID and Tab name

share/spice/holiday/holiday.js
Noticed there was still a possibility for some irrelevant results so I've added a relevancy check comparing the query and the result holiday name. I chose to ignore the word "day" because it doesn't help confirm if the result or more or less relevant.
I've also switched the tab name to "Answer", which is more canonical.
JSHint also threw some warnings at em so I've cleanup up the comparators and semicolons.
---
IA Page: https://duck.co/ia/view/holiday
Maintainer: @sekhavati
=> Holidays: Add relevancy check, minor code cleanup

share/spice/movie/movie.js
We now use an external API for images anyways so this isn't necessary and is causing problems
Fixes #2591 
---
IA Page: https://duck.co/ia/view/movie
/cc @jagtalon
=> Movies: Remove old check for image filename path

share/spice/amazon/amazon.js, share/spice/isbn/isbn.js
Added more guards in the Amazon/ISBN review callback. It's currently causing errors in some cases where no stars are returned.
cc @b2ddg
=> Make sure r and r.stars exist in amazon/isbn callback

lib/DDG/Spice/UV.pm
The HTTP API now redirects to HTTPS so this is currently broken.
This forces HTTPS and will correct the bug.
---
https://duck.co/ia/view/uv
=> Switch API URL to HTTPS because it now redirects there

lib/DDG/Spice/PublicHolidays.pm
This change extends the types of holiday retrieved from the API to include `Local Holidays`. The reason for this change is because it was noted some holidays in the UK weren't showing up, such as St. Patricks Day (Northern Ireland only) and St. Andrews Day (Scotland only) which are [official holidays](https://www.gov.uk/bank-holidays) in those regions. The list of extra holidays this type includes for the UK can be seen [here](http://www.timeanddate.com/holidays/uk/#!hol=2).
**Note**: this IA caches its results for 30 days thus it will need to be flushed when this change goes live to see the difference (if it doesn't do already).
---
https://duck.co/ia/view/public_holidays
=> Public Holidays: Add Local Holidays to the list of holiday types retrieved

lib/DDG/Spice/MinecraftStatus.pm
The API switched to HTTPS and so the Spice is currently failing.
This updates the code to use the HTTPS API endpoint.
---
https://duck.co/ia/view/minecraft_status
=> Switch API to HTTPS

t/Parking.t
The DuckDuckGo package was recently updated and now the Parking test is failing.
This updates the test to pass again.
/cc @zachthompson @GuiltyDolphin 
---
IA PAge: https://duck.co/ia/view/parking
=> Parking: Update test to support to Australia timezone

share/spice/sports/mlb/games/mlb_score.handlebars
Preseason MLB games are often missing a location, as shown here for:
https://duckduckgo.com/?q=mets
This PR fixes the issue by falling back to `venue.city` when `venue.market` is blank, which seems to often be the case for preseason games (maybe an idiosyncrasy of the API provider).
Here's the MLB IA page:
https://duck.co/ia/view/sports_mlb_games
cc @moollaza @bsstoner @andrey-p
=> MLB Games: Fix location for preseason games

share/spice/maps/maps/maps_maps.js
Adding back string based relevancy check for maps. This used to be the relevancy metric before the single point cutoff was put in place.
@bsstoner @andrey-p
=> Use string relevance for maps

share/spice/transit/njt/train_item.handlebars, share/spice/transit/njt/transit_njt.css, share/spice/transit/path/train_item.handlebars, share/spice/transit/path/transit_path.css, share/spice/transit/septa/train_item.handlebars, share/spice/transit/septa/transit_septa.css, share/spice/transit/switzerland/train_item.handlebars, share/spice/transit/switzerland/transit_switzerland.css
I recently changed the ID's of the four Transit IA's to be more canonical as we ran into some internal issues with the current ID's because they didn't follow the standard convention.
I didn't properly test these changes and noticed today that the CSS has been broken since changing the ID's.
This PR updates the CSS and handlebars templates to match the new IDs.
I've tested it locally and everything looks correct again.
---
https://duck.co/ia/view/transit_septa
https://duck.co/ia/view/transit_path
https://duck.co/ia/view/transit_njt
https://duck.co/ia/view/transit_switzerland
=> Transit IA CSS Fixes

lib/DDG/Spice/Thesaurus.pm, share/spice/thesaurus/content.handlebars, share/spice/thesaurus/thesaurus.css, share/spice/thesaurus/thesaurus.js, share/spice/thesaurus/title_content.handlebars, t/Thesaurus.t
Fixes #412
This PR improves the results displayed by the Thesaurus IA. It also changes the layout. As highlighted in #412 the results displayed were somewhat questionable at times. Below I've listed the changes made to address this and the work that is still outstanding. 
I'd also like to look for a better source of data, perhaps [Wordnik](https://www.wordnik.com/), which is what we use for the Dictionary IA. However that goes beyond the scope of this fix.
1. The results returned from the API are now searched and the word type (noun, adjective etc) with the most entries is selected and displayed on the basis that it's likely to be the most common use case for that particular word
2. The results are now displayed using the `list` template group
3. Regardless of the trigger word used (see …
=> Thesaurus: Fixes #412

lib/DDG/Spice/VRC/Teams.pm, share/spice/vrc/teams/vrc_teams.js, t/VRCTeams.t
This IA fetches statistics for a given VEX Robotics Competition team. It displays them in the infobox along with information about their division, location, etc.
The data source, VexDB.io, is regarded in the community as a really good data source, as the canonical data is split up into a lot of csv files rather than a nice, consumable JSON api.
Unfortunately, the data is split into multiple endpoints, so I used the `spice alt_to` attribute exhibited in [xkcd](https://github.com/duckduckgo/zeroclickinfo-spice/blob/master/lib/DDG/Spice/Xkcd/Display.pm#L12-L16) to add these in. I used jQuery's `$.when().then()` to fire the needed requests off simultaneously rather than sequentially. I'm unsure about its compatibility with IE, but I haven't found anything saying that it's incompatible (I'm …
=> New VRCTeams Spice

lib/DDG/Spice/WordMap.pm, t/WordMap.t
Issue: https://github.com/duckduckgo/zeroclickinfo-spice/issues/2681
This fix adds a regex trigger to allow one word after similar to per the issue description.  Other rules may need to be added such as "words like"
---
https://duck.co/ia/view/word_map
Maintainer: @twinword
=> Restrict similar to to allow only one word for 2681

lib/DDG/Spice/Holiday.pm, t/Holiday.t
Fixes #2651. This is a crude fix that simply addresses the issue mentioned. Any query with the word "primary" no longer triggers this IA, so this should cover other `<state> primary` searches too.
---
IA Page: http://duck.co/ia/view/holiday
=> Holiday: False trigger on "California Primary"

share/spice/just_delete_me/just_delete_me.js
Converted arrow functions to anonymous functions. Arrow functions cause problems for the build system because of UglifyJS which can't handle ES6.
/cc @moollaza 
https://duck.co/ia/view/just_delete_me
=> Switch ES6 arrows to ES5 functions

share/spice/public_holidays/record.handlebars
Some holidays only apply to certain regions within a country, in these instances the IA displays a third column clarifying where it is observed. On small screens (ie: mobile devices) this third column can appear clipped, I've attached some before/after screenshots below from an iPhone 5. The end result isn't an ideal layout, but is an improvement.
---
https://duck.co/ia/view/public_holidays
=> Public Holidays: Ensure cell data is wrapped on small screens

share/spice/currency/currency.css, share/spice/currency/detail.handlebars, share/spice/currency/detail_mobile.handlebars
IA URL: https://duck.co/ia/view/currency
Fixes Issue: #2603
Images of the country flags were being rendered too large on mobile devices. This fix sets a fixed size for the flags on mobile screens. Here is an example of output for small and large input values (on iPhone 5):
=> Currency: Fixes large flag img sizing issue for mobile.

share/spice/xkcd/display/xkcd_display.js
Per the suggestion in #2673, making the mobile enhancement safer for XKCD IA.
https://duck.co/ia/view/xkcd
=> Specifically target xkcd separators when running mobile enhancement

lib/DDG/Spice/YogaAsanas.pm
Don't allow `pose` to trigger when part of other words.
IA Page: https://duck.co/ia/view/yoga_asanas
=> YogaAsanas: Don't allow 'pose' to trigger when part of other words

share/spice/hex/hex.js
This commit fixes an issue found by @moollaza, which appears in Elixir packages with a long description (e.g. [math](https://hex.pm/packages/math)), you can find more details about the issue [here](https://github.com/duckduckgo/zeroclickinfo-spice/pull/2690#issuecomment-211601869)
Also, with this commit, you can see a custom Handlebars helper to return the singular or plural form of a given word base on the value of a number.
----
Hex IA page: https://duck.co/ia/view/hex
=> Hex IA: Limit the string length for the subtitle, contributor and maintainer sections

share/spice/coderwall/coderwall.css, share/spice/coderwall/coderwall.js, share/spice/coderwall/content.handlebars
This PR fixes the issue described in #2548 
Fixes include: 
* Changing the object passed to `normalize` to match the new Coderwall API response
* A custom handlebars helper to parse any markdown in `description`
* Profile avatar images included in `iconImage`
@moollaza suggested also using `chompContent` to hide descriptions that are too long, but I am not sure how to implement it.
CC: @GuiltyDolphin
---
IA Page: https://duck.co/ia/view/coderwall
=> Coderwall: Update to handle markdown content from API (fixes #2548)

lib/DDG/Spice/RustCargo.pm, share/spice/rust_cargo/content.handlebars, share/spice/rust_cargo/footer.handlebars, share/spice/rust_cargo/rust_cargo.js
+ Searches for crates instead of displaying a single crate
+ Now uses the same layout as the GitHub IA.
+ Sorts the relevant crates by downloads.
+ It displays a crates' name, version, date of last release, description and number of downloads.
Fixes #2718 by implementing fuzzy searching.
@tagawa
---
Instant Answer Page:
https://duck.co/ia/view/rust-cargo
=> Rust Cargo: Fix 2718 / Search for crates instead of displaying a single crate

lib/DDG/Spice/BikeSharing/CitiBikeNYC.pm, share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.js
The new GBFS feeds will be the only maintained from now on
More info: https://github.com/NABSA/gbfs/
As a side effect, #2156 is fixed, as they now use POSIX timestamps
Fixes #2745, Fixes #2156 
---
IA Page: https://duck.co/ia/view/citi_bike_nyc
=> Use new GBFS feed for CitiBike NYC

share/spice/xkcd/display/xkcd_display.js
Fixes #2663 
Unfortunately http://xkcd.com/1137/info.0.json is giving us back `â®LTR` as the title. There is no programmatic way of knowing there was a specific unicode character in the title, so I went with a hardcoded override here. This seems a bit kludgey, but it is a way forward. If more overrides like this come to be necessary we might think of a better framework than a bunch of if-statments in the code.
https://duck.co/ia/view/xkcd
=> XKCD IA: Override title for 1137

lib/DDG/Spice/Symbolab.pm, t/Symbolab.t
Bug fix: **`Symbolab: Fix #2708`**
Updated the reigger regex not to fire on unrelated queries such as:
'derivative of a vector function' => undef, 
'integral' 
'current version plugin gnome shell integration' 
'continuous integration'
'integration by parts' 
'derivative of arctan'
'line integral'
'integral calcultor' 
'derivative of a summation' 
'integral ad science'
'derivative of a pmf' 
'integration vs unit tests' 
Also updated unit tests accordingly.
Fix #2708
@moollaza @GuiltyDolphin 
---
Instant Answer Page: https://duck.co/ia/view/symbolab
=> updated regex not to include unrelated integral terms

share/spice/quote_of_the_day/content.handlebars, share/spice/quote_of_the_day/quote_of_the_day.css
On `quote_of_the_day` spice, the output clipped the quote icon on
small screen devices. Also, the author name was misaligned on small
screen devices.
* quote icon hidden on small screen devices using CSS styling
* author name aligned correctly on small screen devices
* CSS media queries were used
See also: #2758
---
Instant Answer Page: https://duck.co/ia/view/quote_of_the_day
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @pnpninja
=> quote_of_the_day: Make spice result responsive in design on small screen devices

lib/DDG/Spice/PlayingCards.pm, t/PlayingCards.t
This is in reference to #2788.
While the Instant Answer will no longer trigger on `deal 4` and anything without `card` or `cards`, I did allow the "s" in "cards" to be optional.
i.e. `deal 10 card` is still a valid match.
Grammatical transgression aside, this should stop triggering on irrelevant queries.
***
IA Page: <http://duck.co/ia/view/playing_cards>
=> PlayingCards: Improve Validation Regex

lib/DDG/Spice/Tvmaze/Nextepisode.pm, lib/DDG/Spice/Tvmaze/Previousepisode.pm, t/Tvmaze.t
**Enhancement**
Adds the ability to make queries like "when does game of thrones come back" or "when does mr. robot season 2 start". https://github.com/duckduckgo/zeroclickinfo-spice/commit/4c3eee28263b081840bb2907defee2fef13a2b29
I was not able to add something like "when is steven universe coming back" because that conflicts with https://duck.co/ia/view/holiday. Not sure of the best way to allow two different Spices to trigger if a query begins with "when is."
**Bugfix**
Also changed the regex parsing to make it possible to ask about a show with a period in the title like "Mr. Robot." https://github.com/duckduckgo/zeroclickinfo-spice/commit/a9b56261ed4362cd646d9e40a690f6c5ba3be674
---
Instant Answer Page: https://duck.co/ia/view/tvmaze_nextepisode …
=> TVMaze: Natural language next episode queries, allows show names with punctuation

share/spice/maps/maps/maps_maps.js
@b2ddg 
Fixes this: https://duckduckgo.com/?q=96+Wythe+Avenue+Brooklyn%2C+New+York+11249
=> More map skip words

lib/DDG/Spice/Dictionary/Definition.pm, t/Dictionary.t
Wordnik doesn't handle queries that have "" in the request and it chokes and turns blue.
For example, `/v4/word.json/#22round%20robbin#22/definitions?includeRelated=true&includeTags=true&limit=3&api_key=(key
removed)&callback=ddg_spice_dictionary_definition`
This strips out the quotes.
---
Instant Answer Page: https://duck.co/ia/view/dictionary_definition
=> Dictionary Definition: Remove quotes before passing it to Wordnik

lib/DDG/Spice/MetaCPAN.pm
When additional query words are provided alongside an apparent module name, this change will extract the module name and ignore other terms.
Improvement for #2877 though probably not a complete fix.
@GuiltyDolphin @sahildua2305 
---
Instant Answer Page: https://duck.co/ia/view/meta_cpan
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): **N/A**
=> MetaCPAN: Attempt to extract module name when additional words are in query

lib/DDG/Spice/Maps/Maps.pm
When adding triggers, put plural or compound forms of the same word first.
For example, if you have @startend_triggers = ("map", "maps") and the input query is
"maps", in the matching step, the query will match "map" first and will then split the
input query into "map" and "s" and pass "s" to the upstream, this is obviously wrong,
so your @startend_triggers should look like ("maps", "map").
Fixes the precedence issues in maps triggers.
@nilnilnil @b2ddg 
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil
=> Fix precedence of maps_maps triggers.

lib/DDG/Spice/SoundCloud.pm
Changing this call to https in hopes that it fixes the spike in soundcloud failures. Seems like the redirect from http -> https is what is causing no results to be returned.
@bsstoner @jagtalon
=> change api call to HTTPS

share/spice/whois/whois.js
I've noticed that the Whois spice didn't redirect to a valid page when you click on the link that appears on the bottom of the instant answer. I modified the URL to now redirect to the correct page.
One issue is, I couldn't find a URL that would show the "raw text" version of the whois response. The best I could get is JSON, and then the user can click over to the "raw text" page. 
---
Instant Answer Page: https://duck.co/ia/view/whois
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b1ake
=> Whois: Fixed the sourceUrl

share/spice/whois/whois.js
In this pull, I fix the issue of #2887, which was if the API Response didn't container the key of `registryData`, it would throw an error because it was checking for values inside of it.
I also added a small performance/readability fix in the `get_first_by_key` function. It now will return the value once it's found, instead of continuing looping through the rest of values.
Fixes #2887  - ensures that objects we are going to check are actually objects and are not undefined.
---
Instant Answer Page: https://duck.co/ia/view/whois
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b1ake
=> Bug Fix: Whois: Fix #2887

lib/DDG/Spice/Maps/Maps.pm
Bump mapbox API from v4 to v5.
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil
=> Bump mapbox geocoder from v4 to v5

lib/DDG/Spice/Bible.pm, share/spice/bible/triggers.txt, t/Bible.t
Adding 
> bible verse of the day
triggers and tests.  Uses the NET Bible API [verse of the day](http://labs.bible.org/api_web_service).  The default 1 day caching seems ok for this verse of the day or should this one also be split out to a separate IA like what is being suggested in #2826 for random bible verse and then enable a much longer cache duration on this current IA?
Fixes #2929  - Adds regex for verse of day and various tests.
@pnpninja @tagawa @hunterlang 
---
Instant Answer Page: https://duck.co/ia/view/bible
=> Bible: adding verse of the day

share/spice/sports/nfl/games/sports_nfl_games.js
* The previous implementation assumed that the possession data will be
always available. This might not be the case, especially when a game
gets canceled or delayed.
This commit fixes the situation by skipping the part of the code that
requires the possession to be filled in.
See above
@b1ake 
---
Instant Answer Page: https://duck.co/ia/view/sports
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @b1ake 
* The previous implementation assumed that the possession data will be
always available. This might not be the case, especially when a game
gets canceled or delayed.
This commit fixes the situation by skipping the part of the code that
requires the possession to be filled …
=> Sports: Fix missing possession in NFL

share/spice/airlines/airlines.js
Given that the original query is done using GTM time, when parsing
the data, the timezone needs to be specified as Z, instead of using
local and then requesting the UTC version of the moment object
Fixes #2771
IA Page: http://duck.co/ia/view/airlines 
Maintainer: @amoraleda
=> Fix airlines IA trigger and date parsing

lib/DDG/Spice/Forecast.pm, share/spice/forecast/forecast.js
Updating the forecast.io endpoint to darksky.net.
@tommytommytommy 
cc @bsstoner 
https://github.com/duckduckgo/zeroclickinfo-spice/issues/3008
=> Change forecast endpoint to darksky.net

lib/DDG/Spice/Rain.pm, share/spice/rain/rain.js
Updating the forecast.io endpoint to darksky.net.
@tommytommytommy
cc @bsstoner
#3008
=> For the Rain IA, change forecast endpoint to darksky.net

share/spice/forecast/forecast.js
Currently we only show the UoM using the defaults (i.e. browser preferences). This commit checks the query for presence of 'celsius' or 'fahrenheit' and sets the displayed UoM appropriately.
---
IA Page: https://duck.co/ia/view/forecast
Signed-off-by: mr.Shu <mr@shu.io>
=> Forecast: Detect and use UoM from the query

lib/DDG/Spice/BrainyQuote.pm
Updating API call as HTTP endpoint now redirects to HTTPS which has cause the IA to be disabled
---
Instant Answer Page: https://duck.co/ia/view/brainy_quote
=> BrainyQuote: Update API call to HTTPS

lib/DDG/Spice/MetaCPAN.pm, share/spice/meta_cpan/meta_cpan.js
- Corrected references in meta_cpan.js to the returned data format for the MetaCPAN API
- Added exclusion rule to query regex to prevent a query with a space preceding hyphen - example: `cpan Mojolicious - plugins`
Fixes #3051 
---
Instant Answer Page: https://duck.co/ia/view/meta_cpan
…ce first object in array for Author, description and date with named key only
=> MetaCPAN: Fixes #3051 - Fix up references in JS for MetaCPAN API

share/spice/what3words/what3words.js
This PR enables the What3Words Spice to provide a link to directions to the 3-word address the user has searched.
The W3W team reached out to me directly with this suggestion, and because it is a trivial change I decided to do it.
---
Instant Answer Page: https://duck.co/ia/view/what3words
=> enable showDirections option for what3words spice

share/spice/meta_cpan/meta_cpan.js
Fix up Javascript query var to contain correct module name for link to MetaCPAN, also moves no results check to earliest point.
Fixes #3060 
@sahildua2305 @GuiltyDolphin 
---
Instant Answer Page: https://duck.co/ia/view/meta_cpan
=> MetaCPAN: Fixes #3060 - strip second form of query from Javascript query var if

share/spice/arxiv/arxiv.js
There were two potential js errors here which would result in images fallback being triggered:
- Accessing elements of `api_result` before ensuring it was populated
- In papers with a single author, `item.feed.entry.author` is an Object, not Array so `map` can't be applied.
Fixes: #3045
@bsstoner
---
Instant Answer Page: https://duck.co/ia/view/arxiv
=> ArXiV: Fixing js errors

lib/DDG/Spice/What3Words.pm, t/What3Words.t
The majority of the triggering of this IA is false positives on technical searches like:
string.prototype.length
system.diagnostics.process 
Fixes #2986
@moollaza 
---
https://duck.co/ia/view/what3words
=> What3Words: remove trigger on word.word.word

lib/DDG/Spice/RxInfo.pm
Triggering way too much on tech-related tablet searches.
Fixes #3052  
@moollaza 
---
https://duck.co/ia/view/rx_info
=> RxInfo: Remove trigger on tablet

lib/DDG/Spice/SkyscannerFlightSearch.pm
In preparation for https://github.com/duckduckgo/duckduckgo/pull/208 where `accept_header` has been deprecated, the `accept_header` call has been replaced with a `headers` hashref.
This commit should go live alongside the DDG Spice changes.
https://github.com/duckduckgo/duckduckgo/pull/208
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/skyscanner_flight_search
=> Skyscanner Flight Search : Update accept headers call

lib/DDG/Spice/Cocoapods.pm
The Cocoapods Spice has never worked in production, since release because the Cocoapods API is confused by the headers we send.
After speaking with the Coacoapods Team, we found that the easiest solution is to send an empty Referer header.
We needed to add better support for Headers to Spice Instant Answers in order to achieve this and we are awaiting for that to be finalized and merged here: https://github.com/duckduckgo/duckduckgo/pull/208
**DO NOT MERGE, until the above PR has been merged**
@soleo @jbarrett @jdorweiler 
---
Instant Answer Page: https://duck.co/ia/view/cocoapods
=> CocoaPods: Set empty referer header to make Cocoapoads API happy

share/spice/what3words/what3words.js
Use `latLng` array instead of separate `lat` and `lon` properties. This enables the internal directions code to work as expected, ensuring the directions URL points to a Lat/Lon pair, instead of the named address string.
---
Instant Answer Page: https://duck.co/ia/view/what3words
=> What3Words: Use latLng array so directions points to lat,lon instead of address

lib/DDG/Spice/Forecast.pm, t/Forecast.t
* Prepare for translated forecasts from DarkSky by passing the `$lang` parameter.
---
=> Forecast: Prepare for translated forecasts

share/spice/transit/njt/transit_njt.js, share/spice/transit/septa/transit_septa.js, share/spice/transit/switzerland/transit_switzerland.js
Patches a bug described in #3037, where status icon colors weren't updating when trains are delayed or cancelled. Class names in JavaScript files are updated to reflect those defined in CSS.
Fixes #3037
@moollaza 
Decided to do in a single commit/PR because the issue was related to what amounts to a template change for IAs of this type, but let me know if you'd rather this were split into 3.
---
Instant Answer Page: https://duck.co/ia/view/transit_septa
Instant Answer Page: https://duck.co/ia/view/transit_njt
Instant Answer Page: https://duck.co/ia/view/transit_switzerland
=> Transit IAs: status icon colors correctly update

lib/DDG/Spice/Flights/Route.pm, t/Flights.t
This handles a bug where a list of all airport codes is returned when one is not specified in the query.
The bug occurs because we split the query on `\s`, but we weren't **_trimming_** the query after replacing words in it. Thus, the check for `scalar(@query) > 2` in `identifycodes` passes, but we don't actually have two words, we have an array: `[ '', 'word2' ]`.
@jdorweiler 
---
Instant Answer Page: https://duck.co/ia/view/route
=> Flights: Trim query before splitting on \s to ensure we have an airline in the query

lib/DDG/Spice/RubyGems.pm
It seems from the unanswered query data that some people have been searching for `ruby install <package_name>`, such as `ruby install compass`. As this is pretty unambigious I have added it to the triggers. 
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/ruby_gems
=> RubyGems: Updated Trigger

share/spice/skyscanner_flight_search/skyscanner_flight_search.js
fixing the short api key for the referral service, missing one character causing the associateId to not be found when referring to Skyscanner website
---
Instant Answer Page: https://duck.co/ia/view/skyscanner_flight_search
=> Skyscanner Flight Search: API key typo fix

share/spice/timer/timer.css
- Prevents over-riding of colours to be visible in dark theme
- Makes `hover` state of play button and `Add Timer` similar
This is what it would look like after this fix on mobile devices:
Fixes #3102
@bsstoner @moollaza @mattr555 
---
Instant Answer Page: https://duck.co/ia/view/timer
=> Timer: Fixes "Add timer" button UI

lib/DDG/Spice/SoundCloud.pm, share/spice/sound_cloud/sound_cloud.js
This PR adjusts the `streamURL` variable to use the new `/sc_audio/` proxy endpoint
---
Instant Answer Page: https://duck.co/ia/view/sound_cloud
=> SoundCloud: Update JS/Perl to hide API Client ID

share/spice/forecast/forecast.js
Checks user's region in setting for determining default setting for units.
Fixes #3107 
@himanshu0113 @bsstoner 
---
=> Forecast: Adds region checking for setting default units

share/spice/news/news.js
Leaving the flag there for future experiments with relevancy.
=> Remove static news experiment

share/spice/sound_cloud/sound_cloud.js
The HTTPS SoundCloud API urls stopped working with our NGINX Proxy, switching the urls to HTTP seems to get them working for now.
Live on Moollaza
Fixes #3149
@bsstoner 
---
Instant Answer Page: https://duck.co/ia/view/sound_cloud
=> Force SoundCloud stream urls to HTTP.

share/spice/forecast/forecast.css, share/spice/forecast/forecast.js
- Reduced: 
- current temp font size, and top margin
- current weather details font size
- Removed current weather details divider
- Added bottom margin to weather details
Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3167
@chrismorast 
---
=> Forecast: Minor design adjustments to Current Weather tile

share/spice/currency/currencyNames.txt
Adds the alias ruble for the Russian Ruble.
Fixes #3168
@pjhampton 
---
=> Currency: Add ruble alias

lib/DDG/Spice/Currency.pm, t/Currency.t
This PR prevents the Currency IA triggering on a single currency, ie. `usd`, `eur`, etc.
@moollaza 
---
=> Currency: Prevents Triggering on Single Currency

share/spice/geometry/geometry.js
Search queries for hemisphere (e.g. "geometry of hemisphere") was displaying results for sphere. This PR adds the shape hemisphere to return correct formulas, calculations and visual.
Screenshots for proposed changes:
Without highlighting
With volume highlighting
With surface area highlighting
Fixes first bug from #3194
@moollaza @pjhampton @pixunil @adityatandon007 
---
Instant Answer Page: https://duck.co/ia/view/geometry
=> Geometry: Add hemisphere shape

share/spice/currency/currencyNames.txt, t/Currency.t
Adds the Alias "lev" for the Bulgarian Lev.
Fixes #3207 
@pjhampton 
---
=> Currency: Adding lev Alias

share/spice/sound_cloud/sound_cloud.js
SoundCloud
The Audio view was deprecated internally and it's been redirecting to 'GridTiles'. This allows us to remove internal code.
@bbraithwaite 
---
=> SoundCloud: Remove deprecated Audio view reference

share/spice/maps/maps/maps_maps.js
This PR moves the high future signal tab check out of the public repo. This only has to do with the map module experiment.
https://app.asana.com/0/72649045549333/304271607844297
@bsstoner 
---
=> moving map module future signal tab check internal

lib/DDG/Spice/Dictionary/Definition.pm
Reviewer: @bsstoner 
CC: @kablamo @malbin @marcantonio 
Description: Add upstream timeouts to the dictionary definition spice because Wordnik is timing out.
This PR *requires* https://github.com/duckduckgo/duckduckgo/pull/243/files.
https://duck.co/ia/view/dictionary_definition
=> Dictionary::Definition: Add upstream timeouts.

lib/DDG/Spice/PackageTracking.pm, share/spice/package_tracking/carriers.yml, t/PackageTracking.t
The existing Fedex, UPS, and USPS Goodies constantly return false-positive results because we rely on our regex to determine if a tracking code belong to one courier or another.
This PR migrates those triggers to the Package Spice so we can trigger on queries that only contain alphanumeric strings that match Fedex, USPS, and UPS tracking number patterns. The API will determine if the number is valid and which carrier it actually belongs to and provide us with the current package status.
This is way more reliable and will prevent us from sending the user to the wrong courier website.
This will also enable us to deprecate those 3 Goodies.
Partially resolve https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3973
@Owlree @pjhampton 
---
Instant Answer Page: …
=> Package Tracking: Add Fedex, UPS, USPS Regex Triggers

lib/DDG/Spice/ExpandURL.pm, share/spice/expand_url/expand_url.js, share/spice/expand_url/title_content.handlebars
Since untiny.me was being flagged as a malicious site by browsers, the IA now uses unshorten.me
**Please note** this change requires an API key.  I have it, just let me know where it needs to go.  I followed the convention I saw used in the repo and put `{{ENV{DDG_SPICE_UNSHORTEN_ME_KEY}}}` where it needs to be inserted.
Fixes #3164 
@moollaza 
@pjhampton 
---
Instant Answer Page: https://duck.co/ia/view/expand_url
=> Expand URL: Replacing Malicious API

lib/DDG/Spice/PackageTracking.pm, t/PackageTracking.t
The updated package tracking IA is over triggering on irrelevant queries like phone numbers.
Changes include:
- Use `query_nowhitespace` instead of `query_nowhitespace_nodash`
- After some internal analysis I couldn't find any legitimate tracking numbers for UPS, USPS or Fedex that use dashes, so the triggers for those should ignore queries containing dashes as they are more likely to be a phone number or possibly a product code
- Additional logic to ignore queries that are obviously a phone number
- Tighter USPS regex (based on USPS tracking number format docs)
- Tightened up and restricted the queries that trigger on generic terms to only trigger on queries that start or end with one of the terms
@bsstoner 
---
=> Package Tracking: Tighten up triggers

share/spice/currency/currencyNames.txt, t/Currency.t
This adds the alternative "rouble" spelling to the Russian Ruble entry in `currencyNames.txt`.
---
=> Currency: Add rouble spelling to Russian ruble

lib/DDG/Spice/Currency.pm, t/Currency.t
"currency" keyword will now trigger currency IA with or without an amount.  For ex: "usd currency", "1 usd currency", "20 usd currency in mexican peso currency", etc.  
Fixes #3214 
@pjhampton 
---
=> Currency: Fixes #3214 Support 'Currency' trigger

share/spice/holiday/holiday.js
Bug fix:
When a user searches for a holiday that occurs on the present day the IA incorrectly displays the following years occurrence as the answer. This is due to the level of precision used when testing if the current date is after the holiday date, we now use `days` instead of the default `milliseconds`. For example if you search for `when is senior citizens day usa` which occurs today (21 aug) it will bring up the 2017 result instead of 2016.
---
Instant Answer Page: https://duck.co/ia/view/holiday
=> Holiday: if holiday occurs on present day display current year as answer

share/spice/maps/maps/maps_maps.js
This simply moves some location relevance checks externally. Basically, don't let anything with relevance < .6 through, unless DDG.isRelevant returns true. In that case, let the first item through.
https://app.asana.com/0/11984721910118/313553685693413
---
=> Maps: moving all location relevance checks external to keep them together.

share/spice/package_tracking/package_tracking.js
Adds an additional URL to the carrier's website for Fedex, UPS, USPS, and Parcelforce
More can be added later 👍 
---
=> Package Tracking: Add URL to carrier website for Fedex, UPS, USPS

share/spice/maps/maps/maps_maps.js
This change allows multiple calls to come through from the upstream provider. We are using this internally to pick out the best response if there are multiple.
This is a part of these:
https://dub.duckduckgo.com/core/ddg/pull/9117
https://app.asana.com/0/11984721910118/309824711142306
---
=> Maps: Allow Multiple Calls

share/spice/maps/maps/maps_maps.js
Use internal function so we can roll out the map module to a limited number of users.
https://app.asana.com/0/246491496396031/318152814646111
@bsstoner 
---
=> Maps: use internal function canShowIAModules() 

lib/DDG/Spice/Npm.pm, share/spice/npm/content.handlebars, share/spice/npm/npm.js, t/Npm.t
Currently this IA is falling back big time! This was the result of an experiment in the programming mission. This PR tries to address this by keeping the tile view, but if the first result if an exact match, then it shows the old content view. See screenshots below:
**Old Content View (Restored)**
**Tile view (still there)** 😉 
Allow user to swap to tile view from text view. For example, `npm buttons` gives a very narrow answer.
https://app.asana.com/0/186344451334986/320438475277974
@moollaza 
cc @bsstoner 
---
=> NPM: Added back text view, drops back to tile view

share/spice/package_tracking/package_tracking.js
- Link title text to carrier when available
- Switch "More at" link to carrier when available, add attribution for Packagetrackr with link to more info
---
=> Package Tracking: Link More at to carrier when available, maintain attribution to Packagetrackr

share/spice/maps/maps/maps_maps.js
This is an internal change to revert back to filtering on 0.9 relevancy.
https://app.asana.com/0/72649045549333/326981472128973
@bsstoner 
---
=> Maps: revert relevance filtering back to 0.9

lib/DDG/Spice/ISBN.pm, t/ISBN.t
- Updated logic to ignore queries that match a phone number lookup
- Added appropriate tests
---
Instant Answer Page: https://duck.co/ia/view/isbn
=> ISBN: Ignore phone numbers, update tests accordingly

share/spice/package_tracking/package_tracking.js
- Handles dates as UTC to ensure correct display (we were adjusting for user locale and misrepresenting the dates)
- Title is now the current status instead of the status description
- Subtitle is now the status description, provided from carrier unless it matches the title (e.g. "Delivered"
- Fixed handling of images for UPS and Fedex
---
=> PackageTracking: Correct date handling, improve title and subtitles

share/spice/maps/maps/maps_maps.js
Internal: https://app.asana.com/0/0/324431312180291
---
=> Maps: add 'latitude' and 'longitude' to skip word array

lib/DDG/Spice/PackageTracking.pm, t/PackageTracking.t
Adds a check for queries containing 'isbn' so that Package Tracking Spice doesn't make an API call.
Fixes #3269 
@moollaza 
---
=> PackageTracking: Stops triggering PackageTracking IA if isbn is present in query.

share/spice/maps/maps/maps_maps.js
We needed to add a couple skip words to the array to improve results when users are searching by zip or postal code. I think the best way to explain is by example:
Searching '19087 zip code' gives a high level map signal. However, the top result from mapbox has place_name: "19087, Pennsylvania, United States" and relevance: 0.49, which is below our filtering threshold. This is where the DDG.isRelevant method comes into play: it compares the query (minus a selection of skip words) to the place name of the top result for similarity. By adding these skip words to that array, DDG.isRelevant will return true, which overrides the relevance # we get from mapbox.
We then need to make sure that the top result isn't filtered out due to its relevance being < 0.6, but that disambiguation items with …
=> Maps: add zip code skip words, allow low relevance results through when DDG.isRelevant is true.

share/spice/currency/currency.css
Remove forced 100% width on select to allow custom dropdown arrow
@pjhampton 
---
=> Currency: Remove forced 100% width on select to allow custom dropdown arrow

lib/DDG/Spice/Cryptocurrency.pm, t/Cryptocurrency.t
These changes should ensure the IA only triggers on queries that involve at least 1 cryptocurrency. Currently, it is capable of triggering on conversions between two of the accepted fiat currencies (e.g. "usd to cad") which the Currency Spice already handles.
Also, this fixes a bug that prevents a conversion of 1 unit from a currency that isn't in the top-10 most popular. E.g. "1 zec to usd"
@pjhampton 
---
=> Prevent triggering on two fiat currencies, properly handle queries with a value of "1"

lib/DDG/Spice/PackageTracking.pm, t/PackageTracking.t
Adds the regexes from the remaining tracking goodies to the package tracking spice.
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3973
@moollaza 
---
=> PackageTracking: Added remaining regexes

lib/DDG/Spice/PackageTracking.pm, t/PackageTracking.t
We're matching on many 9 and 10 digits numbers that are product numbers and phone numbers. I've added in the validation which was previously used by the Goodies to prevent the false positives.
@pjhampton 
---
=> Package Tracking: Add DHL and UPS (9 & 10 digit) Validation

share/spice/currency/currencyNames.txt, t/Currency.t
**Improvement**
This PR adds an alias for `aed currency`
@moollaza @mintsoft 
---
=> Currency: Adds alias 'uae dirham'

share/spice/dictionary/definition/dictionary_definition.js
The API sometime returns results that don't have "text" As those
results have nothing to show, we can filter them out
Fixes #2998
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @colemanhenner @sahildua2305
---
Instant Answer Page: https://duck.co/ia/view/dictionary_definition
=> Bug fix: Dictionary: Fix #2998

share/spice/dictionary/definition/dictionary_definition.js
@moollaza why did we add that above the guard? It seems functionally equivalent to put it below and it's throwing JS errors in production:
```
/t/jse_spice?2101784&msg=TypeError%3A%20undefined%20is%20not%20an%20object%20(evaluating%20'api_result.filter')&url=https%3A%2F%2Fduckduckgo.com%2Fshare%2Fspice%2Fdictionary%2Fdefinition%2F1307%2Fdictionary_definition.spice.js&line=1&col=3628&ct=NZ
```
https://duck.co/ia/view/dictionary_definition
=> Dictionary: Move filter() in dictionary below the guard

lib/DDG/Spice/Cryptocurrency.pm, share/spice/cryptocurrency/cryptocurrency.js, t/Cryptocurrency.t
1. Will now open for all cryptocurrency names that we support (<strike>ftc</strike>, ltc, zcash, etc) except for btc.
2. Will now open on generic queries (defaulting to BTC / local currency) such as "cryptocurrency calculator", "crypto prices" etc.
@moollaza 
cc/ @bsstoner 
---
=> Cryptocurrency: Open up triggering

lib/DDG/Spice/Currency.pm, t/Currency.t
This PR allows queries such as:
- `usd - gbp`
- `322 cad - nok`
@mintsoft `-` is  being captured by the `number_style_regex()` from the NumberStyler role. Is this intended behaviour? I worked around it in 184 - 189
n/a
@mintsoft 
@moollaza 
---
=> Currency: Patch triggering edge case

lib/DDG/Spice/PackageTracking.pm, t/PackageTracking.t
This PR adds the regex trigger for OnTrac and update the test.
Test using `prove -Ilib t/PrackageTracking.t` passed
Earlier:
Now:
Fixes #3344 
@moollaza 
---
=> PackageTracking: Adds the regex for OnTrac

lib/DDG/Spice/Transit/NJT.pm, lib/DDG/Spice/Transit/PATH.pm
I went to update the transit data on my APIs and somehow I lost the credentials to the old app engine service, yet it's still running at its old url (with old data). I spun up a new instance so we can get these IAs working again, would appreciate a quick merge, thanks! 🚋 🚀 
---
Instant Answer Page: https://duck.co/ia/view/transit_njt
=> Transit: updated api urls

lib/DDG/Spice/IsItUp.pm, t/IsItUp.t
Tiny change, return if query does not match the regex
Please refer [comment](https://github.com/duckduckgo/zeroclickinfo-spice/pull/3122#discussion_r99644571)
Fix #3136 
@moollaza @GuiltyDolphin 
---
Instant Answer Page: https://duck.co/ia/view/is_it_up
=> IsItUp: Return if query does not match regex

lib/DDG/Spice/MinecraftStatus.pm, share/spice/minecraft_status/minecraft_status.js
This will simply move from the API I created to the official one. I made my own because I wanted to include Minecraft Realms. However, recently it has gotten hard to check the status of Realms, so I decided to just revert back to the official one.
Fixes #2774 
---
Instant Answer Page: https://duck.co/ia/view/minecraft_status
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @destruc7i0n
=> Minecraft Status: Fix #2774 - Use Mojang API Directly

lib/DDG/Spice/Dota2.pm
Always retrieves the English version of Heroes, Abilities and Items.
If no language is specified in the spice to url, there is a chance that a non-English version is returned. In my case it was a German version. Until the time when it is possible to use the preferred language the user has set in DDG I believe it is best to force English.
Things to note: if a language also changes the name of the item/hero (for example 'l=schinese' for simplified Chinese), the entered name must also be in that language otherwise the item/hero won't be found.
---
Instant Answer Page: https://duck.co/ia/view/dota2
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @echosa
=> dota2: Use English language for heroes and items

lib/DDG/Spice/PackageTracking.pm, share/spice/package_tracking/list_content.handlebars, share/spice/package_tracking/package_tracking.js, t/PackageTracking.t
When no API results returned, provide a list of URL for the user to track the package directly on potential couriers' website.
Also, now ignores potential tracking numbers that start with a 0 as none seem to be valid.
_**Note: This is still WIP. Needs further testing.**_
@bsstoner 
---
=> Package Tracking: Add fallback prompt

share/spice/package_tracking/package_tracking.js
- Expands use of the fallback in cases where the upstream times out or errors.
- Lowers the signal when the fallback is added so that we don't show it unless we absolutely have to (e.g. the Answer bar already opened and left space for it).
/cc @pjhampton @moollaza
=> Expand package tracking fallback

lib/DDG/Spice/Xkcd/Display.pm
The API now redirects HTTP to HTTPS which breaks the IA in production. This updates the API to point directly to the HTTPS endpoint.
Fixes #3178 
---
Instant Answer Page: https://duck.co/ia/view/xkcd
=> XKCD: Switch API call to HTTPS to prevent redirect from HTTP

lib/DDG/Spice/Cryptocurrency.pm, share/spice/cryptocurrency/cryptocurrency.js, share/spice/cryptocurrency/cryptocurrencylist.txt, t/Cryptocurrency.t
Adds [Bitcoin cash](https://www.bitcoincash.org/)
@moollaza 
---
=> Cryptocurrency: Add bitcoin cash

lib/DDG/Spice/Flights/Route.pm
Part-fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3396
---
Instant Answer Page: https://duck.co/ia/view/route
=> Flights::Route under 5.24 push on arrayref is forbidden

README.md
It took me a about an hour of trial-and-error before I found a link to the _DuckDuckHack Docs_ book inside the template module. I think it would be way more useful if this link was nearer the top of the README.
duckduckgo/zeroclickinfo-goodies#4389
---
=> Docs: Add a link to the DuckDuckHack Docs

share/spice/dota2/dota2.js
The API response must have changed and now spaces between bigrams are being padded with underscores. This fixes the search result which was currently being used directly.
Fixes #3296
@pjhampton @echosa
---
Instant Answer Page: https://duck.co/ia/view/dota2
=> Dota 2: Fixes #3296 Skeleton King Trigger not working

share/spice/currency/currencyNames.txt, t/Currency.t
Adds alias "pounds sterling" and test
Fixes #3438 
@pjhampton @moollaza 
---
=> Currency: Add alias pounds sterling to gbp

lib/DDG/Spice/What3Words.pm, t/What3Words.t
Adds new trigger to support the companies new approach to handling addresses.
---
Instant Answer Page: https://duck.co/ia/view/what3words
=> Add new trigger for What3Words

share/spice/amazon/amazon.js
Uses the new template by default to show brand links; leaving the old template in place in case we do a rollback.
=> Enable brand links for all products

lib/DDG/Spice/RandPOS.pm, lib/DDG/Spice/RandWord.pm, lib/DDG/Spice/WordOfTheDay.pm
Forces correct content-type for API responses from Wordnik
Fixes #3466 
@x-15a2 
---
Instant Answer Pages:
- https://duck.co/ia/view/RandWord
- https://duck.co/ia/view/RandPOS
- https://duck.co/ia/view/WordOfTheDay
=> Force JS ContentType for Wordnik API responses

share/spice/tor_node/tor_node.js
Fixes the URLs for Tor Relay Search, the old URLs will stop working at some time in the future. If this is not merged, the links will simply stop working when the old URLs are turned off.
Fixes #3491
@mogigoma
---
Instant Answer Page: https://duck.co/ia/view/tor_node
=> Tor Node: Updates name and URLs for Tor Metrics Relay Search (Fixes: #3491)

share/spice/sports/mlb/games/sports_mlb_games.js
* The API Sports uses no longer returns the same number of innings for
both the home and away teams.
* This commit fixes that situation.
Signed-off-by: mr.Shu <mr@shu.io>
---
=> sports: Prepare MLB for 2018 season

lib/DDG/Spice/Forecast.pm
Enables Japanese, Simplified Chinese and Traditional Chinese trigger words for weather, in addition to existing French, German, Italian, etc.
Non-Roman alphabet city names are already recognised, e.g. [weather 東京](https://duckduckgo.com/?q=weather+%E6%9D%B1%E4%BA%AC&ia=weather)
---
=> Forecast Spice: Added more foreign trigger words

lib/DDG/Spice/Whois.pm
The current API endpoint for WHOIS searches uses version 1.0, which is obsolete according to https://www.whoisxmlapi.com/whois-api-guide.php. This fix changes the endpoint to version 2.0, which requires an API key, instead of the previous username and password. The 2.0 docs can be found [here](https://whoisapi.whoisxmlapi.com/docs).
All tests are continue to pass on duckpan with only this change. The required API key has been named `DDG_SPICE_WHOIS_APIKEY`.
Fixes #3518 
@b1ake @moollaza 
---
Instant Answer Page: https://duck.co/ia/view/whois
=> Whois: Update API endpoint to version 2.0

lib/DDG/Spice/JustDeleteMe.pm, share/spice/just_delete_me/just_delete_me.js
Justdelete.me, the current data source, has been abandoned. The community has created a fork
here that is being updated with new information. Changes the data source for just delete me from http://justdelete.me/# to http://justdeleteme.xyz/#
Fixes #3309
Maintainer: @riqpe
/cc @tupaschoal @neeklamy @PyroSamurai @katzrkool
---
IA Page: http://duck.co/ia/view/just_delete_me
Maintainer: @riqpe
=> Just Delete Me: Switch to new API

lib/DDG/Spice/Thesaurus.pm, share/spice/thesaurus/thesaurus.js
Use TLS when linking to, or making request to the API that powers the thesaurus instant answer.
---
Instant Answer Page: https://duck.co/ia/view/thesaurus
=> Thesaurus: Use TLS for the thesaurus

lib/DDG/Spice/MagicTheGathering.pm, share/spice/magic_the_gathering/footer.handlebars, share/spice/magic_the_gathering/magic_the_gathering.js
According to https://redd.it/7j0s7g, the Deckbrew API shut down on May 1, 2018. There, the API developer suggested using Scryfall's API for future projects. This PR adds support for the Scryfall API to the Magic: The Gathering IA.
Some things DDG might want to clarify with Scryfall:
The Scryfall API is free to use for the purposes of searching cards, and this IA is only searching for cards. The guidelines do say:
> You may not use Scryfall logos or use the Scryfall name in a way that implies Scryfall has endorsed you, your work, or your product.
I am not sure if the "More at Scryfall" link, and the favicon beside it, would indicate endorsement.
> Do not cover, crop, or clip off the copyright or artist name on card images.
The `media` template and some CSS does crop the card image when …
=> MagicTheGathering: Move from deprecated Deckbrew API to Scryfall API

share/spice/magic_the_gathering/magic_the_gathering.js
Changes Magic the Gathering IA, so smaller images are downloaded from Scryfall. More info on Scryfall image formats can be found [here](https://scryfall.com/docs/api/images).
Fixes #3570 
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/magic_the_gathering
=> MagicTheGathering: Change card images to use smaller files

lib/DDG/Spice/Currency.pm, t/Currency.t
Relaxes currency triggering to allow more formats that are also supported by Google, I.e. :
500 USD = ?PLN
500 USD =?PLN
500USD= ? PLN
500 USD=? PLN
500USD = ?PLN
500USD=?PLN
500USD=PLN
---
=> Relax triggering with = and ?

lib/DDG/Spice/Forecast.pm, lib/DDG/Spice/Maps/Places.pm, t/Forecast.t, t/Places.t
- Enable triggering on queries like 'local forecast', 'current weather', 'weather near me'
- Prevent Places from triggering on weather-related queries too
---
=> Foreacst: Trigger on 'current weather', 'local weather', etc.

lib/DDG/Spice/Forecast.pm
Adding some more international triggers based on wikictionary: https://en.wiktionary.org/wiki/weather
I only added the ones I could verify with a translation service, though.
A quick win following up from #3520 
@bbraithwaite @knowak 
---
=> Weather IA: Add more translated triggers

share/spice/is_it_up/is_it_up.js
IsItUp.org can use HTTPS for API calls.  We should use it to better protect users' security and privacy.
---
Instant Answer Page: https://duck.co/ia/view/is_it_up
=> IsItUp: changing HTTP to HTTPS for API call
