- lib/DDG/Spice/Flights/RouteHelper.pm
- share/spice/flights/route/flights_route.js
Problem was that $1 would be encoded so we need a `spice from` before appending it to the URL.
> Flights: Fix #1377

- share/spice/news/news.js
i am an idiot!
@bsstoner @jagtalon 
this fixes the barack obama news issue. once we added a story with the entity relaxation, we were bailing on the rest of the stories!
> news: oops

- share/spice/code_search/code_search.js
> CodeSearch: Fix api_result error checking

- lib/DDG/Spice/TravisStatus.pm
- share/spice/travis_status/content.handlebars
- share/spice/travis_status/travis_status.css
- share/spice/travis_status/travis_status.js
- t/TravisStatus.t
It grabs Travis CI's status from the Statuspage.io page, and shows them to the user.
Quickly see if Travis is down or not, and which pieces are actually down.
StatusPage.io: http://status.travis-ci.com/index.json
It is where Travis posts its own status updates
Twitter, maybe?
"Travis Status", "Travis Up"
programmers
**Is …
> travis status IA

- lib/DDG/Spice/Launchbug.pm
- share/spice/launchbug/content.handlebars
- share/spice/launchbug/launchbug.handlebars
- share/spice/launchbug/launchbug.js
- t/Launchbug.t
Returns infos about a bug posted on Launchpad.net
It is faster and more usefull
LP: 7
LP: #298
(LP: #1234)
coders, bug hunters, Ubuntu lovers
**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
Please place an 'X' where appropriate.
```
[X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[X] Wrote test file and added to t/ directory (https://duck.co/duckduckhack/goodie_tests)
[X] Verified that instant answer adheres …
```
> New Spice: Launchbug

- lib/DDG/Spice/Keybase.pm
- share/spice/keybase/content.handlebars
- share/spice/keybase/keybase.css
- share/spice/keybase/keybase.js
- t/Keybase.t
It retrieves basic information about user from keybase.io.
Shoot me I do not know how to answer to this question.
[keybase.io API](https://keybase.io/docs/api/1.0)
I like [keybase.io](https://keybase.io) and you do not have any instant answer for it.
Not to my knowledge.
```keybase mwolny``` ```keybase jeresig```
Well I …
> Spice for keybase.io

- lib/DDG/Spice/TravisStatus.pm
- share/spice/github_status/github_status.css
- share/spice/travis_status/travis_status.css
- share/spice/travis_status/travis_status.js
- t/TravisStatus.t
https://github.com/duckduckgo/zeroclickinfo-spice/issues/1415
https://github.com/duckduckgo/zeroclickinfo-spice/issues/1416
https://github.com/duckduckgo/zeroclickinfo-spice/issues/1417
> Github Status Color changes

- share/spice/launchbug/launchbug.js
@jagtalon I fixed the wrong domain name, can you merge it?
> Launchbug: fixed domain name

- share/spice/whois/whois.css
- share/spice/whois/whois.js
Fixes #1414 @abeyang  @jagtalon
> Whois: Update Style #1414

- lib/DDG/Spice/Rainfall.pm
Fixing my old attribution :cake:
> Rainfall: Fix attribution

- lib/DDG/Spice/Xkcd/Display.pm
As per https://github.com/duckduckgo/zeroclickinfo-spice/pull/1433
> Xkcd: updated attribution

- share/spice/movie/movie.css
Attempt at fixing #1407 (Movies: Broken on mobile)
Probably going about this the wrong way, changing the wrong css selectors etc, however thought I'd give it a go :grimacing: 
**Current** - https://duckduckgo.com/?q=rotten+tomatoes+guardians+of+the+galaxy&ia=movies
**After Changes**
**CC//** @jagtalon
> Movies: Mobile view

- lib/DDG/Spice/InTheaters.pm
What did I fix?
* Basically this issue - #1310. A simple change to 30 movies shown. I can further change it to whatever value you need but I think 30 should be enough.
> InTheatres - Changed number of movies shown to 30

- lib/DDG/Spice/GoWatchIt.pm
- share/spice/go_watch_it/content.handlebars
- share/spice/go_watch_it/go_watch_it.css
- share/spice/go_watch_it/go_watch_it.js
- t/GoWatchIt.t
The Instant Answer grabs availabilities for movies and television shows from GoWatchIt.com
It organizes all of the availabilities of a given movie or show in a convenient row of easy to understand options.
GoWatchIt.com API
We think that GoWatchIt.com's API
We don't believe so!
watch [title], stream [title], [title] on demand
Movie lovers, and anyone curious as to where they can watch their favorite movies and TV shows.
No.
Potentially CanIStreamIt's instant answer, which seems included in this repo but not live on your site.
Everything seems go to go.
We will need to provide you with an API key. Please talk to our business team for details.
Here's a screenshot:
Checklist
Please place an 'X' where appropriate.
[X] Added metadata and attribution information
[X] Wrote test file and added to …
> added completed GoWatchIt spice plugin with tests

- lib/DDG/Spice/Github.pm
- share/spice/github/github.js
- t/Github.t
This fix the issue reported by @moollaza https://github.com/duckduckgo/zeroclickinfo-spice/issues/1458.
Now the trigger "github" without any parameters will not works. Modified the test file.
The fix is a bit "rude", tell me if this is ok ;)
> Fix Github Spice: trigger

- share/spice/transit/septa/transit_septa.css
This should fix issue #1462. I'm not completely sure that this works with trains that are to arrive in 1 minute or something like that, but feel free to take a look. 
cc @jagtalon
> Fix an issue with on time trains and design.

- lib/DDG/Spice/TravisStatus.pm
- share/spice/travis_status/travis_status.js
- t/TravisStatus.t
Resolving #1457
Triggers on "travisci" and "travis ci" should probably add "travis-ci"
> TravisStatus: Trigger on "travisci"

- lib/DDG/Spice/GithubStatus.pm
- share/spice/github_status/github_status.js
- t/GithubStatus.t
Continuing #1457
+ Trigger on 'github'
+ Signal low
+ Add new test cases
See #1472 similar change to TravisStatus
CC// @jagtalon
> GithubStatus: Trigger on GitHub, Update test cases, signal to low

- lib/DDG/Spice/Timer.pm
- t/Timer.t
Added a new test that @jagtalon wanted for the new trigger in #1446. Also felt that we reached the tipping point for repeat test arguments :neckbeard: 
*edit:* hold up, I'll get #1466 too.
> Timer: added new test for 'time'

- share/spice/guidebox/getid/buy.handlebars
- share/spice/guidebox/getid/guidebox_getid.js
Fixing #1475 & #1476
**Result**
//CC @moollaza
> GuideBox: Fix network showing `null`, Change "paid" to show in button

- share/spice/uv/uv.css
Hey, @moollaza! Talked to @abeyang and he had these changes:
- Color should be white instead of `#fffdfb`
- Font size should be 30px
> uv.css: Some minor tweaks

- share/spice/timer/timer.js
I just noticed this, the start button doesn't enable on mobile! 
cc @jagtalon @moollaza, would like to get this out fast :)
> timer: fix mobile start button enabling

- share/spice/airlines/airlines.js
- share/spice/airlines/content.handlebars
- share/spice/flights/route/content.handlebars
- share/spice/flights/route/flights_route.js
**What's changed?**
+ Removed unused handlebars helpers in `airlines.js` and `flights_route.js`
+ Modified name of `status` helper to `airline_status` for `airlines.js` and `flights_route.js` | Recommend:  #1480
**Screenshot**
//CC @moollaza
> Airline/Flights - Remove unused handlebars helpers

- lib/DDG/Spice/Timer.pm
- t/Timer.t
As per https://duck.co/ideas/idea/4935/additional-phrases-for-timer
> Timer: add 'alarm' trigger

- share/spice/uv/uv.css
- share/spice/uv/uv.handlebars
/cc @jagtalon @abeyang @bjoern
Fixed the CSS. Tested on Windows 8 -- FF, Win 7 -- IE 8, OSX Yosemite -- Safari & Chrome. Should be good :)
> Fix vertical centering of UV Index value

- lib/DDG/Spice/IPLookup.pm
- lib/DDG/Spice/Time.pm
- lib/DDG/Spice/Whois.pm
**What happened here?**
Updated my old attributions to the correct GitHub username
*chrisjwilsoncom=>mrchrisw*
> Attribution Updates

- lib/DDG/Spice/Parking.pm
- share/spice/parking/item.handlebars
- share/spice/parking/parking.css
- share/spice/parking/parking.js
- t/Parking.t
This IA queries the Parking Panda location search api for paid parking near locations in the search string. 
Similar to the Places IA when searching for hotels this Instant Answer provides an overview of available parking options for a location as well as a way to reserve parking in advance.
The Parking Panda API https://www.parkingpanda.com/api/v2/help
I chose this data source because it is ease of use, I am familiar with it, I know the data to be high quality and because I work for Parking Panda.
**Are there any other alternative (better) data …
> Parking Instant Answer

- share/spice/expatistan/expatistan.js
- share/spice/rainfall/rainfall.js
- share/spice/shorten/shorten.css
- share/spice/shorten/shorten.handlebars
- share/spice/shorten/shorten.js
Fixing #1496
**Rainfall**
_______
**Expatisan**
> Standardise fact IA's

- lib/DDG/Spice/Parking.pm
/cc @jagtalon @AlexCutlipParkingPanda
Up on DDH7: https://ddh7.duckduckgo.com/?q=parking+near+radio+city+music+hall&ia=parking&iax=1
> simplify spice from regex, remove DateTime and trailing spaces

- share/spice/sound_cloud/sound_cloud.js
> sound_cloud.js: remove https from the image.

- share/spice/go_watch_it/go_watch_it.js
Old:
New:
CC @bsstoner @moollaza
> GoWatchIt: Remove any text that comes before the Buy/Rent line.

- lib/DDG/Spice/Maps/Places.pm
> Maps::Places: Add trigger: around me

- CONTRIBUTING.md
- README.md
- pull_request_template_spice.md
Per issue #1488. Let me know if I need to add/remove anything!
> Removing IE7 test requirement.

- share/spice/forecast/forecast.css
- share/spice/forecast/forecast_detail_mobile.handlebars
- share/spice/forecast/forecast_item.handlebars
**What did I fix?**:
I fixed issue #1546 where the orientation of the text and icon could cause problems.
cc @jagtalon
> Forecast: Swapped around temperature and icon + fixed styling

- share/spice/go_watch_it/go_watch_it.css
> GoWatchIt: Fix css typo.

- share/spice/xkcd/display/content.handlebars
- share/spice/xkcd/display/xkcd_display.css
//cc @chrismorast @jagtalon @gamehelp16
Updated to match @chrismorast's design:
> XKCD: Simple, static prev/next/explain links

- template/lib/DDG/Spice/Example.pm
+ Caching is enabled by default - remove `spice is_cached => 1;` 
+ Include `spice to`
@moollaza
> Update Template: Example.pm

- share/spice/in_theaters/in_theaters.js
- share/spice/movie/movie.js
We contacted Rotten Tomatoes, but for the mean time, the IA looks really bad. Using this string replacement should fix it. CC @moollaza @bsstoner 
Old:
New:
> InTheaters + Movie: HOTFIX: API change makes the image blurry.

- lib/DDG/Spice/Congress.pm
It works on DuckPAN, but not in production CC @moollaza
> Congress: HTTPS API having problems in production. Moving to HTTP.

- lib/DDG/Spice/Namecheap.pm
@moollaza I changed my GitHub username between when this was originally developed and now, so updating that :tada:
> changed github username

- lib/DDG/Spice/Namecheap.pm
- share/spice/namecheap/namecheap.handlebars
- share/spice/namecheap/namecheap.js
- remove subtitle
- change tab to `Domain`
- hardcode `clientip` param (API is set to ignore it for us)
/cc @abeyang @jagtalon 
Will update DDH8 in a sec...
> Namecheap: Final adjustments

- dist.ini
> Remove MetaYAML Plugin, already using newer [MetaJSON]

- share/spice/color_picker/color_picker.js
- share/spice/color_picker/content.handlebars
/cc @mattr555 @chrismorast 
Small refinement to color harmony selections.
Will deploy to a dev machine soon!
> ColoPicker update

- share/spice/reddit_search/reddit_search.js
> RedditSearch: switch to moment.js

- share/spice/hacker_news/footer.handlebars
- share/spice/hacker_news/hacker_news.js
Just to start off for #1554. Also fixed a problem with the comment link that would use the javascript id of the object, rather than the actual link id.
> HackerNews: fixed comment link, use moment.js for time

- share/spice/drinks/drinks.js
> Drinks: Update Name (fixes #1493)

- lib/DDG/Spice/Guidebox/Getid.pm
- t/Guidebox.t
fixes #1434 
@moollaza @jagtalon any other words you guys can think of, which might improve triggers?
> Guidebox: Tighter triggering (fixes #1434)

- lib/DDG/Spice/SeatGeek/EventsByArtist.pm
- lib/DDG/Spice/SeatGeek/EventsNearMe.pm
- t/SeatGeek.t
> SeatGeak: Added Trigger (fixes #1599)

- share/spice/airlines/airlines.js
- share/spice/airlines/content.handlebars
fixes #226 
@moollaza Colors used for text dont adhere to the styleguide, do we change that?
SS below
> Airlines: show trip duration (fixes #226)

- share/spice/dictionary/definition/content.handlebars
from an internal suggestion.
@moollaza
> add text--primary to dictionary word

- lib/DDG/Spice/Population.pm
- t/Population.t
> Population: Switch from regex to trigger words (fixes #1586)

- share/spice/google_plus/google_plus.js
- share/spice/quixey/quixey.js
- share/spice/sound_cloud/sound_cloud.js
> Use DDG.toHTTP/S where applicable (fixes #1552)

- lib/DDG/Spice/Timer.pm
- t/Timer.t
@moollaza Hei, As you suggested here https://github.com/duckduckgo/zeroclickinfo-spice/issues/1618 I updated the triggers.
> Timer: added more triggers

- lib/DDG/Spice/Tvmaze/Previousepisode.pm
- share/spice/tvmaze/nextepisode/tvmaze_nextepisode.js
- share/spice/tvmaze/previousepisode/tvmaze_previousepisode.js
- share/spice/tvmaze/show/tvmaze_show.js
- t/Tvmaze.t
See #1583
Up on http://duckdev.tvmaze.org:5000/
> TVmaze improvements

- .travis.yml
- dist.ini
* Remove generation of .travis.yml from dzil
* Add container routing to .travis.yml
> Remove TravisCI from dzil and use Travis container infrastructure

- share/spice/npm/content.handlebars
- share/spice/npm/npm.js
fixes #1530 
@jagtalon @moollaza I think this is the most useful information we can have here, where do you guys think dependencies should be shown? i included both places, also let me know what other info you think should be there.
SS below
> Npm: Include more Info (fixes #1530)

- lib/DDG/Spice/RedditSubSearch.pm
@moollaza I changed the trigger system about this issue: https://github.com/duckduckgo/zeroclickinfo-spice/issues/1591 . Now it works properly but I don't know if this is the best solution
> Reddit: Switch from regex to word trigger

- lib/DDG/Spice/Time.pm
Saves us about 20Kb per request!
/cc @jagtalon
> Disable prettyprint of API response

- t/SimilarSites.t
@jagtalon @moollaza 
Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>
> similarsites: added test file

- share/spice/newint/newint.js
Added support as mentioned in #1554.
> Newint - support for moment.js

- share/spice/dictionary/definition/content.handlebars
- share/spice/dictionary/definition/dictionary_definition.css
cc @moollaza @sdougbrown @bsstoner
> Updated 'plural form of...' line and "audio unavailable' padding

- lib/DDG/Spice/Movie.pm
Noticed this was a little outdated because we previously had many more triggers. There's no need for the logic we currently have in the `handle`
/cc @jagtalon
> Movies: Simplify handle function, remove old comments

- share/spice/whois/whois.js
:warning: There's currently an issue with using the existing function to parse dates resulting in `undefined` being returned, see [live example](https://duckduckgo.com/?q=whois+see.se&ia=whois) :warning: 
**What this does:** See #1554
+ Update prettifyTimestamp function to support moment.js date parseing
+ Wrap in require moment.js function
**Screenshots**
________________
> Whois: Support for moment.js

- lib/DDG/Spice/Hayoo.pm
- share/spice/hayoo/hayoo.css
- share/spice/hayoo/hayoo.js
- t/Hayoo.t
fixes #1399 
@jagtalon This seemed like the best way to organize the info, let me know if this needs changes.
SS below
> Hayoo: Updated to be restored (fixes #1399)

- share/spice/bitcoin/bitcoin.css
- share/spice/whois/whois.css
- share/spice/whois/whois.js
This depends on an internal PR.
We're adding some new built-in templates (list), and simplifying some spacing and alignment concerns so this PR is just two update a few affected spices.
to @bsstoner
> Content Layout Updates

- share/spice/seat_geek/sports/seat_geek_sports.js
Fixes #1686
@moollaza sorry about that, I must have missed this one when I removed the function and the calls to it!
> Fix for SeatGeek::Sports: JS Error

- share/spice/similar_sites/content.handlebars
- share/spice/similar_sites/similar_sites.css
- share/spice/similar_sites/similar_sites.js
Fixes #1672. Removed the helper function and moved the HTML generation to the template.
> SimilarSites: Removed helper

- share/spice/currency/currency.css
> Currency: The image and image border are not properly aligned

- share/spice/whois/whois.js
> spice/whois - fixed indentation

- lib/DDG/Spice/Github.pm
- share/spice/github/footer.handlebars
- share/spice/github/github.js
Fixes #1694. Also, saw `String::Trim` being used, replaced it with `Text::Trim`.
> spice/github - using Text::Trim, removed helper, using moment.js

- lib/DDG/Spice/TorNode.pm
> Fix `spice from` regex, anchors aren't necessary

- lib/DDG/Spice/DebVersion.pm
> deb_version - added metadata

- share/spice/sound_cloud/sound_cloud.js
This goes along with an internal PR.
> Soundcloud: removing waveform

- share/spice/astrobin/subject/astrobin_subject.js
- share/spice/gifs/gifs.js
- share/spice/images/images.js
This goes hand in hand with an internal PR.
> Astrobin, Gifs, Images: update to new image property names

- lib/DDG/Spice/WordMap.pm
- share/spice/word_map/word_map.js
Twinword's Word Map instant answer has been modified with SSL connection, favicon, and sourceurl changes.
> Twinword's Word Map sorceurl, SSL connection, and icon changed.

- lib/DDG/Spice/Guidebox/Getid.pm
- t/Guidebox.t
Giving this query space to the GoWatchIt Spice.
/cc @jagtalon
> Reduce Guidebox triggers, update tests

- lib/DDG/Spice/Maps/Places.pm
- t/Places.t
> Maps::Places - not triggering for 'local time', added test

- t/Astrobin.t
> t/Astrobin.t: Fix failing test.

- share/spice/iplookup/iplookup.js
Live error: https://duckduckgo.com/?q=107.191.116.44
```js
TypeError: api_result.ddg.blacklists is undefined
```
We need to check blacklists exists before checking length. 
I broke this in c833f6ad901eac52a36af1c660c88eb285775634 :smiley:
> IPLookup - Hotfix

- share/spice/color_picker/color_picker.css
> color_picker.css: Add border to color swatches.

- share/spice/launchbug/launchbug.js
> Lanuchbug: Add moment.js support

- share/spice/word_map/word_map.js
Changed sourceUrl. Now more at link shows visualization graph with user typed search word.
> sourceUrl shows visualization

- share/spice/sun_rise_set/content.handlebars
- share/spice/sun_rise_set/sun_rise_set.css
> sun_rise_set - using tx--14 class

- share/spice/quandl/world_bank/quandl_world_bank.js
> quandl - changed tab name

- share/spice/color_picker/color_picker.css
> color_picker - updated palette_input border and backgroup colors

- share/spice/newint/buy.handlebars
- share/spice/newint/content.handlebars
Using {{url}} for the <a href> links instead of building it up with the broken {{id}}.
> Fixed broken links.

- lib/DDG/Spice/Forecast.pm
- t/Forecast.t
> Forecast: return city, region and country

- share/spice/get_events/get_events.js
- share/spice/get_events/item.handlebars
Merged with latest code and inserted the timezone fixes.
> Fixed wrong timezone issue

- lib/DDG/Spice/Airlines.pm
- share/spice/airlines/airlines.js
- share/spice/airlines/content.handlebars
This PR fixes the Airlines IA by making it explicitly use the FlightStats endpoint and brings us one step closer to unifying the Airlines and Flights/Route IAs!
> Modify Airlines IA to use FlightStats v2 API

- share/spice/forecast/forecast.js
> Forecast: Remove old meta text attributes

- lib/DDG/Spice/Timer.pm
- t/Timer.t
> Timer: fixed query on 'time'

- lib/DDG/Spice/SublimePackages.pm
- share/spice/sublime_packages/footer.handlebars
- share/spice/sublime_packages/skipwords.txt
- share/spice/sublime_packages/sublime_packages.js
- t/SublimePackages.t
Search for information about Sublime Text packages
https://packagecontrol.io
+ sublimetext package code
+ sublime text package php
Developers, Sublime Text Lovers
**What does the Instant Answer look like? (Provide a screenshot for new or updated Instant Answers)**
**Live Example: http://duckpan3.mrchris.me/?q=sublime+text+package+code&ia=software**
Please place an 'X' where appropriate.
```
[X] Added metadata and attribution information (https://duck.co/duckduckhack/metadata)
[X] Wrote test file and added …
```
> Sublime Text Package IA

- share/spice/astrobin/subject/astrobin_subject.js
- share/spice/gifs/gifs.js
- share/spice/images/images.js
- share/spice/videos/videos.js
Switching to images/videos template groups now that they've been added internally.
@moollaza
cc @sdougbrown
> switch to using images/videos template groups

- share/spice/recipes/recipes.css
This goes with an internal PR. Need to update some spices to work with Detail changes.
> Updates for DetailSlider changes

- share/spice/recipes/recipes.css
- share/spice/recipes/recipes_detail.handlebars
Before:
After:
Mobile:
cc @chrismorast @sdougbrown @nilnilnil
> Fix recipes button

- lib/DDG/Spice/Quandl/Fundamentals.pm
- lib/DDG/Spice/Quandl/HomeValues.pm
- lib/DDG/Spice/Quandl/WorldBank.pm
- lib/DDG/Spice/SalesTax.pm
- lib/DDG/Spice/SunRiseSet.pm
- lib/DDG/Spice/Time.pm
- lib/DDG/Spice/Transit/SEPTA.pm
- lib/DDG/Spice/Transit/Switzerland.pm
Use LoadFile to ingest YAML from disk.  Addresses https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1114
> Convert slurp/Load to LoadFile

- share/spice/seat_geek/sports/seat_geek_sports.js
> make sure we specify month inside dateBadge obj

- lib/DDG/Spice/SoundCloud.pm
- lib/DDG/Spice/SoundCloudResult.pm
- share/spice/sound_cloud/sound_cloud.js
- t/SoundCloud.t
Things like "soundcloud ray bradbury" seem to work
> SoundCloud: Work around the broken tokens.

- share/spice/mass_on_time/item.handlebars
- share/spice/mass_on_time/mass_on_time.js
- Moved all JS inside a closure (as is the new standard for JS files and callbacks)
- Switched to use Moment.js to 24->12hr time conversion
Result:
/cc @abeyang @laouji
> Wrap JS in closure, switch to Moment.js for time handling

- share/spice/mass_on_time/mass_on_time.js
> mass_on_time - failing the spice when needed

- share/spice/rhymes/rhymes.js
> Rhymes - wrapping in closure of new API

- lib/DDG/Spice/Snow.pm
- share/spice/snow/snow.css
> Fixed left padding for Is it snowing

- share/spice/mass_on_time/mass_on_time.js
> mass_on_time - updated id

- lib/DDG/Spice/GoWatchIt.pm
- t/GoWatchIt.t
I think this should solve #1865
> Supports trigger movie

- share/spice/similar_sites/similar_sites.css
Fixes clipping of content.
/cc @chrismorast @abeyang 
Result:
Mobile:
> SimilarSites: Font weight 400, font size 1.15em

- share/spice/images/images.js
> images - wrapped in closure of new API

- share/spice/videos/videos.js
> Videos - wrapped in closure of new API

- share/spice/sound_cloud/sound_cloud.js
> SoundCloud: Changed ID to sound_cloud (fixes #1899)

- lib/DDG/Spice/TravisStatus.pm
> TravisStatus: Changed to HTTPS endpoint (fixes #1905)

- share/spice/seat_geek/events_by_artist/seat_geek_events_by_artist.js
- share/spice/seat_geek/events_by_city/seat_geek_events_by_city.js
- share/spice/seat_geek/events_by_venue/seat_geek_events_by_venue.js
- share/spice/seat_geek/events_near_me/seat_geek_events_near_me.js
- share/spice/seat_geek/sports/seat_geek_sports.js
Prevents conflict with coming Sports IA.
/cc @sdougbrown @b1ake
> Changes SeatGeek::Sports name to Tickets

- lib/DDG/Spice/PlayingCards.pm
- share/spice/playing_cards/content.handlebars
- share/spice/playing_cards/playing_cards.css
- share/spice/playing_cards/playing_cards.js
- t/PlayingCards.t
It enables a user to be dealt a hand of n cards. "deal 5 cards" will give them images of five random cards.
It's not really a problem, but it's fun. :)
<http://deckofcardsapi.com>
I recently came across it over at Hacker News, and thought it might be fun to do something with it.
Not that I know of.
* "deal 7 cards"
* "deal 12"
**Which communities will this Instant Answer be especially useful for? (gamers, book lovers, …
> New IA: Playing Cards

- share/spice/playing_cards/playing_cards.js
Switching to a better `name` for the tab.
/cc @kbhat95
> Playing Cards: change name to

- lib/DDG/Spice/MetaCPAN.pm
- share/spice/meta_cpan/meta_cpan.js
Fixes the broken link mentioned in #1815  
My first duckduckhack, so do let me know if anything's gone gooey (I'm assuming the Pull Request Template would be overkill for this though). The fix was manually verified and the build dzil-tested.
> MetaCPAN Spice fix

- lib/DDG/Spice/Wikinews.pm
- share/spice/wikinews/wikinews.js
> Wikinews: Switch API call to HTTPS to prevent redirect

- share/spice/similar_sites/similar_sites.css
Border set to transparent #1857
> Fix border css

- share/spice/news/news.js
Refactored `news.js`
Refer to #1896
> News - Update to latest Spice API

- share/spice/amazon/amazon.js
- share/spice/in_theaters/in_theaters.js
- share/spice/isbn/isbn.js
- share/spice/movie/movie.js
Requires internal Spice API changes
> Replace Amazon/Movies DOM hacking

- share/spice/snow/snow.css
- share/spice/snow/snow.js
- Revert change to default background colour (discussed internally and decided this is best for now)
- Cleanup code formatting
Result:
/cc @gokul1794 @chrismorast
> IsItSnowing Update

- share/spice/gravatar/gravatar.js
Continuation of #1925 
@moollaza Fixed.  Hope this works now...
> Gravatar - Check for null profiles

- lib/DDG/Spice/Pokemon/Data.pm
This caught my fancy.  I thought we could do a better job here, so this is just a start. :smile: 
to @moollaza 
cc @jagtalon
> Pokedex Triggers

- share/spice/bitcoin_address/bitcoin_address.css
> Bitcoin Address: Change CSS class to remove QR code display on mobile

- share/spice/currency/currency.css
> Currency: Lighten divider color on mobile

- lib/DDG/Spice/Whois.pm
- t/Whois.t
> Whois: Fix port replacing regex

- share/spice/sound_cloud/sound_cloud.js
> set signal high for soundcloud

- share/spice/pokemon/data/pokemon_data.js
Fixes #1969.
This is how it looks now -
> Pokemon data - added more relevant MoreAt section

- share/spice/people_in_space/people_in_space.css
Small UI tweak
/cc @abeyang @MrChrisW
> small increase to tile and .info height

- .travis.yml
- dist.ini
Put these back in distro for catching errors on release.
> Re-add tests to distro

- share/spice/forecast/forecast.js
Updating Forecast to the new API. #1896
> Forecast to new Spice API

- share/spice/maven/maven.js
This one was a quickie – tests checked out on my end.
> refactored maven to use new API. fixes #1896

- lib/DDG/Spice/GooglePlus.pm
- share/spice/google_plus/content.handlebars
- share/spice/google_plus/google_plus.css
- share/spice/google_plus/google_plus.js
- Adjust css to remove border overflow (fixes #1928)
- Update to latest Spice API (fixes #1896)
- Update to `product` template group
_Some comments_: 
Had an awful time debugging the `product_item` attributes.  Seemed like the `title` attribute didn't work, but managed to find one that did – `heading`.  
Someone should look into the templates to see if the DuckDuckHack documentation matches up to it.  Would definitely help the newbies like me to understand how things are set up...
> Google Plus – Spice API, template updates, CSS amendments

- lib/DDG/Spice/SimilarSites.pm
- t/SimilarSites.t
> added similar site as trigger

- share/spice/is_it_up/detail.handlebars
- share/spice/is_it_up/is_it_up.css
> Fix colors for IsItUp in Dark theme

- share/spice/product_hunt/product_hunt.js
Fixes broken tile links which have suddenly become relative links...
/cc @jdorweiler @jagtalon
> Producthunt fix

- share/spice/similar_sites/similar_sites.css
as @chrismorast said in #2025, this fixes the issue:
> make line height avoid cropping in SimilarSites IA

- share/spice/currency/currency.js
> set signal 'high'

- lib/DDG/Spice/Rain.pm
- share/spice/rain/content.handlebars
- share/spice/rain/rain.js
- t/Rain.t
Fixes #1577.
Note:
- Using dummy api endpoint.
- Showing the current condition. Should we also show if it's Going to rain anytime soon?
---
IA Page: https://duck.co/ia/view/rain
> Rain - is it raining?

- lib/DDG/Spice/RandWord.pm
- t/RandWord.t
> RandWord: fixed trigger on extra words

- share/spice/currency/detail_mobile.handlebars
> Update metabar class, fix moreat alignment

- lib/DDG/Spice/Npm.pm
- t/Npm.t
Fixes #2064.
- Added `nodejs` as a trigger
- Added tests
> Npm - added nodejs trigger and test

- lib/DDG/Spice/Twitch/Streams.pm
> twitch - increased limit of stream search

- share/spice/twitter/twitter.js
> twitter - not showing divider if no location is available

- share/spice/hearthstone/hearthstone.js
> Hearthstone: Changed `name` to "Gaming"

- share/spice/envato/audio.handlebars
- share/spice/envato/envato.css
- share/spice/envato/envato.js
Before:
After:
@jagtalon @moollaza
> Envato review count fixes

- share/spice/statista/statista.css
- t/Statista.t
Adding in some final adjustments. Looks great!
/cc @abeyang @statista
> Add padding to tile__foot and tile__body, namespace css

- share/spice/aqi/aqi.css
Fixes #2041.  Previews on desktop and mobile.
> Air Quality Index: Vertical center color label

- share/spice/dictionary/definition/dictionary_definition.js
Fixes the dictionary ID. 
Don't merge yet.  I want to do some testing.
------
IA Page:  http://duck.co/ia/view/dictionary_definition
> fix dictionary id

- lib/DDG/Spice/Sports.pm
- lib/DDG/Spice/Sports/Sports.pm
> Sports Perl Package

- lib/DDG/Spice/LaunchpadProject.pm
- share/spice/launchpad_project/footer.handlebars
- share/spice/launchpad_project/launchpad_project.css
- share/spice/launchpad_project/launchpad_project.js
- t/LaunchpadProject.t
The IA searches and returns results for projects hosted on [Launchpad](https://launchpad.net/).
This provides results for projects hosted on Launchpad at a glance, including summaries of the projects and specifying the group that maintains the projects, rather than having to search through the Launchpad website itself.
The reference documentation on the specific API used can be found here: https://launchpad.net/+apidoc/devel.html#projects
It is the official Launchpad API to query and return results for packages hosted on that website.
**Are …
> DDG IA - Launchpad Project

- lib/DDG/Spice/Hayoo.pm
@moollaza  Refers to [PR](https://github.com/duckduckgo/zeroclickinfo-spice/pull/1977).
/cc @headprogrammingczar
> Remove 'haskell' trigger from Hayoo IA.

- lib/DDG/Spice/Aur.pm
- share/spice/aur/aur.js
> Arch User Repository: Fix sourceUrl

- share/spice/quandl/fundamentals/quandl_fundamentals.js
- share/spice/quandl/home_values/quandl_home_values.js
fix for https://github.com/duckduckgo/zeroclickinfo-spice/issues/2131
> added url parameter to results

- lib/DDG/Spice/YogaAsanas.pm
- share/spice/yoga_asanas/footer.handlebars
- share/spice/yoga_asanas/yoga_asanas.css
- share/spice/yoga_asanas/yoga_asanas.js
- t/YogaAsanas.t
Displays individual and sequences of yoga postures, the sanskrit name, and English translation.  T
Quick way to the image, name, and translation of many yoga postures.
[DDG::Longtail::YogaAsanasAPI](https://github.com/duckduckgo/zeroclickinfo-longtail/pull/18)
It is a custom API comprised of three separate sources (see https://github.com/duckduckgo/zeroclickinfo-longtail/pull/18 for more details.)
"dandasana", "surya …
> New spice for Yoga Asanas

- lib/DDG/Spice/GoWatchIt.pm
- t/GoWatchIt.t
Fixes #2070.
- Added list of stop words
- added tests for them
> go_watch_it - added stop words and tests

- pull_request_template_spice.md
/cc @zekiel @tagawa @talsraviv
> Update for clarity, add gif demo

- lib/DDG/Spice/GoWatchIt.pm
> GoWatchIt: Small updat, remove experimental smartmatch operator

- share/spice/news/news.js
This should fix #2129
-----
IA Page: https://duck.co/ia/view/news
> sort news by date

- lib/DDG/Spice/Maps/Maps.pm
- share/spice/maps/maps/maps_maps.js
Changing the geocoder endpoint here. Also adjusting the relevancy filter to use returned relevance information. 
@nilnilnil @tommytommytommy @brianrisk
> Maps geocoding changes

- share/spice/people_in_space/people_in_space.js
> Added Kazakhstan to countrycode.

- lib/DDG/Spice/BikeSharing/CitiBikeNYC.pm
- share/spice/bike_sharing/citi_bike_nyc/content.handlebars
- Improved handle function
- added check for defined `$loc` variable
- build regex using array + `join`
- removed unneeded `<div class="table__body">` from content template
/cc @marianosimone @AcriCAA
> BikeSharing CitiBikeNYC: Improved handle function and template cleanup

- share/spice/maps/maps/maps_maps.js
Changing the relevancy threshold to a stricter value of 0.9
@tommytommytommy @nilnilnil
> Increase maps relevancy cutoff

- share/spice/bike_sharing/indego_phl/bike_sharing_indego_phl.js
> BikeSharing PHL: fix indentation

- lib/DDG/Spice/Maps/Places.pm
- t/Places.t
Changing handle remainder to handle query_lc so the full query is passed to local
@bsstoner @nilnilnil @tommytommytommy
> pass full query_lc to local

- lib/DDG/Spice/WGHA.pm
- t/WGHA.t
Hi All,
I have updated the Spice wgha with more cities and more trigger words.
Regards
Samuel
> Updated Spice wgha with more cities and triggers

- share/spice/cryptocurrency/cryptocurrency.css
- share/spice/currency/currency.css
- share/spice/people_in_space/people_in_space.css
Fixes duckduckgo/zeroclickinfo-spice#2137
> CSS Cleanup, remove legacy IE8 classes

- share/spice/go_watch_it/go_watch_it.css
Fixes duckduckgo/zeroclickinfo-spice#2136
> Increase GoWatchIt footer margin to be consistant with padding.

- share/spice/timer/timer.js
Fixes #2147
This PR will also have the timer sound looping, but I'll add this once we've cleared up some interaction stuff with @abeyang.
cc @russellholt 
-----
IA Page: https://duck.co/ia/view/timer
> Timer tweaks

- pull_request_template_spice.md
fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/1625
* Added windows 10 as a new platform.
* Added Linux as a new platform.
> Added Windows 10 and Linux as platforms for spice

- share/spice/uv/uv.js
> UV: Change signal to 'high'

- share/spice/timer/timer.css
> Timer: Update progress bar colour

- share/spice/sports/sports.js
This removes the out-of-order game that was being inserted in mobile portrait mode.
to @bsstoner 
cc @b1ake @chrismorast
> (Sports) Remove special boxscore re-sorting for mobile

- lib/DDG/Spice/Drinks.pm
- share/spice/drinks/drinks.txt
- t/Drinks.t
Improvements for #2191 
- Fix calls with failure (a|an|in|of): 
>mix a grand-ma in a wheelchair
> recipe of bit of russiaan honey
> Drinks: Improve the Drink Name Filter

- lib/DDG/Spice/OpenNIC.pm
- share/spice/open_nic/content.handlebars
- share/spice/open_nic/open_nic.css
- share/spice/open_nic/open_nic.js
- t/OpenNIC.t
List OpenNIC DNS
Search based on keywords, with ability to choose between ipv4 and ipv6 addresses.
The opennic website uses fixed options to search the DNS, while their API could
allow the user to precise a lot of things.
https://api.opennicproject.org/geoip/?help
This is the OpennicAPI
No, only an html page on opennic's wiki : http://wiki.opennicproject.org/Tier2
opennic, neutral dns, censor-free dns  (lists 4 DNS close …
> Cylgom's OpenNIC DNS Spice

- share/spice/indeed_jobs/footer.handlebars
- share/spice/sublime_packages/footer.handlebars
Fixes #1873. Should fix both **Indeed Jobs** and **Sublime** design.
_This pull request is a fix for pull request #2229 which was not properly done (contained unwanted commits)_
> Fixes issue #1873 (proper pull request)

- share/spice/people_in_space/people_in_space.js
> People In Space: Set signal as "high"

- share/spice/people_in_space/people_in_space.js
Fixes issue #2261
-----
IA Page: http://duck.co/ia/view/people_in_space
> PeopleInSpace: Code Cleaning

- template/lib/DDG/Spice/Example.pm
* Remove (most) metadata from module template
* Simplify syntax
> Remove metadata from template

- lib/DDG/Spice/Coursebuffet.pm
- share/spice/coursebuffet/coursebuffet.js
- t/Coursebuffet.t
Issue #2228 - Coursebuffet: Should trigger on Learn X Online
> Issue #2228 - Coursebuffet: Should trigger on Learn X Online

- lib/DDG/Spice/Timer.pm
- t/Timer.t
Fix the Issue #2245 - Timer: Triggering on "countdown.js" 
-----
IA Page: https://duck.co/ia/view/timer
> Issue #2245 - Timer: Triggering on "countdown.js" 

- t/Currency.t
- t/YogaAsanas.t
> Prevent Wide Character Warnings

- share/spice/in_theaters/in_theaters.css
- share/spice/in_theaters/subtitle_content.handlebars
Fixes issue #2217 using an old CSS class which looks abandoned.
> Fixes issue #2217

- share/spice/rand_word/rand_word.js
- share/spice/rand_word/single_word.handlebars
I hope this will fix #2253
---
IA Page: http://duck.co/ia/view/rand_word
> Fixing Issue #2253

- lib/DDG/Spice/Riffsy.pm
> Riffsy: Fixes #2291

- share/spice/go_watch_it/content.handlebars
- share/spice/go_watch_it/go_watch_it.css
- share/spice/go_watch_it/go_watch_it.js
How it looks right now:
With this fix:
> GoWatchIt: Fix broken template

- lib/DDG/Spice/Pwned.pm
- share/spice/pwned/pwned.js
Needs coordination with https://github.com/duckduckgo/duckduckgo/pull/157
This IA searches haveibeenpwned.com for email accounts exposed in data breaches
This information isn't readily apparent from organic links. The text dumps have been nicely parsed and made available through this api.
haveibeenpwned.com
It's a definitive source and well made api.
no
pwned test@hotmail.com
have i been pwned test@hotmail.com
**Which …
> New Pwned Spice

- share/spice/people_in_space/people_in_space.js
> Fix people in space metabar text

- share/spice/octopart/octopart.js
> Fix Octopart JS Error

- share/spice/timer/timer.js
> Timer: Fixes #2315

- share/spice/sound_cloud/sound_cloud.js
- t/SoundCloud.t
Depends on: https://github.com/duckduckgo/duckduckgo/pull/168
/cc @zachthompson @b2ddg
> SoundCloud: ensure call is encoded; result of fix to DDG lib

- template/share/spice/example/example.js
- template/t/Example.t
Tested with changes introduced in https://github.com/duckduckgo/p5-app-duckpan/pull/289
> templates: use ia_id instead of lia_name

- lib/DDG/Spice/Keybase.pm
- share/spice/keybase/keybase.js
Show any keybase user info. Added all social accounts verified by user.
Show all public information for a particular account. 
https://keybase.io/docs/api/1.0/call/user/lookup
Well designed API
No
``keybase xinjiangshao`` 
``keybase chris``
Software developers
**Is this Instant Answer connected to a DuckDuckHack [Instant …
> Added all verified accounts for keybase spice. Ref #1864

- share/spice/pwned/pwned.js
Just reusing the url that was already being generated to make every item in the list link to the source
fixes #2325
> add link to details of pwned IA

- share/spice/quixey/quixey.js
fixes #2342 and fixes #2364
-----
IA Page: https://duck.co/ia/view/apps
> use avg_rating in quixey results when available

- share/spice/rx_info/rx_info.js
> Replace bad semicolon with comma

- share/spice/rain/rain.js
Remove debug console.log - Rain IA
> Remove debug console.log - Rain IA

- share/spice/amazon/amazon.js
Remove debug console.log - Amazon IA
@bsstoner Oops! 0a4431e6fcdc5e2337d9ad63244e981f9083e637 :laughing:
> Remove debug console.log - Amazon IA

- share/spice/missing_kids/footer.handlebars
- share/spice/missing_kids/missing_kids.css
- share/spice/missing_kids/missing_kids.js
Minor changes to UI and tile width/height:
Result:
-----
IA Page: https://duck.co/ia/view/missing_kids
> MissingKids: adjust tile height and width, minor updates to text casing and length

- share/spice/cryptocurrency/cryptocurrencylist.txt
I missed one, woops!
@MrChrisW 
https://duck.co/ia/view/cryptocurrency
> Fix missing comma

- share/spice/wikinews/wikinews.css
Fixes #2391 for wikinews css rules.
IA Page: http://duck.co/ia/view/wikinews
> WikiNews Spice: Fixes #2391

- template/lib/DDG/Spice/Example.pm
> Update Spice template URLs for new documentation

- share/spice/expand_url/expand_url.js
> Check for empty api response for expand_url

- lib/DDG/Spice/RenegoJobSearch.pm
- share/spice/renego_job_search/footer.handlebars
- share/spice/renego_job_search/renego_job_search.js
- t/RenegoJobSearch.t
This integrates the renego job search engine as a spice into duckduckgo.
---
https://duck.co/ia/view/renego_job_search
> Renego Job Search Spice

- lib/DDG/Spice/RustCargo.pm
- share/spice/rust_cargo/content.handlebars
- share/spice/rust_cargo/rust_cargo.js
- t/RustCargo.t
Continues #1852, addressing review comments.
-----
IA Page: https://duck.co/ia/view/rust_cargo
> Rust Cargo: Update of PR #1852

- lib/DDG/Spice/RustCargo.pm
Since we already have the IA pages https://duck.co/ia/view/rust_cargo
> RustCargo.pm: Remove metadata

- lib/DDG/Spice/SunRiseSet.pm
- t/SunRiseSet.t
Fixes #2145
https://duck.co/ia/view/sun_rise_set
> Sunrise/Sunset: Fixes #2145

- lib/DDG/Spice/Gulp.pm
- share/spice/gulp/footer.handlebars
- share/spice/gulp/gulp.js
- share/spice/ruby_gems/footer.handlebars
- t/Gulp.t
It uses http://npmsearch.com/ as the API provider which is what http://gulpjs.com/plugins/ uses.
---
https://duck.co/ia/view/gulp
> New Gulp Spice

- template/share/spice/example/example.js
> Correct spacing in JS template

- lib/DDG/Spice/Recipes.pm
Fixes #2480 
---
IA Page: https://duck.co/ia/view/recipes
> Recipes: Prevent this IA from triggering when 'Duck Duck Hack' is queried

- share/spice/seat_geek/events_by_artist/seat_geek_events_by_artist.js
SeatGeek Events (Artist): Use moment.js
Re: #1554
* `getDate()`
* `getMonth()`
* `getDay()`
* `months[]`
* `days[]`
**Note:** The majority of changes in the diff are a result of adding the `require()` block which pushed everything down one line and indented it. The core changes occur at lines 110-128.
---
IA Page: https://duck.co/ia/view/seat_geek_events_by_artist
> SeatGeek Events (Artist): Use moment.js

- lib/DDG/Spice/SeatGeek/EventsByArtist.pm
Fixes #2420 
Added event and events to startend trigger list.
IA Page: http://duck.co/ia/view/seat_geek_events_by_artist
> SeatGeek Events : Fixes #2420

- share/spice/couprex/couprex.css
- share/spice/couprex/couprex.js
Better handling of failed image requests. Using onerror to modify image src when request fails.
No more background-image magic.
-----
IA Page: https://duck.co/ia/view/couprex_coupons
> Couprex: Better handling of failed Clearbit image requests

- lib/DDG/Spice/SublimePackages.pm
- t/SublimePackages.t
Fixed the unwanted trigger
---
IA Page: https://duck.co/ia/view/sublime_packages
> SublimePackages: Fixes triggering for "sublime text alternatives" (Fixes #2495)

- share/spice/pwned/pwned.js
-----
IA Page: https://duck.co/ia/view/pwned
> Fix indentations, switch tabs to spaces

- share/spice/whois/whois.js
This is a partial fix for #2467. I'll add more info about my findings there.
---
IA Page: https://duck.co/ia/view/whois
> Whois: Fix JavaScript bug where we attempt to access an unassigned property of an object

- CONTRIBUTING.md
Spice version of same PR on Goodies.
> Better Contributing MD - slightly redundant to docs on purpose

- lib/DDG/Spice/Thumbtack.pm
- share/spice/thumbtack/thumbtack.js
- share/spice/thumbtack/top_keywords.txt
- t/Thumbtack.t
It returns a list of professionals able to perform the work specified in the query
Users often want to browse and hire professionals in their area. This IA addresses this
need by presenting them with a list of people who perform that work and allowing them
to browse reviews for local professionals. Yelp has a similar instant answer, but theirs
is more tailored to professionals who have physical business locations and not those
who travel. Examples of this could be electricians, house cleaners, movers, etc.
thumbtack.com
Thumbtack now has more …
> Add initial Thumbtack spice

- lib/DDG/Spice/Forecast.pm
Added "forecast" to the file forecast.pm as trigger.
IA Page: http://duck.co/ia/view/forecast
> Forecast: Added trigger "forecast"

- lib/DDG/Spice/RedditSubSearch.pm
- t/RedditSubSearch.t
Update trigger: 'r' -> '/r/'
Migrate to regex triggers
Fixes #2514 
IA Page: https://duck.co/ia/view/reddit_sub_search
> RedditSubSearch: Fixes #2514

- share/spice/dogo_news/dogo_news.css
@moollaza - will this close issue #2072? 
I'll work to close that issue, look like that's been pending a long time
> Fixing css issues (Issue #2072)

- share/spice/forecast/forecast.js
Forecast: Use moment.js
Addressing #1554 for this IA.
----
IA page: https://duck.co/ia/view/forecast
> Forecast: Use moment.js

- share/spice/forvo/forvo.css
- share/spice/forvo/forvo.handlebars
- share/spice/forvo/forvo.js
- Fix mobile display with updated CSS and HTML
- Fix UK Flag display with regex replacement
/cc @alexbaforvo 
---
IA Page: https://duck.co/ia/view/forvo
> Forvo: Fix mobile UI and UK Flag

- lib/DDG/Spice/Github.pm
- t/Github.t
> fixes github trigger for repo search #2512

- lib/DDG/Spice/IsItUp.pm
- t/IsItUp.t
> fixing isitup issue #2499

- .travis.yml
We can `dzil` manually and during release.
> Use prove on travis

- share/spice/product_hunt/product_hunt.js
Fixes #2550 
------
IA Page:  http://duck.co/ia/view/product_hunt
> Product Hunt: Update id to product_hunt

- lib/DDG/Spice/Thumbtack.pm
---
IA Page: https://duck.co/ia/view/thumbtack
> Remove Perl metadata, ported to IA Page

- share/spice/forvo/forvo.handlebars
- share/spice/forvo/forvo.js
Ensure audio is proxied through DDG. Requires internal PR to function in prod/beta.
Tested on Moollaza: https://moollaza.duckduckgo.com/?q=how+to+pronounce+saoirse&ia=answer
/cc @jagtalon 
---
IA Page: https://duck.co/ia/view/forvo
> Forvo: Proxy Audio through DDG

- lib/DDG/Spice/Seasons.pm
- lib/DDG/Spice/SunRiseSet.pm
- lib/DDG/Spice/Time.pm
Fixes #2511
---
https://duck.co/ia/view/time
https://duck.co/ia/view/seasons
https://duck.co/ia/view/sun_rise_set
> Specify version in requests made to timeanddate.com API

- lib/DDG/Spice/Quixey.pm
Change apps IA to use wrap_jsonp_callback. 
@bsstoner @moollaza
> wrap jsonp callback for apps

- lib/DDG/Spice/YachtSpecs.pm
Hi,
We recently modified the API from http to https, hence the update of the Instant answer here below.
Here you go @moollaza :smile: 
Existing AI https://duck.co/ia/view/yacht_specs
> Updated API from http to https

- lib/DDG/Spice/Forvo.pm
- t/Forvo.t
Following a [suggestion on Twitter](https://twitter.com/starrcourt/status/706861368096514048), added "how do i say" and "how do i pronounce" as triggers.
---
https://duck.co/ia/view/forvo
> Forvo: Added new triggers

- lib/DDG/Spice/Coupons.pm
- lib/DDG/Spice/LaunchLibrary.pm
- lib/DDG/Spice/PoliticalPolls.pm
- lib/DDG/Spice/Pwned.pm
- lib/DDG/Spice/RenegoJobSearch.pm
- lib/DDG/Spice/Riffsy.pm
- lib/DDG/Spice/Tides.pm
> Remove Perl Metadata

- lib/DDG/Spice/EconomicIndicators.pm
- lib/DDG/Spice/InEveryLang.pm
- lib/DDG/Spice/Quixey.pm
- lib/DDG/Spice/Transit/SEPTA.pm
- t/Quixey.t
See https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2333
Also updates a use of `YAML` to `YAML::XS`.
/cc @moollaza @zachthompson @jbarrett
> Update JSON to JSON::MaybeXS

- lib/DDG/Spice/Holiday.pm
- share/spice/holiday/holiday.js
- t/Holiday.t
90% of the work was done here:  https://github.com/duckduckgo/zeroclickinfo-spice/pull/1701.
IA page: https://duck.co/ia/view/holiday
> Finish support for Holiday IA

- lib/DDG/Spice/Arxiv.pm
- share/spice/arxiv/arxiv.js
- t/Arxiv.t
> Arxiv.org abstract retrieval

- lib/DDG/Spice/SalesTaxZipCode.pm
- share/spice/sales_tax_zip_code/sales_tax_zip_code.css
- share/spice/sales_tax_zip_code/sales_tax_zip_code.js
- t/SalesTaxZipCode.t
**Description** This IA provides breakdown of sales tax at state/county/local level. Different zipcodes with-in a state can have different sales tax.
**Snapshot images**
1. ![screenshot_salestaxzipcode_001](https://cloud.githubusercontent.com/assets/1039912/12989374/461198a2-d0d3-11e5-95b9-d782b5993882.PNG)
2. ![screenshot_salestaxzipcode_002](https://cloud.githubusercontent.com/assets/1039912/12989378/4ae206be-d0d3-11e5-9d31-81a138c04842.PNG)
-----
IA Page: https://duck.co/ia/view/sales_tax_zip_code
> New ZipCode Sales Tax Spice

- lib/DDG/Spice/NearEarthObjects.pm
- share/spice/near_earth_objects/near_earth_objects.js
- t/NearEarthObjects.t
IA: https://duck.co/ia/view/near_earth_objects
> New Spice: Near earth objects

- share/spice/product_hunt/product_hunt.js
Added tileSnippet to variants for making the tile height consistent. Fixes #2595.
IA Page: https://duck.co/ia/view/product_hunt
> Product Hunt : Fixes #2595 

- share/spice/public_holidays/public_holidays.js
- share/spice/public_holidays/record.handlebars
Fixes #2594
**Note:** I've renamed some variables to better describe what they contain, this will cause some merge conflicts with other PRs I have open, namely #2589.
---
http://duck.co/ia/view/public_holidays
> Public Holidays: Merge duplicate date/events

- lib/DDG/Spice/NearEarthObjects.pm
- share/spice/near_earth_objects/near_earth_objects.js
- t/NearEarthObjects.t
As suggested by @moollaza, made sure that only the specified queries trigger the IA.
Also enlarged the tile title text.
---
https://duck.co/ia/view/near_earth_objects
> NEOs: Added check for correct search query

- share/spice/rust_cargo/content.handlebars
---
https://duck.co/ia/view/rust_cargo
> Rust Cargo: Fixed missing quotation mark

- share/spice/alternative_to/alternative_to.js
this is a tmp fix until some utility for unescaping is in place
fixes #1305
---
IA Page: https://duck.co/ia/view/alternative_to
Maintainer: @vikashvverma
> unescape html entities in alternative to IA

- lib/DDG/Spice/Maps/Maps.pm
> Expand maps triggers

- share/spice/sound_cloud/sound_cloud.js
Lowering the signal from high to medium for SoundCloud triggering.
cc @moollaza
> Set signal to medium for soundcloud

- lib/DDG/Spice/Maps/Maps.pm
> Add 'map of' as an additional trigger for Maps

- lib/DDG/Spice/Couprex.pm
Refining the triggering conditions for couprex due to interference from unrelated queries.
/cc @AdamSC1-ddg 
---
IA Page: https://duck.co/ia/view/couprex
> Refine couprex trigger words

- lib/DDG/Spice/Experimentalia.pm
- share/spice/experimentalia/content.handlebars
- share/spice/experimentalia/experimentalia.css
- share/spice/experimentalia/experimentalia.js
- share/spice/experimentalia/footer.handlebars
IA testing spice that's running on beta.  I'll need to verify I can get this working on beta before merging. 
https://duck.co/ia/view/experimentalia
> IA Testing spice

- lib/DDG/Spice/WordOfTheDay.pm
- share/spice/word_of_the_day/content.handlebars
- share/spice/word_of_the_day/word_of_the_day.css
- share/spice/word_of_the_day/word_of_the_day.js
- t/WordOfTheDay.t
IA: https://duck.co/ia/view/word_of_the_day
> New WordOfTheDay Spice

- lib/DDG/Spice/Spotify.pm
- share/spice/spotify/footer.handlebars
- share/spice/spotify/spotify.js
- t/Spotify.t
IA: https://duck.co/ia/view/spotify
> New Spotify Spice

- share/spice/timer/timer.js
Referenced in https://github.com/duckduckgo/zeroclickinfo-spice/issues/2625#issuecomment-203701100.
Sorry, I realize that this will cause divergence from https://github.com/duckduckgo/zeroclickinfo-goodies/pull/2253, cc @GuiltyDolphin 
http://duck.co/ia/view/timer
> Timer: don't autostart unless it is the first timer

- lib/DDG/Spice/Maps/Maps.pm
- t/Maps/Maps.t
> Improve maps trigger for directions

- lib/DDG/Spice/Xkcd/Display.pm
Fixes #2634 
In order to be more up-to-date with newer XKCD comics, how does a 6 hour cache sound?
https://duck.co/ia/view/xkcd
> Invalidate XKCD cache every 6 hours

- lib/DDG/Spice/Metar.pm
- share/spice/metar/metar.js
- t/Metar.t
Given a query with a 4-letter ICAO code, return the METAR weather information from [avwx.rest/](http://avwx.rest/).
https://duck.co/ia/view/metar_information
> New METAR Spice Instant Answer

- share/spice/experimentalia/experimentalia.js
Removed the console log since this is getting kinda noisy in the console output.
Updated the install status to "success" since we're checking for that when setting the color install flag on line 83.
------
IA Page:  http://duck.co/ia/view/experimentalia
Maintainer: @vikashvverma
> remove console log and update status

- share/spice/experimentalia/experimentalia.js
Fixes https://github.com/duckduckgo/zeroclickinfo-spice/issues/2637
IA Page: http://duck.co/ia/view/experimentalia
> Fix IA Date

- lib/DDG/Spice/Maps/Maps.pm
- t/Maps/Maps.t
Blocking some navigational queries from triggering maps.
@bsstoner 
cc @andrey-p @mrshu
> Add query skip list for maps

- lib/DDG/Spice/Hex.pm
- share/spice/hex/hex.js
- t/Hex.t
Looks up packages on Hex, an Erlang/Elixir package manager
Allows quicker lookup of Erlang / Elixir packages
https://hex.pm
It is completely open-source and programmer-oriented, as well as being incredibly user-friendly.
**Is there any other alternative (better) data sources?**
No
```
hex install phoenix
elixir install httpotion
elixir ex_doc
```
Programmers, hobbyists, sysadmins …
> New Hex package manager Spice

- lib/DDG/Spice/Etsy.pm
- share/spice/etsy/etsy.js
- t/Etsy.t
> New Etsy Spice

- share/spice/hex/content.handlebars
- share/spice/hex/hex.js
Now the content section shows the latest version number, release date and the total number of releases for the given package.
If the maintainer of the package provides some links, we also show them in the content section.
-----
Hex IA page: https://duck.co/ia/view/hex
> Hex IA: Add more details in the content section

- lib/DDG/Spice/Airlines.pm
- lib/DDG/Spice/Flights/Route.pm
- share/spice/airlines/airlines.css
- share/spice/airlines/airlines.js
- share/spice/airlines/content.handlebars
- share/spice/flights/route/content.handlebars
- share/spice/flights/route/flights_route.js
- t/Flights.t
The Airlines IA has been adapted to the new design, matching the Flights IA. Included in this PR, other previous bugs has been fixed.
- The bar is showing the scheduled time and the dot the actual flight progress
- Added a 5 minute margin to be considered "Delayed"
- Status information matching the size of the flight and date information
- Show date beside the scheduled time if departure and arrival time is not in the same day
- Allowed relaxed queries for the FlightsIA #1838 
- Fixed other minor bugs
***
**IA Page**: https://duck.co/ia/view/airlines
Maintainer: @jdorweiler
> Airlines: New design and solved related issues

- share/spice/just_delete_me/content.handlebars
- share/spice/just_delete_me/footer.handlebars
- share/spice/just_delete_me/just_delete_me.js
https://duck.co/ia/view/just_delete_me
Removed embolden where existing
Added descriptive text for email link
Title now links to deletion page
Added fallback instructions when note does not exist
Refactored filtering to make it easier to read and understand
> JustDeleteMe: adds improvements suggested by @moollaza

- share/spice/spotify/spotify.js
Fixing Spotify IA
Hotfix. Check that images property contains content
---
Instant Answer Page: https://duck.co/ia/view/spotify
> Add check for images property length

- share/spice/dota2/dota2.js
Ensure query is lowercased before regex replace
---
Instant Answer Page: https://duck.co/ia/view/dota2
> ensure query is lowercased before regex replacement

- lib/DDG/Spice/Symbolab.pm
- t/Symbolab.t
https://duck.co/ia/view/symbolab
> Symbolab: Add support for queries of the form "integral of x^2"

- share/spice/ski_resorts/ski_resorts.js
Removes dynamic ID from IA
---
Instant Answer Page: https://duck.co/ia/view/ski_resorts
> Correctly hardcode ID property

- share/spice/couprex/couprex.js
- share/spice/reddit_sub_search/reddit_sub_search.js
- t/Couprex.t
After https://github.com/duckduckgo/duckduckgo-utils/pull/8 got merged, we can remove ad-hoc functions :+1: 
---
https://duck.co/ia/view/couprex
https://duck.co/ia/view/reddit_sub_search
> Couprex & RedditSubSearch: Use unescape

- lib/DDG/Spice/BrainyQuote.pm
- lib/DDG/Spice/QuoteOfTheDay.pm
- share/spice/quote_of_the_day/content.handlebars
- share/spice/quote_of_the_day/quote_of_the_day.css
- share/spice/quote_of_the_day/quote_of_the_day.js
- t/QuoteOfTheDay.t
IA : https://duck.co/ia/view/quote_of_the_day
> New Quote of The Day Spice

- lib/DDG/Spice/Parking.pm
- t/Parking.t
https://duck.co/ia/view/parking
> Parking: Don't pass timezone to api.  Display times in local time zone instead.

- lib/DDG/Spice/Rfc.pm
- share/spice/rfc/footer.handlebars
- share/spice/rfc/rfc.js
- t/Rfc.t
This instant answer provides quick access to RFCs relating to your search.
https://duck.co/ia/view/request_for_comments
> New RFC Spice

- lib/DDG/Spice/HackerNews.pm
- lib/DDG/Spice/JrDevJobs.pm
- share/spice/jr_dev_jobs/footer.handlebars
- share/spice/jr_dev_jobs/jr_dev_jobs.js
- t/JrDevJobs.t
https://duck.co/ia/view/jr_devjobs
> New Jr.Devjobs Spice

- lib/DDG/Spice/RustCargo.pm
Adds the triggers **rust crate** or **cargo crate**
Fixes #2719
@GuiltyDolphin, @lambda, @tagawa, @TomBebbington
---
https://duck.co/ia/view/rust_cargo
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @TomBebbington
> Updated triggers (#2719)

- share/spice/just_delete_me/just_delete_me.js
Replaced String.prototype.includes() calls with calls to String.prototype.indexOf() for better support throughout different browsers.
Fixes #2743.
String.includes() method which has been used, was not supported across all browsers.
Replaced this with something that works in Chrome, Safari, FireFox and IE 9+
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/just_delete_me
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe
> Just Delete Me: Fix #2743 by replacing .includes() with .indexOf()

- share/spice/rfc/rfc.js
---
Instant Answer Page: https://duck.co/ia/view/request_for_comments
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @imwally
> RFC: Update ID in JS to match IA Page

- share/spice/fedora_project_package_db/fedora_project_package_db.js
---
Instant Answer Page: https://duck.co/ia/view/{{ID}}
> check for api_result

- share/spice/iplookup/iplookup.js
Improved error checking
/cc @jagtalon 
---
Instant Answer Page: https://duck.co/ia/view/iplookup
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mintsoft
> Add guard to iplookup

- share/spice/dictionary/definition/dictionary_definition.js
---
Instant Answer Page: https://duck.co/ia/view/dictionary_definition
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon
> Guard against no page reference in dictionary definition

- share/spice/dota2/dota2.js
---
Instant Answer Page: https://duck.co/ia/view/dota2
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @echosa
> Add guards to dota2

- lib/DDG/Spice/Shorten.pm
- [ x ] Bug fix: **`Shorten: Fix 2744`**
Changed HTTP to HTTPS
---
Instant Answer Page: https://duck.co/ia/view/shorten
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @danjarvis
> Changed 'http' to 'https' (fixes #2744)

- lib/DDG/Spice/JrDevJobs.pm
- share/spice/jr_dev_jobs/jr_dev_jobs.js
- t/JrDevJobs.t
Use 4-space soft tabs.
Update regex matching
Use `startend` triggers
Add more tests
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/jr_dev_jobs
> Jr.Devjobs: Improve regex, tabbing, and add tests

- lib/DDG/Spice/Dictionary/Definition.pm
Words like "cats" will autocorrect to "cat".
Words like "brobdingnagian" will autocorrect to "Brobdingnagian".
---
Instant Answer Page: https://duck.co/ia/view/dictionary_definition
> Dictionary Definition: Enable useCanonical in the upstream provider.

- lib/DDG/Spice/BikeSharing/CitiBikeNYC.pm
- share/spice/bike_sharing/citi_bike_nyc/bike_sharing_citi_bike_nyc.js
fixes #2784
https://duck.co/ia/view/citi_bike_nyc
> proxy citibike nyc status calls

- lib/DDG/Spice/BitbucketStatus.pm
- share/spice/bitbucket_status/bitbucket_status.css
- share/spice/bitbucket_status/bitbucket_status.js
- share/spice/bitbucket_status/content.handlebars
- t/BitbucketStatus.t
Return Bitbucket status
---
Instant Answer Page: https://duck.co/ia/view/bitbucket_status
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @qqq3
> New Bitbucket status Spice

- share/spice/gravatar/gravatar.js
Added function for converting special chars into HTML.
Not sure whether creating HTML element and pasting-cutting text from it is the best way of doing this, so I would appreciate any idea which would solve this problem in a nicer way.
Fixes  #2676
to @moollaza 
---
IA Page: http://duck.co/ia/view/gravatar
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adman
Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>
> gravatar: fixed special chars decoding in bio

- share/spice/bitbucket_status/bitbucket_status.js
Change tab `name` from `Status` to `Answer`
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/bitbucket_status
> Bitbucket Status: Change tab name

- share/spice/haxelib/content.handlebars
- share/spice/haxelib/haxelib.js
This PR basically:
+ Adds project tags to the box panel.
+ Adds the project's owner to box panel.
+ Adds the project's website to box panel.
+ Moves the license to the box panel.
+ Adds a changes box to the box panel with the summary of the latest change to the package.
---
Instant Answer Page: https://duck.co/ia/view/haxelib
> Haxelib: Use newer text layout and include owner, changes and tags in box data

- share/spice/drinks/drinks.js
Added the URL to the returned results.
Fixes #2814 
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/drinks
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mutilator
> Drinks: Add url for drinks in results

- lib/DDG/Spice/Tides.pm
- t/Tides.t
The tide spice should be triggered for more queries as suggested
on issue tracker. It could be done by adding more trigger words.
* added more triggers
See also: #2737
---
Instant Answer Page: https://duck.co/ia/view/tides
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mattr555
> tide: Add more triggers

- share/spice/dota2/dota2.js
Fixes #2793 
---
Instant Answer Page: https://duck.co/ia/view/dota2 
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @echosa
> DOTA 2 Heroes: Fix the buggy "more at" link

- lib/DDG/Spice/GoWatchIt.pm
- share/spice/go_watch_it/go_watch_it.js
Fixes #2213 
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/go_watch_it
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @plexusent
> GoWatchIt: Code cleanup and refractor

- lib/DDG/Spice/Hex.pm
Removed `elixir` startend trigger. This is going to cause an immediate problem with the elixir fathead with is coming to a conclusion. As this is more to do with hex and _not_ the elixir programming language, I have removed the trigger.
---
Instant Answer Page: https://duck.co/ia/view/hex
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @milmazz
> Removed conflicting `Elixir` start trigger. Added more triggers.

- share/spice/experimentalia/experimentalia.css
Issue #2635
Added `.zci--<id>` to the css rules.
IA Page: http://duck.co/ia/view/experimentalia
> Namespace "Experimental IA" Spice CSS

- lib/DDG/Spice/IsItUp.pm
- t/IsItUp.t
Modified regex to match Unicode characters, used Domain::PublicSuffix instead of regular expression to match and get root domain name, used Data::Validate::IP to ensure IP is valid IPv4 address, modified test file.
Fixes #220 
@MrChrisW @moollaza 
---
Instant Answer Page: https://duck.co/ia/view/is_it_up
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @mrshu
> IsItUp: Attempt to add support for domains containing unicode characters for #220

- share/spice/detect_lang/content.handlebars
- share/spice/detect_lang/detect_lang.js
Update the code to new format having spice call in a closure
Fixes #988 for this IA
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/detect_lang
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @ghedo
> DetectLang: Update code to new format and changed template to text

- lib/DDG/Spice/SearchCode.pm
- share/spice/search_code/content.handlebars
- share/spice/search_code/search_code.handlebars
- share/spice/search_code/search_code.js
SearchCode IA now uses the new Spice API and uses an existing template.
Fixes #1814 
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/search_code
> SearchCode: Update to new Spice API

- template/lib/DDG/Spice/Example.pm
Added `use strict;` to the template. It's good to have 👍
> Add `use strict;` to Spice template

- share/spice/news/news.js
Adding the idField of the news tile as the articles url. so we have a unique identifier to select it.
---
Instant Answer Page: https://duck.co/ia/view/news
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @jagtalon
> update to spice config to match news config in frontend code

- share/spice/git_book_status/git_book_status.css
Update CSS - remove unnecessary class
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/gitbook_status
> Gitbook Status: remove unnecessary CSS class

- share/spice/npm/npm.js
Added TonicDev link in IA results alongside `More at` text.
@moollaza @MariagraziaAlastra 
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @remixz
> NPM: Add TonicDev link

- share/spice/experimentalia/experimentalia.js
Show Fathead PRs on beta
Fixes #2843 - include fathead PRs result in IA
@jdorweiler 
---
Instant Answer Page: https://duck.co/ia/view/experimentalia
> Experimentalia: Show fathead PRs

- share/spice/near_earth_objects/near_earth_objects.js
Moved signal property out of meta object.
---
Instant Answer Page: https://duck.co/ia/view/near_earth_objects
> Moved signal property out of meta object

- template/lib/DDG/Spice/Example.pm
- template/share/spice/example/example.js
Fixes https://github.com/duckduckgo/zeroclickinfo-goodies/issues/3347
@moollaza @GuiltyDolphin
> Templates: Use single quotes for strings

- share/spice/amazon/amazon.js
- share/spice/isbn/isbn.js
---
Instant Answer Page: https://duck.co/ia/view/{{ID}}
> Remove ratings/reviews from Amazon IA's

- share/spice/search_code/search_code.js
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/search_code
> SearchCode: Add more at link

- lib/DDG/Spice/Movie.pm
- share/spice/movie/buy.handlebars
- share/spice/movie/movie.css
- share/spice/movie/movie.js
- share/spice/movie/subtitle_content.handlebars
- t/Movie.t
There was no support for cast of movies.
This commit add `cast` `casts`, `cast of` and `casts of` triggers and displays movie cast's picture as well as name and character. 
Fixes https://github.com/duckduckgo/zeroclickinfo-spice/issues/2685 - Add movie cast support
@GuiltyDolphin 
---
Instant Answer Page: https://duck.co/ia/view/movie
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @moollaza
> Add 'movie cast' support

- lib/DDG/Spice/Astrobin/Apod.pm
I added "apod" as a trigger. Fixes #2582 
---
http://duck.co/ia/view/apod
Maintainer: @killerfish
> Added "apod" as trigger #2582

- lib/DDG/Spice/AlternativeTo.pm
- t/AlternativeTo.t
I noticed that this IA doesn't get triggered for query `opensource alternative to github` because the space between `open` and `space` wasn't optional.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/alternative_to
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @vikashvverma
> AlternativeTo: Improve triggering

- share/spice/expand_url/title_content.handlebars
Fixed url link
Fixes #2909 
@moollaza 
@tagawa 
---
IA Page: http://duck.co/ia/view/expand_url
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @adman
Signed-off-by: Adrian Matejov <a.matejov@centrum.sk>
> expandurl: fixed link of expanded url (fixes #2909)

- lib/DDG/Spice/Maps/Maps.pm
Call the mapbox API via HTTPS instead of HTTP.
@b2ddg 
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @nilnilnil
> Call the mapbox API via HTTPS instead of HTTP.

- lib/DDG/Spice/Untappd.pm
- share/spice/untappd/content.handlebars
- share/spice/untappd/footer.handlebars
- share/spice/untappd/untappd.css
- share/spice/untappd/untappd.js
- t/Untappd.t
Instant Answer Page: https://duck.co/ia/view/untappd
> New Untappd Instant Answer

- lib/DDG/Spice/Recipes.pm
WIP
IA Page: http://duck.co/ia/view/recipes
Fixes #2530
> Fixes #2530 - Recipes: triggering on `recipes.com`

- share/spice/github/github.js
@jdorweiler seeing some errors in the logs when the items array comes back empty, added more guards at the top.
> More guards for github

- share/spice/forecast/forecast.js
- share/spice/forecast/forecast_detail_mobile.handlebars
- share/spice/forecast/forecast_item.handlebars
Fixes https://github.com/duckduckgo/zeroclickinfo-spice/issues/2510
IA Page: http://duck.co/ia/view/forecast
Maintainer: @himanshu0113
> Add humidity info to weather IA

- lib/DDG/Spice/Holiday.pm
- Removed the check for an existing .txt file because it always failed in a production 
environment.
- Moved static variables out of `handle`
- Order holidays by length to grab longest match (e.g. "christmas day" vs. "christmas")
- Strip holiday from query first because some holidays contain a year in the name
- Added `\b` to regexes to ensure we don't match on a substring
@jdorweiler @sekhavati 
---
Instant Answer Page: https://duck.co/ia/view/holiday
> Rewrite Holidays.pm to work in production

- lib/DDG/Spice/Holiday.pm
- t/Holiday.t
- Ensure we don't load non-existent files in `share()`
- Switch variables to canonical `snake_case` (from `camelCase`)
- add test to ensure no results are returned for unsupported countries
@sekhavati 
---
Instant Answer Page: https://duck.co/ia/view/holiday
> Holiday: Better method for avoiding unsupported countries, update test to verify

- lib/DDG/Spice/Maps/Maps.pm
Preserve the same behavior of the v4 geocoder.
@nilnilnil 
---
Instant Answer Page: https://duck.co/ia/view/{{ID}}
> Preserve the same behavior of v4 by disregarding POI

- lib/DDG/Spice/CaniuseLists.pm
- share/spice/caniuse_lists/caniuse_lists.js
- t/CaniuseLists.t
Added anchors in the regular expression to ensure extra words are not allowed. Removed loop from javascript which was unnecessary after adding the anchors and updated the test file.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/caniuse_lists
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @rasikapohankar
> CanIUse Spice: Update regex

- lib/DDG/Spice/Maps/Maps.pm
> Add -tube- to skip words to avoid triggering for queries like -tube map-

- share/spice/movies/filmography/movies_filmography.js
ID should be `movies_filmography` instead of just `filmography`
---
Instant Answer Page: https://duck.co/ia/view/movies_filmography
> ID should be consistent everywhere

- share/spice/search_code/search_code.js
Instant Answer Page: https://duck.co/ia/view/search_code
> Check if api_result exists before using it.

- share/spice/forecast/forecast.css
- share/spice/forecast/forecast.js
- share/spice/forecast/forecast_detail_mobile.handlebars
- share/spice/forecast/forecast_item.handlebars
- [X ] Improvement
- [X ] Enhancement: **`Forecast: Fixes #2795 by adding precipitation to the forecast result for current conditions`**
As per enhancement suggested in #2795, this change will add precipitation to be included in the forecast result for current conditions.  In addition to updating the handlebars and the js to include precipitation in the current results, css was also updated in order to allow enough space for precipitation to be displayed.
Fixes #2795 - This is an enhancement that will add precipitation into the forecast result.
@himanshu0113
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): …
> Forecast: Addition of precipitation to the forecast result (#2795)

- share/spice/forecast/forecast.js
Applied `Math.round` function to the humidity value
Should fix a floating point issue as reported here: http://blog.lerner.co.il/fun-with-floats/
---
> Forecast: Rounded humidity value

- README.md
1. Updated README to reflect the Programming Mission: https://forum.duckduckhack.com/t/duckduckhack-programming-mission-overview/53
- We are focused on validating the tools/processes used to create Instant Answers on DuckDuckGo by working directly with contributors to a single search topic: Programming-related searches. We're starting with CSS, JS, Perl, Python, and Swift but plan to expand into other programming languages/frameworks (and other topics) as the new community grows. 
2. Introduces the focus and policy on programming-related Instant Answers: 
- We are only reviewing/accepting Pull Requests/Issues within the Programming Mission.
> README update for Prog Mission alert

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
Update the PR template and contributing.md for Programming Mission callouts
@alohaas
> more updates for programming mission

- share/spice/npm/npm.js
This comes because of rebranding of tonicdev as runkit. Tonicdev links are anyway redirected
to corresponding runkit ones.
What changes does this PR introduce? 
What issues or discussions (if any) does this PR address? Please provide the issue # or link.
@moollaza 
---
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @remixz
> NPM: Change tonicdev to runkit

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- Updates the PR template to use a new format and HTML comments
- Adds new Issue template
@GuiltyDolphin
> Add issue template, update pr template

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Simplified HTML comments in PR and Issue templates to make them easier to use/read
> PR and Issue Templates: Simplification of HTML Comments

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- Simplify README, emphasize Programming Mission
- Simplify ISSUE_TEMPLATE and PULL_REQUEST_TEMPLATE
- Mimicking changes made to Fathead REPO
@MariagraziaAlastra @tagawa
> README Updates

- share/spice/sound_cloud/sound_cloud.js
> Add trailing slash to audio URL so it doesn't redirect

- lib/DDG/Spice/Forecast.pm
> Forecast: Use first two chars from locale as language

- share/spice/recipes/recipes.js
> Recipes: Remove detail pane, send directly to Yummly on click

- share/spice/open_nic/content.handlebars
- share/spice/open_nic/open_nic.css
This fixes the style issues with the Opennic IA (some site-wide style changes made it unreadable)
I already made some tests:
- Linux: Firefox
- OSX: Firefox, Safari
- Windows10: Firefox, Chrome, Opera, Edge, IE
- iOS: Dolphin, Safari
---
IA Page: https://duck.co/ia/view/open_nic
> Opennic: css update to fix width issues

- share/spice/movies/filmography/movies_filmography.js
Moves getting `castId` after data check.
#2995
@mention any relevant people/organizations
@b2ddg @jagtalon @moollaza 
---
Instant Answer Page: https://duck.co/ia/view/movies_filmography
@whalenrp
> Fixes #2995: Movies/Filmography JS Error

- share/spice/news/news.js
> Put news relevancy behind feature flag

- share/spice/amazon/amazon.js
> Fail amazon if there's less than 2 results

- share/spice/today_in_history/content.handlebars
- share/spice/today_in_history/today_in_history.css
- Finalize this IA for launch...finally!
@killerfish 
---
Instant Answer Page: https://duck.co/ia/view/today_in_history
> Today In History: Migrate css font properties to classes, set high to hide overflow

- share/spice/bitcoin/bitcoin.js
Fixes for transaction data from BitEasy API:
- Fixed date time stamp(earlier undefined)
- Fixed meta link
Fixes #3079 
@bsstoner @jmg 
---
Instant Answer Page: https://duck.co/ia/view/bitcoin
> Bitcoin: Fixes transactions

- lib/DDG/Spice/Npm.pm
- share/spice/npm/content.handlebars
- share/spice/npm/footer.handlebars
- share/spice/npm/npm.js
- t/Npm.t
Changes from a single detail response to a search style response
Fixes #3098 
Note that this leaves the README.md with an image of the previous incarnation of the npm spice
@pjhampton
---
> JavaScript: Switch NPM to new API and tile view

- lib/DDG/Spice/Maps/Maps.pm
- t/Maps/Maps.t
Updating the query trigger to remove some map related words.
@tommytommytommy 
cc @bsstoner
> Remove map keywords from the query trigger

- lib/DDG/Spice/Npm.pm
Added more triggers based on John's unanswered query data for node/npm related queries. This now, AFAIK, reflects how people are searching for npm packages. These are just awkward edge case triggers. 
@moollaza 
---
> npm: Updated triggers based on unanswered query data.

- lib/DDG/Spice/Currency.pm
- t/Currency.t
This 2 character change reflects user feedback described here https://github.com/duckduckgo/zeroclickinfo-spice/issues/3137
Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3137
---
Instant Answer Page: http://duck.co/ia/view/currency
> Currency: '=' to trigger 

- lib/DDG/Spice/SkyscannerFlightSearch.pm
- share/spice/skyscanner_flight_search/skyscanner_flight_search.js
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/skyscanner_flight_search
> Skyscanner flight search

- lib/DDG/Spice/Maps/Maps.pm
Changed "cocation" into "location" in the IA abstract.
@moollaza @gautamkrishnar 
---
> Maps: Fixed typo error in the abstract

- t/Currency.t
Added a test for the change I had made in an earlier PR.
Requested in PR #3182 
@moollaza 
---
> Currency: Added test for ruble trigger

- share/spice/news/news.js
Enable/disable relevancy on a per-story basis
> Allow per-story relevancy filtering

- lib/DDG/SpiceRole/NumberStyle.pm
- lib/DDG/SpiceRole/NumberStyler.pm
- t/Currency.t
Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3109#issuecomment-287474392
I've added a test to Currency to prove the role is hooked up
@moollaza 
---
Instant Answer Page: http://duck.co/ia/view/currency
> NumberRole: Updating from the goodie repo

- lib/DDG/Spice/Metar.pm
- share/spice/metar/metar.js
Fixes #2897 
- Change the API url to use https. 
- Add a "maintenance check warning" indicator to the table when that warning is specified in a metar.
---
Instant Answer Page: https://duck.co/ia/view/metar
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @santigl
> METAR Information: Change API url to https. Add new translation.

- share/spice/maps/maps/maps_maps.js
IA Page: https://duck.co/ia/view/maps_maps
> Skip relevancy for maps experiment

- share/spice/package_tracking/package_tracking.js
Checks the API result for a carrier name to prevent broken results
---
> Package Tracking: Ensure we have a carrier for the result

- lib/DDG/Spice/Dictionary/Definition.pm
> Update dictionary upstream timeouts

- share/spice/maps/maps/maps_maps.js
Internal: https://app.asana.com/0/72649045549333/309019162904994
Adding relevancy check to map module code
@bsstoner 
---
> add relevancy check to spice experiment code.

- share/spice/maps/maps/maps_maps.js
Internal: https://app.asana.com/0/246491496396031/309019162904981
@bsstoner 
---
> move mapbox relevance filter from .7 to .6

- lib/DDG/Spice/Riffsy.pm
- share/spice/riffsy/riffsy.js
The company changed their name from Riffsy to Tenor in 2016. The links, including API, are still valid however.
---
Instant Answer Page: https://duck.co/ia/view/riffsy
> Riffsy: Updated source name

- lib/DDG/Spice/Maps/Maps.pm
We did this for the dictionary spice a few weeks ago and it eliminated a ton of the fallbacks. I want to try it on maps and see if this will help at all.
```
ab -c2 -n100 https://duckduckgo.com/local.js?q=41%20perry%20street%2C%20new%20york
va-xl1
Connection Times (ms)
min  mean[+/-sd] median   max
Connect:        3    4   0.6      4       9
Processing:   605  760 112.0    736    1143
Waiting:      605  760 112.0    736    1143
Total:        609  764 112.2    740    1147
Percentage of the requests served within a certain time (ms)
50%    740
66%    787
75%    811
80%    824
90%    913
95%   1037
98%   1121
99%   1147
100%   1147 (longest request)
sing-xl1
Connection Times (ms)
min  mean[+/-sd] median   max
Connect:        2    3   0.4      3       5
Processing:   714  774  45.9    760 …
```
> Add hard upstream timeouts for maps

- lib/DDG/Spice/Maps/Maps.pm
cc @duendex 
This reverts commit feee52d562e905c887598d96dc80b07613db5511.
---
> Revert "Add hard upstream timeouts for maps (#3241)"

- share/spice/currency/currency.js
Fixes instances of currencies with non-standard number of decimals geting rounded to 2 decimal places.
Fixes #1465 and #2724 
@javathunderman @MonoMonkey @MrChrisW
---
> Currency: Ensures correct number of decimal places for non-standard currencies

- lib/DDG/Spice/Currency.pm
- t/Currency.t
Fixes #3129 
@moollaza  @pjhampton 
> Currency Conversion: Adds price as a keyword

- lib/DDG/Spice/Forecast.pm
> Add upstream timeout for forecast

- lib/DDG/Spice/Forecast.pm
Rolling back, it's causing more fallbacks somehow, need to reassess.
/cc @b2ddg
> Disable forecast timeout

- share/spice/npm/content.handlebars
- share/spice/npm/npm.js
Enhanced the UI for npm spice as described #3266 
Fixes #3266 
@pjhampton 
---
> npm: Enhanced UI/UX

- share/spice/package_tracking/package_tracking.js
Corrects string comparison logic by normalizing text before comparing
---
> Package Tracking: Ensure strings are lowercased when compared

- lib/DDG/Spice/Currency.pm
- t/Currency.t
Stop triggering on Mop / Top triggering edge case.
https://app.asana.com/0/inbox/246900294405161/297648046603684/297648876948776
@moollaza 
@bsstoner 
---
> Currency: Fix Mop / Top triggering edge case

- lib/DDG/Spice/Currency.pm
Fixes the triggering issue described in https://github.com/duckduckgo/zeroclickinfo-spice/pull/3272#issuecomment-304002606
https://github.com/duckduckgo/zeroclickinfo-spice/pull/3272#issuecomment-304002606
@moollaza @adityatandon007 
---
> Currency: Tightened Natural Language triggering

- share/spice/currency/currency.css
- share/spice/currency/currency.js
Hande inputs increments, and add back left padding.
Internal
@moollaza 
---
> Currency: Fix Padding. Add change handling

- lib/DDG/Spice/Cryptocurrency.pm
> Cryptocurrency: Modify caching to 1m

- t/Cryptopcurrency.t
Missed this in the other PR, should have ran the tests.
cc @pjhampton @moollaza
> Cryptocurrency: Update tests

- share/spice/currency/currency.css
Removes red border on ff
https://app.asana.com/0/246900294405162/351096579371314
@andrey-p @bsstoner @moollaza 
---
> Currency: Remove red border on FF validation.

- share/spice/currency/currency.js
This fixes the significant digits issue with the currency.
@bsstoner 
---
> Currency: Fixes sig figs issue.

- share/spice/cryptocurrency/cryptocurrency.js
Defaults to symbols on smaller devices
@bsstoner @moollaza 
---
> Cryptocurrency: Swap full names with symbols on mobile

- share/spice/cryptocurrency/cryptocurrency.css
Reduces font-sizes as requested by the design team
@moollaza 
---
> Cryptocurrency: Reduce font-size

- share/spice/currency/currency.css
Update the font-size as requested by design
---
> Currency: Update the font-size

- CONTRIBUTING.md
Update to match Goodies repo. Link out to new externally hosted contributing doc.
> Update to match Goodies Repo

- share/spice/forecast/forecast.js
- Moves the DOM related logic into an `onShow` function so it is guaranteed to run once the Spice DOM is ready and built.
- Fixed indentation to make things more legible
- To view only non-whitespace changes: https://github.com/duckduckgo/zeroclickinfo-spice/pull/3340/files?w=1
@duendex 
---
> Forecast: Fix temperature switch

- lib/DDG/Spice/Cryptocurrency.pm
- share/spice/cryptocurrency/cryptocurrency.js
Swaps out the external api url with the internal proxy url
Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3349
@moollaza 
---
> Cryptocurrency: Swap out external endpoint for proxy endpoint.

- share/spice/just_delete_me/just_delete_me.js
IA will no longer display partial matches
Fixes also display of exact name matches which was broken before but unnoticed.
#2961
@moollaza @tagawa @mrshu @edgesince84 
---
Instant Answer Page: https://duck.co/ia/view/just_delete_me
[Maintainer](http://docs.duckduckhack.com/maintaining/guidelines.html): @riqpe
> Fixes #2961 by removing partial matches

- share/spice/thesaurus/thesaurus.js
Fix #3111
@lactose 
---
Instant Answer Page: https://duck.co/ia/view/thesaurus
> Thesaurus: Don't display IA result if searching for antonym not found

- share/spice/github/github.js
See #3333 
Fixes #3333 
@pjhampton 
---
Instant Answer Page: https://duck.co/ia/view/github
> GitHub: Swap Stars in infobox with SSH URL

- .travis.yml
Postpones Trusty (14.04.5 LTS) move and keeps the builds against Precise (12.04.5 LTS)
> Repo: Update travis config

- lib/DDG/Spice/Xkcd/Display.pm
Carries on from earlier PR
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/Xkcd
> Xkcd: Update to spice endpoint as https

- lib/DDG/Spice/Currency.pm
- t/Currency.t
- Patches overtriggering
- Expands triggering based on community member suggestion
Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3374
---
> Currency: Patches overtriggering. Expand Triggering.

- lib/DDG/Spice/WGHA.pm
- t/WGHA.t
Remove n-gram triggers preventing this IA to over trigger on unrelated queries.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/wgha
> WGHA: Fix WGHA overtriggering.

- lib/DDG/Spice/Glassdoor.pm
- share/spice/glassdoor/glassdoor.js
An attempt at reducing the Glassdoor fallbacks.
@moollaza 
---
Instant Answer Page: https://duck.co/ia/view/glassdoor
> Glassdoor: Add upstream timeouts.

- lib/DDG/Spice/Currency.pm
- t/Currency.t
Patches some over-triggering (discovered from user feedback))
@moollaza 
---
> Currency: Patch overtriggering

- lib/DDG/Spice/Quandl/Fundamentals.pm
- lib/DDG/Spice/Quandl/HomeValues.pm
- lib/DDG/Spice/Quandl/WorldBank.pm
Remainder of fixes for: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3396
---
Instant Answer Page: https://duck.co/ia/view/quandl_fundamentals
> Quandl: Fixes for Perl 5.24

- share/spice/cryptocurrency/cryptocurrency.js
- t/Cryptocurrency.t
Add a high signal for cryptocurrency.
@moollaza 
---
> Cryptocurrency: Add high signal.

- lib/DDG/Spice/Github.pm
- t/Github.t
Fixes overlapping triggering with Github Issues triggers
#3170 #3264 
@moollaza @pjhampton 
---
Instant Answer Page: https://duck.co/ia/view/github
> Github: Handle overlapping triggers with Issues IA

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
Updates the PR Template and READMEs.
> REPO: Update pr/readme template 

- lib/DDG/Spice/Forecast.pm
- share/spice/forecast/forecast.js
- t/Forecast.t
Uses timezone hinting to work around the celcius bug.
Fixes: https://github.com/duckduckgo/zeroclickinfo-spice/issues/3353
---
> Forcast: Default to Celcius for non US 

- .travis.yml
> Switch to use Ubuntu Trusty

- share/spice/maps/maps/maps_maps.js
> call duckbar.failed() for empty maps responses

- share/spice/amazon/amazon.js
> Remove Products drop down

- share/spice/amazon/amazon.js
> Remove products dropdown

- share/spice/currency/detail.handlebars
Fixes bug where firefox only treated integers as valid.
Fixes #3413 
@pjhampton 
---
> Currency: Fix input step

- share/spice/maps/directions/maps_directions.js
- share/spice/maps/maps/maps_maps.js
- share/spice/maps/places/maps_places.js
> Remove maps requires

- share/spice/maps/directions/maps_directions.js
> revert maps_directions changes

- share/spice/videos/videos.js
> do not send next meta data

- share/spice/amazon/amazon.js
Products: Updates the answer type field so we can override some shared functions internally.
> Update Products answer type

- lib/DDG/Spice/Dictionary/Definition.pm
- lib/DDG/Spice/Holiday.pm
> Force Holiday and Dictionary/Definition to have JS content-type

- share/spice/amazon/amazon.css
- share/spice/amazon/amazon.js
- share/spice/amazon/branded_products_item.handlebars
Implements new UI Experiment by using a new custom Spice template that allows for a Brand link.
---
Instant Answer Page: https://duck.co/ia/view/products
> Amazon: Implement UI Tests

- share/spice/amazon/amazon.css
- share/spice/amazon/amazon.js
- share/spice/amazon/button_products_item.handlebars
More updates to Amazon for UI experiments
---
Instant Answer Page: https://duck.co/ia/view/products
> Amazon: Shop Now button experiment

- share/spice/amazon/amazon.js
Work-in-progress, just putting up the PR to get started on testing adding back ratings/reviews...
cc: @moollaza
> Re-enable Amazon ratings

- share/spice/amazon/amazon.js
Start using new `source` param in API response
---
Instant Answer Page: https://duck.co/ia/view/products
> Products: Use new source param to specify result provider

- share/spice/currency/currency.js
**Internal Review Only**
This replaces the $.get function with $.ajax so that we can get the data type to text.
> use jquery ajax function over get

- share/spice/currency/currency.js
> set type to text

- lib/DDG/Spice/Forecast.pm
> Add foreign trigger words for weather

- share/spice/amazon/amazon.js
> Add affiliate label for amazon

- share/spice/amazon/amazon.js
Add "ad" label to Products
@bsstoner
> Add affiliate label

- share/spice/sports/sports.js
> Link Sportradar attribution

- lib/DDG/Spice/Maps/Places.pm
Disables the baseline regex for the categories experiment.
---
> Disable the baseline regex for categories expeiment

- share/spice/news/news.js
We don't need any of this in the spice anymore, it's done elsewhere now.
> Simplify news.js code

- dist.ini
> Added whitespace to test auto release

- share/spice/cryptocurrency/cryptocurrency.css
- share/spice/currency/currency.css
- Updates Currency and Crytocurrency IA inputs
@bsstoner @bbraithwaite
> Update border-radius to 4px

- lib/DDG/Spice/Rhymes.pm
- Upgrade API to HTTPS to bring back online
@brianhall
> Switch API to HTTPS to handle redirect

- lib/DDG/Spice/Dictionary/Definition.pm
> Wrap wordnik API calls with callback
